CREATE TABLE CHARACTER_TYPES (CHARACTER_TYPE CHARACTER(8), VARCHAR_TYPE VARCHAR(8),
CLOB_TYPE CLOB(8), GRAPHIC_TYPE GRAPHIC(8), VARGRAPHIC_TYPE VARGRAPHIC(255), DBCLOB_TYPE DBCLOB(8));

INSERT INTO CHARACTER_TYPES(CHARACTER_TYPE, VARCHAR_TYPE, CLOB_TYPE, GRAPHIC_TYPE, VARGRAPHIC_TYPE, DBCLOB_TYPE) VALUES ('Datagrok', 'Datagrok', 'Datagrok', 'Datagrok', 'Datagrok', 'Datagrok');
