/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace queries {
  export async function assaysByOrganism(organism: string ): Promise<DG.DataFrame> {
    return await grok.data.query('Biologics:AssaysByOrganism', { organism });
  }

  export async function adcsLinkedToDrug(drugID: string ): Promise<DG.DataFrame> {
    return await grok.data.query('Biologics:AdcsLinkedToDrug', { drugID });
  }
}

export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('Biologics:Info', {});
  }

  export async function createDemoBiologicsData(): Promise<void> {
    return await grok.functions.call('Biologics:CreateDemoBiologicsData', {});
  }

  /**
  Populates missing ADC glyphs with random PNG (base64) strings
  */
  export async function populateAdcGlyphs(): Promise<void> {
    return await grok.functions.call('Biologics:PopulateAdcGlyphs', {});
  }

  export async function autostartBiologics(): Promise<void> {
    return await grok.functions.call('Biologics:AutostartBiologics', {});
  }
}
