version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      datagrok:
        aliases:
          - database
    volumes:
      - datagrok_db:/var/lib/postgresql/data
  datagrok:
    image: datagrok/datagrok:1.0.79-93dc7bd
    environment:
      GROK_PARAMETERS: "{\"deployDemo\": false, \"dbServer\": \"database\", \"db\": \"datagrok\", \"dbAdminLogin\": \"postgres\", \"dbAdminPassword\": \"postgres\", \"dbLogin\": \"dg\", \"dbPassword\": \"dg\"}"
    ports:
      - "8080:8080"
    networks:
      datagrok:
        aliases:
          - datagrok
    volumes:
      - datagrok_data:/home/grok/data
      - datagrok_cfg:/home/grok/cfg
  cvm:
    image: datagrok/cvm:1.0.79-93dc7bd
    environment:
      GROK_COMPUTE_NUM_CORES: 4
    ports:
      - "5005:5005"
      - "8081:8080"
      - "54321:54321"
    networks:
      datagrok:
        aliases:
          - cvm
volumes: 
  datagrok_db:
  datagrok_data:
  datagrok_cfg:
networks:
  datagrok: