/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('EDA:Info', {});
  }

  export async function init(): Promise<void> {
    return await grok.functions.call('EDA:Init', {});
  }

  /**
   * Density-based spatial clustering of applications with noise (DBSCAN)
   * @param {number} epsilon - The maximum distance between two samples for them to be considered as in the same neighborhood.
   * @param {number} minPts - The number of samples (or total weight) in a neighborhood for a point to be considered as a core point.
   */
  export async function dbScan(df: DG.DataFrame , xCol: DG.Column , yCol: DG.Column , epsilon: number , minPts: number ): Promise<DG.Column> {
    return await grok.functions.call('EDA:DbScan', { df, xCol, yCol, epsilon, minPts });
  }

  /**
   * Principal component analysis (PCA).
   * @param {number} components - Number of components.
   * @param {boolean} center - Indicating whether the variables should be shifted to be zero centered.
   * @param {boolean} scale - Indicating whether the variables should be scaled to have unit variance.
   */
  export async function pca(table: DG.DataFrame , features: string[] , components: number , center: boolean , scale: boolean ): Promise<void> {
    return await grok.functions.call('EDA:PCA', { table, features, components, center, scale });
  }

  /**
   * @param {number} epsilon - Minimum distance between two points to be considered as in the same neighborhood.
   * @param {number} minimumPoints - Minimum number of points to form a dense region.
   */
  export async function dbscanPostProcessingFunction(col1: DG.Column , col2: DG.Column , epsilon: number , minimumPoints: number ): Promise<void> {
    return await grok.functions.call('EDA:DbscanPostProcessingFunction', { col1, col2, epsilon, minimumPoints });
  }

  export async function numberPreprocessingFunction(col: DG.Column , _metric?: string ): Promise<any> {
    return await grok.functions.call('EDA:NumberPreprocessingFunction', { col, _metric });
  }

  export async function stringPreprocessingFunction(col: DG.Column , _metric?: string ): Promise<any> {
    return await grok.functions.call('EDA:StringPreprocessingFunction', { col, _metric });
  }

  export async function reduceDimensionality(): Promise<void> {
    return await grok.functions.call('EDA:ReduceDimensionality', {});
  }

  export async function getMCLEditor(call: any ): Promise<void> {
    return await grok.functions.call('EDA:GetMCLEditor', { call });
  }

  /**
   * Markov clustering (MCL) is an unsupervised clustering algorithm for graphs based on simulation of stochastic flow.
   * @param {any} metrics - Distance metric per column used to measure similarity between rows.
   * @param {any} weights - Relative weight of each column when combining per-column distances.
   * @param {string} aggregationMethod - How per-column distances are aggregated into a single distance.
   * @param {any} preprocessingFuncs - Preprocessing function applied to each column before distances are computed.
   * @param {any} preprocessingFuncArgs - Arguments passed to the preprocessing functions.
   * @param {number} threshold - Similarity threshold (percentile): edges below it are dropped before clustering.
   * @param {number} maxIterations - Maximum number of expansion/inflation iterations.
   * @param {boolean} useWebGPU - Run the computation on the GPU via WebGPU when available.
   * @param {number} inflate - Inflation factor controlling cluster granularity: higher values yield more, smaller clusters.
   * @param {number} minClusterSize - Clusters smaller than this are merged into noise.
   */
  export async function mclclustering(df: DG.DataFrame , cols: any , metrics: any , weights: any , aggregationMethod: string , preprocessingFuncs: any , preprocessingFuncArgs: any , threshold: number , maxIterations: number , useWebGPU: boolean , inflate: number , minClusterSize: number ): Promise<void> {
    return await grok.functions.call('EDA:MCLClustering', { df, cols, metrics, weights, aggregationMethod, preprocessingFuncs, preprocessingFuncArgs, threshold, maxIterations, useWebGPU, inflate, minClusterSize });
  }

  /**
   * Markov clustering viewer
   */
  export async function markovClusteringViewer(): Promise<any> {
    return await grok.functions.call('EDA:MarkovClusteringViewer', {});
  }

  /**
   * Compute partial least squares (PLS) regression analysis components: prediction, regression coefficients, T- & U-scores, X-loadings.
   * @param {number} components - Number of latent factors the model extracts from the predictors.
   */
  export async function pls(table: DG.DataFrame , features: string[] , predict: DG.Column , components: number , names: DG.Column ): Promise<any> {
    return await grok.functions.call('EDA:PLS', { table, features, predict, components, names });
  }

  /**
   * Compute partial least squares (PLS) regression components. They maximally summarize the variation of the predictors while maximizing correlation with the response variable.
   */
  export async function topMenuPLS(): Promise<void> {
    return await grok.functions.call('EDA:TopMenuPLS', {});
  }

  /**
   * Multidimensional data analysis using partial least squares (PLS) regression.
   */
  export async function mva(): Promise<void> {
    return await grok.functions.call('EDA:MVA', {});
  }

  /**
   * Multidimensional data analysis using partial least squares (PLS) regression. It identifies latent factors and constructs a linear model based on them.
   */
  export async function demoMultivariateAnalysis(): Promise<void> {
    return await grok.functions.call('EDA:DemoMultivariateAnalysis', {});
  }

  /**
   * Two-sample t-test (Welch or Student) compares the means of a feature between two groups.
   */
  export async function tTest(): Promise<void> {
    return await grok.functions.call('EDA:TTest', {});
  }

  /**
   * One-way analysis of variances (ANOVA) determines whether the examined factor has a significant impact on the explored feature.
   */
  export async function anova(): Promise<void> {
    return await grok.functions.call('EDA:Anova', {});
  }

  /**
   * Compare several groups against a single control (Dunnett's test or Holm-corrected Welch's t-tests).
   */
  export async function controlComparisons(): Promise<void> {
    return await grok.functions.call('EDA:ControlComparisons', {});
  }

  /**
   * Missing values imputation using the k-nearest neighbors method (KNN)
   */
  export async function kNNImputation(): Promise<void> {
    return await grok.functions.call('EDA:KNNImputation', {});
  }

  /**
   * Missing values imputation using the k-nearest neighbors method
   */
  export async function kNNImputationForTable(table: DG.DataFrame ): Promise<void> {
    return await grok.functions.call('EDA:KNNImputationForTable', { table });
  }

  /**
   * @param {number} rate - Gradient descent learning rate.
   * @param {number} iterations - Largest number of training steps before training stops.
   * @param {number} alpha - L1 (Lasso) regularization term. 0 means plain ordinary least squares.
   * @param {number} lambda - L2 (Ridge) regularization term. 0 means plain ordinary least squares.
   */
  export async function trainLinearRegression(df: DG.DataFrame , predictColumn: DG.Column , rate: number , iterations: number , alpha: number , lambda: number ): Promise<any> {
    return await grok.functions.call('EDA:TrainLinearRegression', { df, predictColumn, rate, iterations, alpha, lambda });
  }

  /**
   * Predict the target for a table using a trained linear regression model.
   * @param {any} model - Trained linear regression model to apply.
   */
  export async function applyLinearRegression(df: DG.DataFrame , model: any ): Promise<DG.DataFrame> {
    return await grok.functions.call('EDA:ApplyLinearRegression', { df, model });
  }

  export async function isApplicableLinearRegression(df: DG.DataFrame , predictColumn: DG.Column ): Promise<boolean> {
    return await grok.functions.call('EDA:IsApplicableLinearRegression', { df, predictColumn });
  }

  export async function isInteractiveLinearRegression(df: DG.DataFrame , predictColumn: DG.Column ): Promise<boolean> {
    return await grok.functions.call('EDA:IsInteractiveLinearRegression', { df, predictColumn });
  }

  /**
   * @param {number} rate - Gradient descent learning rate.
   * @param {number} iterations - Largest number of training steps before training stops.
   * @param {number} penalty - Regularization rate.
   * @param {number} tolerance - Smallest improvement worth continuing training for.
   */
  export async function trainSoftmax(df: DG.DataFrame , predictColumn: DG.Column , rate: number , iterations: number , penalty: number , tolerance: number ): Promise<any> {
    return await grok.functions.call('EDA:TrainSoftmax', { df, predictColumn, rate, iterations, penalty, tolerance });
  }

  /**
   * Classify the rows of a table using a trained softmax (multinomial logistic regression) model.
   * @param {any} model - Trained softmax classifier model to apply.
   */
  export async function applySoftmax(df: DG.DataFrame , model: any ): Promise<DG.DataFrame> {
    return await grok.functions.call('EDA:ApplySoftmax', { df, model });
  }

  export async function isApplicableSoftmax(df: DG.DataFrame , predictColumn: DG.Column ): Promise<boolean> {
    return await grok.functions.call('EDA:IsApplicableSoftmax', { df, predictColumn });
  }

  export async function isInteractiveSoftmax(df: DG.DataFrame , predictColumn: DG.Column ): Promise<boolean> {
    return await grok.functions.call('EDA:IsInteractiveSoftmax', { df, predictColumn });
  }

  /**
   * @param {number} components - Number of latent components.
   */
  export async function trainPLSRegression(df: DG.DataFrame , predictColumn: DG.Column , components: number ): Promise<any> {
    return await grok.functions.call('EDA:TrainPLSRegression', { df, predictColumn, components });
  }

  /**
   * Predict the target for a table using a trained partial least squares (PLS) regression model.
   * @param {any} model - Trained PLS regression model to apply.
   */
  export async function applyPLSRegression(df: DG.DataFrame , model: any ): Promise<DG.DataFrame> {
    return await grok.functions.call('EDA:ApplyPLSRegression', { df, model });
  }

  export async function isApplicablePLSRegression(df: DG.DataFrame , predictColumn: DG.Column ): Promise<boolean> {
    return await grok.functions.call('EDA:IsApplicablePLSRegression', { df, predictColumn });
  }

  export async function visualizePLSRegression(df: DG.DataFrame , targetColumn: DG.Column , predictColumn: DG.Column , model: any ): Promise<any> {
    return await grok.functions.call('EDA:VisualizePLSRegression', { df, targetColumn, predictColumn, model });
  }

  export async function isInteractivePLSRegression(df: DG.DataFrame , predictColumn: DG.Column ): Promise<boolean> {
    return await grok.functions.call('EDA:IsInteractivePLSRegression', { df, predictColumn });
  }

  /**
   * @param {number} iterations - Number of training iterations.
   * @param {number} eta - Learning rate.
   * @param {number} maxDepth - Maximum depth of a tree.
   * @param {number} lambda - L2 regularization term.
   * @param {number} alpha - L1 regularization term.
   */
  export async function trainXGBooster(df: DG.DataFrame , predictColumn: DG.Column , iterations: number , eta: number , maxDepth: number , lambda: number , alpha: number ): Promise<any> {
    return await grok.functions.call('EDA:TrainXGBooster', { df, predictColumn, iterations, eta, maxDepth, lambda, alpha });
  }

  /**
   * Predict the target for a table using a trained XGBoost gradient-boosting model.
   * @param {any} model - Trained XGBoost model to apply.
   */
  export async function applyXGBooster(df: DG.DataFrame , model: any ): Promise<DG.DataFrame> {
    return await grok.functions.call('EDA:ApplyXGBooster', { df, model });
  }

  export async function isInteractiveXGBooster(df: DG.DataFrame , predictColumn: DG.Column ): Promise<boolean> {
    return await grok.functions.call('EDA:IsInteractiveXGBooster', { df, predictColumn });
  }

  export async function isApplicableXGBooster(df: DG.DataFrame , predictColumn: DG.Column ): Promise<boolean> {
    return await grok.functions.call('EDA:IsApplicableXGBooster', { df, predictColumn });
  }

  /**
   * Perform optimization across multiple objectives: analyze trade-offs between conflicting objectives and identify Pareto-optimal points.
   */
  export async function paretoFront(): Promise<void> {
    return await grok.functions.call('EDA:ParetoFront', {});
  }

  /**
   * Pareto front viewer
   */
  export async function paretoFrontViewer(): Promise<any> {
    return await grok.functions.call('EDA:ParetoFrontViewer', {});
  }

  /**
   * Train probabilistic multi-parameter optimization (pMPO) model
   */
  export async function trainPmpo(): Promise<void> {
    return await grok.functions.call('EDA:TrainPmpo', {});
  }

  export async function getPmpoAppItems(view: DG.View ): Promise<any> {
    return await grok.functions.call('EDA:GetPmpoAppItems', { view });
  }

  /**
   * Generate a synthetic dataset oriented on probabilistic multi-parameter optimization (pMPO) modeling.
   * @param {number} samples - Number of rows (samples) to generate.
   */
  export async function generatePmpoDataset(samples: number ): Promise<DG.DataFrame> {
    return await grok.functions.call('EDA:GeneratePmpoDataset', { samples });
  }
}
