export enum WORKER_CALL {
  INIT_MOLECULES_STRUCTURES = 'initRdKitMolecules',
  FREE_MOLECULES_STRUCTURES = 'freeRdKitMolecules',
  GET_FINGERPRINTS = 'getFingerprints',
  SEARCH_SUBSTRUCTURE = 'searchSubstructure',
  CONVERT_MOL_NOTATION = 'convertMolNotation',
  GET_STRUCTURAL_ALERTS = 'getStructuralAlerts',
  INVALIDATE_CACHE = 'invalidateCache',
  SET_TERMINATE_FLAG = 'setTerminateFlag',
  MMP_GET_FRAGMENTS = 'mmpGetFragments',
  MMP_LINK_FRAGMENTS = 'mmpLinkFragments',
  MMP_GET_MCS = 'mmpGetMcs',
  MOST_COMMON_STRUCTURE = 'mostCommonStructure',
  R_GROUP_ANALYSIS = 'rGroupAnalysis',
  BEAUTIFY_MOLS = 'beautifyMols',
}
