/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function init(): Promise<void> {
    return await grok.functions.call('ChatGPT:Init', {});
  }

  export async function autostart(): Promise<void> {
    return await grok.functions.call('ChatGPT:Autostart', {});
  }

  export async function combinedLLMSearchProvider(): Promise<any> {
    return await grok.functions.call('ChatGPT:CombinedLLMSearchProvider', {});
  }

  /**
  Get answers from DeepGROK AI assistant based on Datagrok documentation and public code.
  */
  export async function askHelpLLMProvider(prompt: string ): Promise<any> {
    return await grok.functions.call('ChatGPT:AskHelpLLMProvider', { prompt });
  }

  /**
  Plans and executes function steps to achieve needed results
  */
  export async function smartChainExecutionProvider(prompt: string ): Promise<any> {
    return await grok.functions.call('ChatGPT:SmartChainExecutionProvider', { prompt });
  }

  /**
  Tries to find a query which has the similar pattern as the prompt user entered and executes it
  */
  export async function llmSearchQueryProvider(prompt: string ): Promise<any> {
    return await grok.functions.call('ChatGPT:LlmSearchQueryProvider', { prompt });
  }

  export async function askAIGeneralCached(model: string , systemPrompt: string , prompt: string , schema: any ): Promise<string> {
    return await grok.functions.call('ChatGPT:AskAIGeneralCached', { model, systemPrompt, prompt, schema });
  }

  export async function getExecutionPlan(userGoal: string ): Promise<string> {
    return await grok.functions.call('ChatGPT:GetExecutionPlan', { userGoal });
  }

  export async function fuzzyMatch(prompt: string , searchPatterns: any , descriptions: any ): Promise<string> {
    return await grok.functions.call('ChatGPT:FuzzyMatch', { prompt, searchPatterns, descriptions });
  }

  export async function askDocumentationCached(prompt: string ): Promise<string> {
    return await grok.functions.call('ChatGPT:AskDocumentationCached', { prompt });
  }
}
