/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function a(): Promise<void> {
    return await grok.functions.call('ChatGPT:A', {});
  }

  export async function init(): Promise<void> {
    return await grok.functions.call('ChatGPT:Init', {});
  }

  export async function autostart(): Promise<void> {
    return await grok.functions.call('ChatGPT:Autostart', {});
  }

  export async function ask(question: string ): Promise<string> {
    return await grok.functions.call('ChatGPT:Ask', { question });
  }

  export async function askFun(question: string ): Promise<string> {
    return await grok.functions.call('ChatGPT:AskFun', { question });
  }
}
