/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('Inventory:Info', {});
  }

  /**
  Inventory over entity-mapped domain schemas — batch upsert by SKU, optimistic stock adjustments, per-department column security
  */
  export async function inventoryApp(): Promise<DG.View> {
    return await grok.functions.call('Inventory:InventoryApp', {});
  }

  /**
  Column-security demo setup - verifies the department property schemas are registered and creates the Chemists and Procurement groups (see README for the grant step)
  */
  export async function setupInventoryDemo(): Promise<string> {
    return await grok.functions.call('Inventory:SetupInventoryDemo', {});
  }
}
