/**
 * Shared HELM fixtures for the OligoNucleotide renderer test suites
 * (`oligo-renderer-tests.ts` + `oligo-alignment-tests.ts`).
 *
 * HELMCore canonical: lowercase backbone (`r`, `m`, `d`, `lna`, `fl2r`, `p`, `sp`).
 * Single-char sugars/phosphates are unbracketed; multi-char must be bracketed.
 *
 * The explicit-pair / complex fixtures are generated by
 * `prototypes/gen-complex-test-helms.mjs` (so the `$connections$` sections are
 * exact); their expected values are probed via `prototypes/probe-complex.mjs`.
 */

// A blunt, fully reverse-complementary 19/19 duplex (so the auto-aligner keeps
// it blunt, shift 0). The antisense keeps a representative fl2r/m/r modification
// skeleton; only the base letters are the reverse-complement of the sense.
export const SAMPLE_DUPLEX =
  'RNA1{m(G)[sp].m(A)[sp].[fl2r](C)p.[fl2r](U)p.r(G)p.r(A)p.r(A)p.r(U)p.r(A)p.r(U)p.r(A)p.r(A)p.r(A)p.' +
  'r(C)p.r(U)p.r(U)p.m(G)p.m(U)[sp].m(G)[sp].[L3]}|' +
  'RNA2{[fl2r](C)[sp].m(A)[sp].m(C)p.m(A)p.r(A)p.r(G)p.r(U)p.r(U)p.r(U)p.r(A)p.r(U)p.r(A)p.r(U)p.' +
  'r(U)p.r(C)p.m(A)p.m(G)[sp].m(U)[sp].r(C)}$$$$';

export const SAMPLE_SS = 'RNA1{[lna](C)[sp].[lna](A)[sp].[lna](G)[sp].d(T)[sp].d(C)[sp].d(A)[sp]}$$$$';

// Legacy / Pistoia-style symbols that should still render via the alias map.
export const LEGACY_DUPLEX =
  'RNA1{[mR](G)[sP].[mR](A)[sP].[fR](C)P.R(U)P}|RNA2{[mR](C)[sP].R(A)P.R(U)P.R(G)P}$$$$';

// User-reference HELM: blunt 19/19, explicit `pair` connections + strandtype.
// (RNA2 carries a leading 5' phosphate, so its base positions are offset by 1.)
export const EXPLICIT_BLUNT =
  'RNA1{m(G)[sp].m([cl8A])[sp].m(C)p.m(U)p.m(G)p.m(A)p.m(A)p.m(U)p.m(A)p.m(U)p.m(A)p.m(A)p.m(A)p.m(C)p.m(U)p.' +
  'm(U)p.m(G)[sp].m(U)[sp].m(G)[L3]}|RNA2{p.r(C)p.r(A)p.r(C)p.r(A)p.r(A)p.r(G)p.r(T)p.r(T)p.r(T)p.r(A)p.r(T)p.' +
  'r(A)p.r(T)p.r(T)p.r(C)p.r(A)p.r(G)p.r(T)p.r(C)}$' +
  'RNA1,RNA2,2:pair-57:pair|RNA1,RNA2,5:pair-54:pair|RNA1,RNA2,8:pair-51:pair|RNA1,RNA2,11:pair-48:pair|' +
  'RNA1,RNA2,14:pair-45:pair|RNA1,RNA2,17:pair-42:pair|RNA1,RNA2,20:pair-39:pair|RNA1,RNA2,23:pair-36:pair|' +
  'RNA1,RNA2,26:pair-33:pair|RNA1,RNA2,29:pair-30:pair|RNA1,RNA2,32:pair-27:pair|RNA1,RNA2,35:pair-24:pair|' +
  'RNA1,RNA2,38:pair-21:pair|RNA1,RNA2,41:pair-18:pair|RNA1,RNA2,44:pair-15:pair|RNA1,RNA2,47:pair-12:pair|' +
  'RNA1,RNA2,50:pair-9:pair|RNA1,RNA2,53:pair-6:pair|RNA1,RNA2,56:pair-3:pair$${"RNA1":{"strandtype":"ss"}}$V2.0';

// Explicit pairs encoding a 2-column shift (6/6 strands, pairs senseIdx+antiIdx=3 → shift −2).
export const EXPLICIT_OVERHANG =
  'RNA1{m(A)p.m(C)p.m(G)p.m(U)p.m(A)p.m(C)}|RNA2{m(G)p.m(U)p.m(A)p.m(C)p.m(G)p.m(U)}$' +
  'RNA1,RNA2,2:pair-11:pair|RNA1,RNA2,5:pair-8:pair|RNA1,RNA2,8:pair-5:pair|RNA1,RNA2,11:pair-2:pair$$$V2.0';

// Blunt-complementary bases (would auto-align to shift 0) BUT explicit pairs say
// shift −1 — proves explicit info wins over the auto-aligner.
export const EXPLICIT_OVERRIDE =
  'RNA1{m(A)p.m(C)p.m(G)p.m(U)p.m(A)p.m(C)}|RNA2{m(G)p.m(U)p.m(A)p.m(C)p.m(G)p.m(U)}$' +
  'RNA1,RNA2,2:pair-14:pair|RNA1,RNA2,5:pair-11:pair|RNA1,RNA2,8:pair-8:pair|' +
  'RNA1,RNA2,11:pair-5:pair|RNA1,RNA2,14:pair-2:pair$$$V2.0';

// Strand-type annotation names RNA2 as the sense strand (document order is
// antisense-first) → the parser must swap so `sense` is the real sense.
export const SWAPPED =
  'RNA1{m(A)p.m(U)p.m(G)p.m(C)}|RNA2{m(G)p.m(C)p.m(A)p.m(U)}$$$' +
  '{"RNA1":{"strandtype":"as"},"RNA2":{"strandtype":"ss"}}$V2.0';

// 8/8 nt duplex with 2-nt dTdT 3' overhangs, complementary 6-bp core, no explicit
// info → auto-aligner should find shift −2 (symmetric 3' overhangs).
export const OVERHANG_AUTO =
  'RNA1{m(A)p.m(C)p.m(G)p.m(U)p.m(A)p.m(C)p.d(T)p.d(T)}|' +
  'RNA2{m(G)p.m(U)p.m(A)p.m(C)p.m(G)p.m(U)p.d(T)p.d(T)}$$$$';

/* ---- complex, realistic HELMs (see prototypes/gen-complex-test-helms.mjs) ---- */

// GalNAc/Chol both-end conjugates, 2'-OMe/2'-F alternating, 2-nt dTdT 3' overhangs, explicit shift −2.
export const COMPLEX_GALNAC_OH =
  'RNA1{[Chol].m(G)[sp].[fl2r](A)p.m(C)p.[fl2r](U)p.m(G)p.[fl2r](A)p.m(A)p.[fl2r](U)p.m(A)p.[fl2r](U)p.m(A)p.' +
  '[fl2r](A)p.m(A)p.[fl2r](C)p.m(U)p.[fl2r](U)p.m(G)p.[fl2r](U)p.m(G)p.d(T)[sp].d(T)[sp].[GalNAc]}|' +
  'RNA2{m(C)[sp].m(A)[sp].m(C)p.m(A)p.m(A)p.m(G)p.m(U)p.m(U)p.m(U)p.m(A)p.m(U)p.m(A)p.m(U)p.m(U)p.m(C)p.m(A)p.' +
  'm(G)p.m(U)p.m(C)[sp].d(T)[sp].d(T)}$' +
  'RNA1,RNA2,3:pair-56:pair|RNA1,RNA2,6:pair-53:pair|RNA1,RNA2,9:pair-50:pair|RNA1,RNA2,12:pair-47:pair|' +
  'RNA1,RNA2,15:pair-44:pair|RNA1,RNA2,18:pair-41:pair|RNA1,RNA2,21:pair-38:pair|RNA1,RNA2,24:pair-35:pair|' +
  'RNA1,RNA2,27:pair-32:pair|RNA1,RNA2,30:pair-29:pair|RNA1,RNA2,33:pair-26:pair|RNA1,RNA2,36:pair-23:pair|' +
  'RNA1,RNA2,39:pair-20:pair|RNA1,RNA2,42:pair-17:pair|RNA1,RNA2,45:pair-14:pair|RNA1,RNA2,48:pair-11:pair|' +
  'RNA1,RNA2,51:pair-8:pair|RNA1,RNA2,54:pair-5:pair|RNA1,RNA2,57:pair-2:pair$$' +
  '{"RNA1":{"strandtype":"ss"},"RNA2":{"strandtype":"as"}}$V2.0';

// 5' sense overhang → positive shift +2 (explicit pairs).
export const COMPLEX_POS_SHIFT =
  'RNA1{d(T)[sp].d(T)[sp].m(G)p.m(A)p.m(C)p.m(U)p.m(G)p.m(A)p.m(A)p.m(U)p.m(A)p.m(U)p.m(A)p.m(A)p.m(A)p.m(C)p.' +
  'm(U)p.m(U)p.m(G)[sp].m(U)[sp].m(G)}|' +
  'RNA2{m(C)[sp].m(A)[sp].m(C)p.m(A)p.m(A)p.m(G)p.m(U)p.m(U)p.m(U)p.m(A)p.m(U)p.m(A)p.m(U)p.m(U)p.m(C)p.m(A)p.' +
  'm(G)[sp].m(U)[sp].m(C)}$' +
  'RNA1,RNA2,8:pair-56:pair|RNA1,RNA2,11:pair-53:pair|RNA1,RNA2,14:pair-50:pair|RNA1,RNA2,17:pair-47:pair|' +
  'RNA1,RNA2,20:pair-44:pair|RNA1,RNA2,23:pair-41:pair|RNA1,RNA2,26:pair-38:pair|RNA1,RNA2,29:pair-35:pair|' +
  'RNA1,RNA2,32:pair-32:pair|RNA1,RNA2,35:pair-29:pair|RNA1,RNA2,38:pair-26:pair|RNA1,RNA2,41:pair-23:pair|' +
  'RNA1,RNA2,44:pair-20:pair|RNA1,RNA2,47:pair-17:pair|RNA1,RNA2,50:pair-14:pair|RNA1,RNA2,53:pair-11:pair|' +
  'RNA1,RNA2,56:pair-8:pair|RNA1,RNA2,59:pair-5:pair|RNA1,RNA2,62:pair-2:pair$${"RNA1":{"strandtype":"ss"}}$V2.0';

// sense 23 / antisense 19, sense overhangs on BOTH ends (shift +2), explicit pairs.
export const COMPLEX_DIFFLEN =
  'RNA1{d(T)[sp].d(T)[sp].m(G)p.m(A)p.m(C)p.m(U)p.m(G)p.m(A)p.m(A)p.m(U)p.m(A)p.m(U)p.m(A)p.m(A)p.m(A)p.m(C)p.' +
  'm(U)p.m(U)p.m(G)p.m(U)p.m(G)[sp].d(T)[sp].d(T)}|' +
  'RNA2{m(C)[sp].m(A)[sp].m(C)p.m(A)p.m(A)p.m(G)p.m(U)p.m(U)p.m(U)p.m(A)p.m(U)p.m(A)p.m(U)p.m(U)p.m(C)p.m(A)p.' +
  'm(G)[sp].m(U)[sp].m(C)}$' +
  'RNA1,RNA2,8:pair-56:pair|RNA1,RNA2,11:pair-53:pair|RNA1,RNA2,14:pair-50:pair|RNA1,RNA2,17:pair-47:pair|' +
  'RNA1,RNA2,20:pair-44:pair|RNA1,RNA2,23:pair-41:pair|RNA1,RNA2,26:pair-38:pair|RNA1,RNA2,29:pair-35:pair|' +
  'RNA1,RNA2,32:pair-32:pair|RNA1,RNA2,35:pair-29:pair|RNA1,RNA2,38:pair-26:pair|RNA1,RNA2,41:pair-23:pair|' +
  'RNA1,RNA2,44:pair-20:pair|RNA1,RNA2,47:pair-17:pair|RNA1,RNA2,50:pair-14:pair|RNA1,RNA2,53:pair-11:pair|' +
  'RNA1,RNA2,56:pair-8:pair|RNA1,RNA2,59:pair-5:pair|RNA1,RNA2,62:pair-2:pair$$$V2.0';

// 25-mer with mixed sugars (m/fl2r/lna/moe), fully reverse-complementary → auto blunt (shift 0).
export const COMPLEX_AUTO_LONG =
  'RNA1{m(G)[sp].[fl2r](A)[sp].[lna](C)p.[moe](U)p.m(G)p.[fl2r](A)p.[lna](A)p.[moe](U)p.m(A)p.[fl2r](U)p.' +
  '[lna](A)p.[moe](A)p.m(A)p.[fl2r](C)p.[lna](U)p.[moe](U)p.m(G)p.[fl2r](U)p.[lna](G)p.[moe](C)p.m(A)p.' +
  '[fl2r](C)p.[lna](A)[sp].[moe](A)[sp].m(G)}|' +
  'RNA2{m(C)[sp].[fl2r](U)[sp].[lna](U)p.[moe](G)p.m(U)p.[fl2r](G)p.[lna](C)p.[moe](A)p.m(C)p.[fl2r](A)p.' +
  '[lna](A)p.[moe](G)p.m(U)p.[fl2r](U)p.[lna](U)p.[moe](A)p.m(U)p.[fl2r](A)p.[lna](U)p.[moe](U)p.m(C)p.' +
  '[fl2r](A)p.[lna](G)[sp].[moe](U)[sp].m(C)}$$$$';

// 4-nt 3' overhangs (canonical bases), no explicit info → auto shift −4.
export const COMPLEX_AUTO_4OH =
  'RNA1{m(G)[sp].m(A)[sp].m(C)p.m(U)p.m(G)p.m(A)p.m(A)p.m(U)p.m(A)p.m(U)p.m(A)p.m(A)p.m(A)p.m(C)p.m(U)p.m(U)p.' +
  'm(G)p.m(U)p.m(G)p.d(T)p.d(T)[sp].d(T)[sp].d(T)}|' +
  'RNA2{m(C)[sp].m(A)[sp].m(C)p.m(A)p.m(A)p.m(G)p.m(U)p.m(U)p.m(U)p.m(A)p.m(U)p.m(A)p.m(U)p.m(U)p.m(C)p.m(A)p.' +
  'm(G)p.m(U)p.m(C)p.d(T)p.d(T)[sp].d(T)[sp].d(T)}$$$$';

// Custom modified bases (5meC) in the duplex with explicit blunt pairs (shift independent of analogs).
export const COMPLEX_CUSTOM_EXPLICIT =
  'RNA1{[fl2r]([5meC])[sp].[fl2r](A)[sp].[fl2r](G)p.[fl2r](U)[sp].[fl2r]([5meC])[sp].[fl2r](A)}|' +
  'RNA2{m(U)[sp].m(G)[sp].m(A)p.m(C)[sp].m(U)[sp].m(G)}$' +
  'RNA1,RNA2,2:pair-17:pair|RNA1,RNA2,5:pair-14:pair|RNA1,RNA2,8:pair-11:pair|' +
  'RNA1,RNA2,11:pair-8:pair|RNA1,RNA2,14:pair-5:pair|RNA1,RNA2,17:pair-2:pair$$$V2.0';

// Single strand with standalone backbone linkers: a 3-phosphate 5' cap
// (`p.p.p`) and three consecutive mid-strand `[sp]` linkers. 19 nucleotides,
// 6 standalone linkers. (The user's reference HELM.) Linkers render as arcs.
export const LINKER_SS =
  'RNA1{p.p.p.r(C)p.r(A)p.r(C)p.r(A)p.r(A)p.r(G)p.r(T)p.r(T)p.r(T)p.[sp].[sp].[sp].' +
  'r(A)p.r(T)p.r(A)p.r(T)p.r(T)p.r(C)p.r(A)p.r(G)p.r(T)p.r(C)}$$$$';

// Blunt 19/19 duplex where the SENSE strand has two consecutive standalone `[sp]`
// linkers mid-strand (after base 9) that the antisense lacks → bases stay aligned,
// the gap widens, and the antisense draws a single wider arc across it.
export const LINKER_BULGE =
  'RNA1{m(G)p.m(A)p.m(C)p.m(U)p.m(G)p.m(A)p.m(A)p.m(U)p.m(A)p.m(U)p.[sp].[sp].' +
  'm(A)p.m(A)p.m(A)p.m(C)p.m(U)p.m(U)p.m(G)p.m(U)p.m(G)}|' +
  'RNA2{m(C)p.m(A)p.m(C)p.m(A)p.m(A)p.m(G)p.m(U)p.m(U)p.m(U)p.m(A)p.m(U)p.m(A)p.m(U)p.' +
  'm(U)p.m(C)p.m(A)p.m(G)p.m(U)p.m(C)}$$$$';

// Strand swap: RNA1 is the antisense, RNA2 (GalNAc-conjugated) is the sense, per annotation.
export const COMPLEX_SWAP_CONJ =
  'RNA1{m(C)[sp].m(A)[sp].m(C)p.m(A)p.m(A)p.m(G)p.m(U)p.m(U)p.m(U)p.m(A)p.m(U)p.m(A)p.m(U)p.m(U)p.m(C)p.m(A)p.' +
  'm(G)[sp].m(U)[sp].m(C)}|' +
  'RNA2{m(G)[sp].m(A)[sp].m(C)p.m(U)p.m(G)p.m(A)p.m(A)p.m(U)p.m(A)p.m(U)p.m(A)p.m(A)p.m(A)p.m(C)p.m(U)p.m(U)p.' +
  'm(G)p.m(U)[sp].m(G)[sp].[GalNAc]}$' +
  'RNA2,RNA1,2:pair-56:pair|RNA2,RNA1,5:pair-53:pair|RNA2,RNA1,8:pair-50:pair|RNA2,RNA1,11:pair-47:pair|' +
  'RNA2,RNA1,14:pair-44:pair|RNA2,RNA1,17:pair-41:pair|RNA2,RNA1,20:pair-38:pair|RNA2,RNA1,23:pair-35:pair|' +
  'RNA2,RNA1,26:pair-32:pair|RNA2,RNA1,29:pair-29:pair|RNA2,RNA1,32:pair-26:pair|RNA2,RNA1,35:pair-23:pair|' +
  'RNA2,RNA1,38:pair-20:pair|RNA2,RNA1,41:pair-17:pair|RNA2,RNA1,44:pair-14:pair|RNA2,RNA1,47:pair-11:pair|' +
  'RNA2,RNA1,50:pair-8:pair|RNA2,RNA1,53:pair-5:pair|RNA2,RNA1,56:pair-2:pair$$' +
  '{"RNA1":{"strandtype":"as"},"RNA2":{"strandtype":"ss"}}$V2.0';
