/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('Grit:Info', {});
  }

  export async function initGrit(): Promise<void> {
    return await grok.functions.call('Grit:InitGrit', {});
  }

  /**
   * Custom rendering for grit.issue domain rows (status/priority badges)
   */
  export async function gritIssueHandler(): Promise<any> {
    return await grok.functions.call('Grit:GritIssueHandler', {});
  }

  /**
   * Issue tracker over entity-mapped domain schemas — the platform's Domain View with the filter panel
   */
  export async function issuesApp(path?: string ): Promise<DG.View> {
    return await grok.functions.call('Grit:IssuesApp', { path });
  }

  export async function issuesTreeBrowser(treeNode: any ): Promise<void> {
    return await grok.functions.call('Grit:IssuesTreeBrowser', { treeNode });
  }
}
