/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('Grit:Info', {});
  }

  export async function initGrit(): Promise<void> {
    return await grok.functions.call('Grit:InitGrit', {});
  }

  /**
  Custom rendering for grit.issue domain rows (status/priority badges, timeline)
  */
  export async function gritIssueHandler(): Promise<any> {
    return await grok.functions.call('Grit:GritIssueHandler', {});
  }

  /**
  GRok Issue Tracker — projects, issues, comments over entity-mapped domain schemas
  */
  export async function gritApp(): Promise<DG.View> {
    return await grok.functions.call('Grit:GritApp', {});
  }
}
