/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  /**
   * Predictive modeling: engines and the model catalog
   */
  export async function forgeApp(): Promise<DG.View> {
    return await grok.functions.call('Forge:ForgeApp', {});
  }

  /**
   * Opens the Forge app
   */
  export async function forgeModels(): Promise<void> {
    return await grok.functions.call('Forge:ForgeModels', {});
  }
}
