-- GHS hazard statements (UNECE GHS Rev.10, Annex 3, table A3.1.1): the current single-code
-- vocabulary with the hazard class each belongs to and the pictogram it carries (NULL where the
-- category carries none). Statements withdrawn by Rev.8 (H200-H203, H205) and the EU CLP
-- sub-variants (H350i, H360D/F..., H361d/f...) are not part of the UNECE set and are left out.

INSERT INTO stockroom.h_statement (id, code, text, hazard_class_id, pictogram)
SELECT md5('stockroom.h_statement:' || v.code)::uuid, v.code, v.text,
       md5('stockroom.hazard_class:' || v.class)::uuid, v.pictogram
FROM (VALUES
  -- Physical hazards
  ('H204', 'Fire or projection hazard.', '2.1', 'GHS01'),
  ('H206', 'Fire, blast or projection hazard; increased risk of explosion if desensitizing agent is reduced.', '2.17', 'GHS02'),
  ('H207', 'Fire or projection hazard; increased risk of explosion if desensitizing agent is reduced.', '2.17', 'GHS02'),
  ('H208', 'Fire hazard; increased risk of explosion if desensitizing agent is reduced.', '2.17', 'GHS02'),
  ('H209', 'Explosive.', '2.1', 'GHS01'),
  ('H210', 'Very sensitive.', '2.1', 'GHS01'),
  ('H211', 'May be sensitive.', '2.1', 'GHS01'),
  ('H220', 'Extremely flammable gas.', '2.2', 'GHS02'),
  ('H221', 'Flammable gas.', '2.2', NULL),
  ('H222', 'Extremely flammable aerosol.', '2.3', 'GHS02'),
  ('H223', 'Flammable aerosol.', '2.3', 'GHS02'),
  ('H224', 'Extremely flammable liquid and vapour.', '2.6', 'GHS02'),
  ('H225', 'Highly flammable liquid and vapour.', '2.6', 'GHS02'),
  ('H226', 'Flammable liquid and vapour.', '2.6', 'GHS02'),
  ('H227', 'Combustible liquid.', '2.6', NULL),
  ('H228', 'Flammable solid.', '2.7', 'GHS02'),
  ('H229', 'Pressurized container: may burst if heated.', '2.3', NULL),
  ('H230', 'May react explosively even in the absence of air.', '2.2', 'GHS02'),
  ('H231', 'May react explosively even in the absence of air at elevated pressure and/or temperature.', '2.2', 'GHS02'),
  ('H232', 'May ignite spontaneously if exposed to air.', '2.2', 'GHS02'),
  ('H240', 'Heating may cause an explosion.', '2.8', 'GHS01'),
  ('H241', 'Heating may cause a fire or explosion.', '2.8', 'GHS01'),
  ('H242', 'Heating may cause a fire.', '2.8', 'GHS02'),
  ('H250', 'Catches fire spontaneously if exposed to air.', '2.9', 'GHS02'),
  ('H251', 'Self-heating; may catch fire.', '2.11', 'GHS02'),
  ('H252', 'Self-heating in large quantities; may catch fire.', '2.11', 'GHS02'),
  ('H260', 'In contact with water releases flammable gases which may ignite spontaneously.', '2.12', 'GHS02'),
  ('H261', 'In contact with water releases flammable gas.', '2.12', 'GHS02'),
  ('H270', 'May cause or intensify fire; oxidizer.', '2.4', 'GHS03'),
  ('H271', 'May cause fire or explosion; strong oxidizer.', '2.13', 'GHS03'),
  ('H272', 'May intensify fire; oxidizer.', '2.13', 'GHS03'),
  ('H280', 'Contains gas under pressure; may explode if heated.', '2.5', 'GHS04'),
  ('H281', 'Contains refrigerated gas; may cause cryogenic burns or injury.', '2.5', 'GHS04'),
  ('H282', 'Extremely flammable chemical under pressure: may explode if heated.', '2.3', 'GHS02'),
  ('H283', 'Flammable chemical under pressure: may explode if heated.', '2.3', 'GHS02'),
  ('H284', 'Chemical under pressure: may explode if heated.', '2.3', 'GHS04'),
  ('H290', 'May be corrosive to metals.', '2.16', 'GHS05'),
  -- Health hazards
  ('H300', 'Fatal if swallowed.', '3.1', 'GHS06'),
  ('H301', 'Toxic if swallowed.', '3.1', 'GHS06'),
  ('H302', 'Harmful if swallowed.', '3.1', 'GHS07'),
  ('H303', 'May be harmful if swallowed.', '3.1', NULL),
  ('H304', 'May be fatal if swallowed and enters airways.', '3.10', 'GHS08'),
  ('H305', 'May be harmful if swallowed and enters airways.', '3.10', NULL),
  ('H310', 'Fatal in contact with skin.', '3.1', 'GHS06'),
  ('H311', 'Toxic in contact with skin.', '3.1', 'GHS06'),
  ('H312', 'Harmful in contact with skin.', '3.1', 'GHS07'),
  ('H313', 'May be harmful in contact with skin.', '3.1', NULL),
  ('H314', 'Causes severe skin burns and eye damage.', '3.2', 'GHS05'),
  ('H315', 'Causes skin irritation.', '3.2', 'GHS07'),
  ('H316', 'Causes mild skin irritation.', '3.2', NULL),
  ('H317', 'May cause an allergic skin reaction.', '3.4', 'GHS07'),
  ('H318', 'Causes serious eye damage.', '3.3', 'GHS05'),
  ('H319', 'Causes serious eye irritation.', '3.3', 'GHS07'),
  ('H320', 'Causes eye irritation.', '3.3', NULL),
  ('H330', 'Fatal if inhaled.', '3.1', 'GHS06'),
  ('H331', 'Toxic if inhaled.', '3.1', 'GHS06'),
  ('H332', 'Harmful if inhaled.', '3.1', 'GHS07'),
  ('H333', 'May be harmful if inhaled.', '3.1', NULL),
  ('H334', 'May cause allergy or asthma symptoms or breathing difficulties if inhaled.', '3.4', 'GHS08'),
  ('H335', 'May cause respiratory irritation.', '3.8', 'GHS07'),
  ('H336', 'May cause drowsiness or dizziness.', '3.8', 'GHS07'),
  ('H340', 'May cause genetic defects.', '3.5', 'GHS08'),
  ('H341', 'Suspected of causing genetic defects.', '3.5', 'GHS08'),
  ('H350', 'May cause cancer.', '3.6', 'GHS08'),
  ('H351', 'Suspected of causing cancer.', '3.6', 'GHS08'),
  ('H360', 'May damage fertility or the unborn child.', '3.7', 'GHS08'),
  ('H361', 'Suspected of damaging fertility or the unborn child.', '3.7', 'GHS08'),
  ('H362', 'May cause harm to breast-fed children.', '3.7', NULL),
  ('H370', 'Causes damage to organs.', '3.8', 'GHS08'),
  ('H371', 'May cause damage to organs.', '3.8', 'GHS08'),
  ('H372', 'Causes damage to organs through prolonged or repeated exposure.', '3.9', 'GHS08'),
  ('H373', 'May cause damage to organs through prolonged or repeated exposure.', '3.9', 'GHS08'),
  -- Environmental hazards
  ('H400', 'Very toxic to aquatic life.', '4.1', 'GHS09'),
  ('H401', 'Toxic to aquatic life.', '4.1', NULL),
  ('H402', 'Harmful to aquatic life.', '4.1', NULL),
  ('H410', 'Very toxic to aquatic life with long lasting effects.', '4.1', 'GHS09'),
  ('H411', 'Toxic to aquatic life with long lasting effects.', '4.1', 'GHS09'),
  ('H412', 'Harmful to aquatic life with long lasting effects.', '4.1', NULL),
  ('H413', 'May cause long lasting harmful effects to aquatic life.', '4.1', NULL),
  ('H420', 'Harms public health and the environment by destroying ozone in the upper atmosphere.', '4.2', 'GHS07')
) AS v (code, text, class, pictogram)
ON CONFLICT (id) DO NOTHING;
