-- GHS precautionary statements (UNECE GHS Rev.10, Annex 3, section 3): the current single-code
-- vocabulary by kind. Combined statements (P303+P361+P353 ...) are label compositions, not
-- vocabulary, and are left out; the bracketed parts are the manufacturer's blanks, kept as printed.

INSERT INTO stockroom.p_statement (id, code, text, kind)
SELECT md5('stockroom.p_statement:' || v.code)::uuid, v.code, v.text, v.kind
FROM (VALUES
  -- General
  ('P101', 'If medical advice is needed, have product container or label at hand.', 'general'),
  ('P102', 'Keep out of reach of children.', 'general'),
  ('P103', 'Read carefully and follow all instructions.', 'general'),
  -- Prevention
  ('P203', 'Obtain, read and follow all safety instructions before use.', 'prevention'),
  ('P210', 'Keep away from heat, hot surfaces, sparks, open flames and other ignition sources. No smoking.', 'prevention'),
  ('P211', 'Do not spray on an open flame or other ignition source.', 'prevention'),
  ('P212', 'Avoid heating under confinement or reduction of the desensitized agent.', 'prevention'),
  ('P222', 'Do not allow contact with air.', 'prevention'),
  ('P223', 'Do not allow contact with water.', 'prevention'),
  ('P230', 'Keep wetted with ...', 'prevention'),
  ('P232', 'Protect from moisture.', 'prevention'),
  ('P233', 'Keep container tightly closed.', 'prevention'),
  ('P234', 'Keep only in original packaging.', 'prevention'),
  ('P235', 'Keep cool.', 'prevention'),
  ('P240', 'Ground and bond container and receiving equipment.', 'prevention'),
  ('P241', 'Use explosion-proof [electrical/ventilating/lighting/...] equipment.', 'prevention'),
  ('P242', 'Use non-sparking tools.', 'prevention'),
  ('P243', 'Take action to prevent static discharges.', 'prevention'),
  ('P244', 'Keep valves and fittings free from oil and grease.', 'prevention'),
  ('P250', 'Do not subject to grinding/shock/friction/...', 'prevention'),
  ('P251', 'Do not pierce or burn, even after use.', 'prevention'),
  ('P260', 'Do not breathe dust/fume/gas/mist/vapours/spray.', 'prevention'),
  ('P261', 'Avoid breathing dust/fume/gas/mist/vapours/spray.', 'prevention'),
  ('P262', 'Do not get in eyes, on skin, or on clothing.', 'prevention'),
  ('P263', 'Avoid contact during pregnancy and while nursing.', 'prevention'),
  ('P264', 'Wash [...] thoroughly after handling.', 'prevention'),
  ('P265', 'Do not touch eyes.', 'prevention'),
  ('P270', 'Do not eat, drink or smoke when using this product.', 'prevention'),
  ('P271', 'Use only outdoors or in a well-ventilated area.', 'prevention'),
  ('P272', 'Contaminated work clothing should not be allowed out of the workplace.', 'prevention'),
  ('P273', 'Avoid release to the environment.', 'prevention'),
  ('P280', 'Wear protective gloves/protective clothing/eye protection/face protection/hearing protection/...', 'prevention'),
  ('P282', 'Wear cold insulating gloves and either face shield or eye protection.', 'prevention'),
  ('P283', 'Wear fire resistant or flame retardant clothing.', 'prevention'),
  ('P284', '[In case of inadequate ventilation] wear respiratory protection.', 'prevention'),
  -- Response
  ('P301', 'IF SWALLOWED:', 'response'),
  ('P302', 'IF ON SKIN:', 'response'),
  ('P303', 'IF ON SKIN (or hair):', 'response'),
  ('P304', 'IF INHALED:', 'response'),
  ('P305', 'IF IN EYES:', 'response'),
  ('P306', 'IF ON CLOTHING:', 'response'),
  ('P308', 'IF exposed or concerned:', 'response'),
  ('P316', 'Get emergency medical help immediately.', 'response'),
  ('P317', 'Get medical help.', 'response'),
  ('P318', 'If exposed or concerned, get medical advice.', 'response'),
  ('P319', 'Get medical help if you feel unwell.', 'response'),
  ('P320', 'Specific treatment is urgent (see ... on this label).', 'response'),
  ('P321', 'Specific treatment (see ... on this label).', 'response'),
  ('P322', 'Specific measures (see ... on this label).', 'response'),
  ('P323', 'Specific treatment (see ... on the safety data sheet).', 'response'),
  ('P330', 'Rinse mouth.', 'response'),
  ('P331', 'Do NOT induce vomiting.', 'response'),
  ('P332', 'If skin irritation occurs:', 'response'),
  ('P333', 'If skin irritation or rash occurs:', 'response'),
  ('P334', 'Immerse in cool water [or wrap in wet bandages].', 'response'),
  ('P335', 'Brush off loose particles from skin.', 'response'),
  ('P336', 'Thaw frosted parts with lukewarm water. Do not rub affected area.', 'response'),
  ('P337', 'If eye irritation persists:', 'response'),
  ('P338', 'Remove contact lenses, if present and easy to do. Continue rinsing.', 'response'),
  ('P340', 'Remove person to fresh air and keep comfortable for breathing.', 'response'),
  ('P342', 'If experiencing respiratory symptoms:', 'response'),
  ('P351', 'Rinse cautiously with water for several minutes.', 'response'),
  ('P352', 'Wash with plenty of water/...', 'response'),
  ('P353', 'Rinse skin with water [or shower].', 'response'),
  ('P354', 'Immediately rinse with water for several minutes.', 'response'),
  ('P360', 'Rinse immediately contaminated clothing and skin with plenty of water before removing clothes.', 'response'),
  ('P361', 'Take off immediately all contaminated clothing.', 'response'),
  ('P362', 'Take off contaminated clothing.', 'response'),
  ('P363', 'Wash contaminated clothing before reuse.', 'response'),
  ('P364', 'And wash it before reuse.', 'response'),
  ('P370', 'In case of fire:', 'response'),
  ('P371', 'In case of major fire and large quantities:', 'response'),
  ('P372', 'Explosion risk.', 'response'),
  ('P373', 'DO NOT fight fire when fire reaches explosives.', 'response'),
  ('P375', 'Fight fire remotely due to the risk of explosion.', 'response'),
  ('P376', 'Stop leak if safe to do so.', 'response'),
  ('P377', 'Leaking gas fire: Do not extinguish, unless leak can be stopped safely.', 'response'),
  ('P378', 'Use ... to extinguish.', 'response'),
  ('P380', 'Evacuate area.', 'response'),
  ('P381', 'In case of leakage, eliminate all ignition sources.', 'response'),
  ('P390', 'Absorb spillage to prevent material damage.', 'response'),
  ('P391', 'Collect spillage.', 'response'),
  -- Storage
  ('P401', 'Store in accordance with ...', 'storage'),
  ('P402', 'Store in a dry place.', 'storage'),
  ('P403', 'Store in a well-ventilated place.', 'storage'),
  ('P404', 'Store in a closed container.', 'storage'),
  ('P405', 'Store locked up.', 'storage'),
  ('P406', 'Store in a corrosion resistant/... container with a resistant inner liner.', 'storage'),
  ('P407', 'Maintain air gap between stacks or pallets.', 'storage'),
  ('P410', 'Protect from sunlight.', 'storage'),
  ('P411', 'Store at temperatures not exceeding ... °C/... °F.', 'storage'),
  ('P412', 'Do not expose to temperatures exceeding 50 °C/122 °F.', 'storage'),
  ('P413', 'Store bulk masses greater than ... kg/... lbs at temperatures not exceeding ... °C/... °F.', 'storage'),
  ('P420', 'Store separately.', 'storage'),
  -- Disposal
  ('P501', 'Dispose of contents/container to ...', 'disposal'),
  ('P502', 'Refer to manufacturer or supplier for information on recovery or recycling.', 'disposal'),
  ('P503', 'Refer to manufacturer/supplier/... for information on disposal/recovery/recycling.', 'disposal')
) AS v (code, text, kind)
ON CONFLICT (id) DO NOTHING;
