/**
 * Main annotator: numbers an antibody sequence and returns structured results.
 */

import type {
  Scheme, ChainType, ChainGroup,
  NumberingResult, NumberingEntry, RegionAnnotation,
} from './types';
import { alignSequence } from './alignment';
import { getRegions } from './data/regions';

const VALID_AAS = new Set('ACDEFGHIKLMNPQRSTVWY');

/**
 * Extract and clean a single-letter amino acid sequence from various input formats.
 */
export function extractSequence(raw: string): string {
  if (!raw) return '';
  const s = raw.trim().replace(/[-.\s]/g, '');
  return Array.from(s.toUpperCase()).filter(c => VALID_AAS.has(c)).join('');
}

/**
 * Number a single antibody sequence.
 *
 * @param sequence - Raw amino acid sequence (single-letter codes)
 * @param scheme - Numbering scheme: 'imgt', 'kabat', 'chothia', or 'aho'
 * @param chains - Which chain types to try: ['H', 'K', 'L'] by default
 * @returns Structured numbering result
 */
export function numberSequence(
  sequence: string,
  scheme: Scheme = 'imgt',
  chains: ChainType[] = ['H', 'K', 'L'],
): NumberingResult {
  const seq = extractSequence(sequence);

  if (!seq) {
    return emptyResult('Empty or invalid sequence');
  }

  if (seq.length < 10) {
    return emptyResult('Sequence too short (minimum 10 residues)');
  }

  // Perform alignment
  const alignment = alignSequence(seq, scheme, chains);

  if (alignment.error && alignment.percentIdentity < 0.3) {
    return emptyResult(alignment.error);
  }

  // Determine chain group
  const chainGroup: ChainGroup = alignment.chainType === 'H' ? 'Heavy' : 'Light';

  // Build numbering detail and position names
  const numberingDetail: NumberingEntry[] = [];
  const posNames: string[] = [];
  const numberingMap: Record<string, number> = {};

  for (let i = 0; i < seq.length; i++) {
    const posCode = alignment.numbering[i];
    if (posCode !== '-') {
      posNames.push(posCode);
      numberingDetail.push({ position: posCode, aa: seq[i] });
      numberingMap[posCode] = i;
    }
  }

  // Build region annotations
  const regionDefs = getRegions(scheme, chainGroup);
  const annotations: RegionAnnotation[] = regionDefs.map(([name, start, end]) => ({
    id: `${scheme}-${chainGroup}-${name}`.toLowerCase(),
    name,
    description: `${name} (${scheme.toUpperCase()} ${start}-${end})`,
    start: String(start),
    end: String(end),
    visualType: 'region' as const,
    category: 'structure' as const,
    sourceScheme: scheme.toUpperCase(),
    autoGenerated: true,
  }));

  return {
    positionNames: posNames.join(', '),
    chainType: chainGroup,
    chainTypeCode: alignment.chainType,
    annotations,
    numberingDetail,
    numberingMap,
    percentIdentity: alignment.percentIdentity,
    error: alignment.error,
    numbering: alignment.numbering,
  };
}

/**
 * Number multiple sequences at once.
 */
export function numberSequences(
  sequences: string[],
  scheme: Scheme = 'imgt',
  chains: ChainType[] = ['H', 'K', 'L'],
): NumberingResult[] {
  return sequences.map(seq => numberSequence(seq, scheme, chains));
}

function emptyResult(error: string): NumberingResult {
  return {
    positionNames: '',
    chainType: 'Heavy',
    chainTypeCode: '',
    annotations: [],
    numberingDetail: [],
    numberingMap: {},
    percentIdentity: 0,
    error,
    numbering: [],
  };
}
