/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  /**
  Configure and simulate daily bacterial growth in a bioreactor
  */
  export async function bioreactorWorkflow(params: any ): Promise<any> {
    return await grok.functions.call('BioreactorWorkflowDemo:BioreactorWorkflow', { params });
  }

  /**
  Define the initial reactor state and bacterial growth parameters
  */
  export async function bioreactorConfiguration(initialVolume: number , initialBiomass: number , initialSubstrate: number , muMax: number , monodKs: number , biomassYield: number , decayRate: number , maxVolume: number ): Promise<{volume: number, biomass: number, substrate: number, maximumGrowthRate: number, halfSaturationConstant: number, yieldCoefficient: number, decayConstant: number, dayDuration: number, workingVolumeLimit: number}> {
    return await grok.functions.call('BioreactorWorkflowDemo:BioreactorConfiguration', { initialVolume, initialBiomass, initialSubstrate, muMax, monodKs, biomassYield, decayRate, maxVolume });
  }

  /**
  Apply daily feeding and simulate bacterial growth for one cultivation day
  */
  export async function dayCalculation(solutionAdded: number , substrateAdded: number , incomingVolume: number , incomingBiomass: number , incomingSubstrate: number , maximumGrowthRate: number , halfSaturationConstant: number , yieldCoefficient: number , decayConstant: number , dayDuration: number ): Promise<{finalVolume: number, finalBiomass: number, finalSubstrate: number, finalBiomassMass: number, finalSubstrateMass: number, biomassMassChange: number, substrateConsumed: number, dailyProfile: DG.DataFrame}> {
    return await grok.functions.call('BioreactorWorkflowDemo:DayCalculation', { solutionAdded, substrateAdded, incomingVolume, incomingBiomass, incomingSubstrate, maximumGrowthRate, halfSaturationConstant, yieldCoefficient, decayConstant, dayDuration });
  }

  export async function info(): Promise<void> {
    return await grok.functions.call('BioreactorWorkflowDemo:Info', {});
  }
}
