let dm = {
  'STUDYID': 'Study Identier',
  'DOMAIN': 'Domain Abbreviation',
  'USUBJID': ' Unique Subject Identier',
  'SUBJID': 'Subject Identier for the Study',
  'RFSTDTC': 'Subject Reference Start Date/Time',
  'RFENDTC': 'Subject Reference End Date/Time',
  'RFXSTDTC': 'Date/Time of First Study Treatment',
  'RFXENDTC': 'Date/Time of Last Study Treatment',
  'RFICDTC': 'Date/Time of Informed Consent',
  'RFPENDTC': 'Date/Time of End of Participation',
  'DTHDTC': 'Date/Time of Death',
  'DTHFL': 'Subject Death Flag',
  'SITEID': 'Study Site Identier',
  'AGE': 'Age',
  'AGEU': 'Age Units',
  'SEX': 'Sex',
  'RACE': 'Race',
  'ETHNIC': 'Ethnicity',
  'ARMCD': 'Planned Arm Code',
  'ARM': 'Description of Planned Arm',
  'ACTARMCD': 'Actual Arm Code',
  'ACTARM': 'Description of Actual Arm',
  'COUNTRY': 'Country',
  'DMDTC': 'Date/Time of Collection',
  'DMDY': 'Study Day of Collection double 5'
};