// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    api: [
        {
            type: 'doc',
            id: 'index',
            label: 'API Overview',
        },
        {
            type: 'category',
            label: 'JavaScript API',
            link: { type: "doc", id: "js/index" },
            items: require('./js/typedoc-sidebar'), // e.g., sidebar generated by TypeDoc plugin
        },
        {
            type: 'category',
            label: 'Python API',
            link: { type: "doc", id: "py/index" },
            items: require('./py/typedoc-sidebar'), // your manually created sidebar for Python API
        },
    ],
};

module.exports = sidebars;
