/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('valerij_developer_exercise_1:Info', {});
  }

  export async function complement(nucleotides: string ): Promise<string> {
    return await grok.functions.call('valerij_developer_exercise_1:Complement', { nucleotides });
  }

  export async function complementWidget(nucleotides: string ): Promise<any> {
    return await grok.functions.call('valerij_developer_exercise_1:ComplementWidget', { nucleotides });
  }
}
