// Worker for the function 'solveFAEexplicitWebWorker'.

// Import from JS-file generated by Emscripten
import {exportFAEexplicit} from '../wasm/FAEexplicitForWebWorker';

// Import utilities
import {cppWrapper} from './callWasmUtils';

onmessage = async function (evt) {
  exportFAEexplicit().then(module => 
    { 
        // exctract arguments to be put to wasm-function    
        let args = evt.data

        // call c++/wasm-function via wrapper
        let result = cppWrapper(module, args, 'solveFAEexplicit', 'number');

        // post results
        postMessage({'callResult': result, 'args': args});
    } )
}