export interface DomainInfo {
  description: string;
  category: string;
}

export const DOMAINS_DESCRIPTIONS: {[key: string]: any} = {
  ae: {SEND: {}, SDTM: {description: 'Adverse Events', category: 'Events'}},
  ag: {SEND: {description: 'Additional Genetic Tests', category: 'Genetics / Genomics'}, SDTM: {}},
  apce: {SEND: {}, SDTM: {description: 'Associated Persons Clinical Events', category: 'Associated Persons'}},
  apcm: {SEND: {}, SDTM: {description: 'Associated Persons Concomitant Medications', category: 'Associated Persons'}},
  apeg: {SEND: {}, SDTM: {description: 'Associated Persons ECG', category: 'Associated Persons'}},
  aplb: {SEND: {}, SDTM: {description: 'Associated Persons Laboratory Tests', category: 'Associated Persons'}},
  apmh: {SEND: {}, SDTM: {description: 'Associated Persons Medical History', category: 'Associated Persons'}},
  apvs: {SEND: {}, SDTM: {description: 'Associated Persons Vital Signs', category: 'Associated Persons'}},
  bg: {SEND: {description: 'Background Genetics', category: 'Genetics / Genomics'}, SDTM: {}},
  bw: {SEND: {description: 'Body Weights', category: 'Findings'}, SDTM: {}},
  ce: {SEND: {}, SDTM: {description: 'Clinical Events', category: 'Events'}},
  cl: {SEND: {description: 'Clinical Observations', category: 'Findings'}, SDTM: {}},
  cm: {SEND: {}, SDTM: {description: 'Concomitant Medications', category: 'Interventions'}},
  co: {SEND: {description: 'Comments', category: 'Core / Special Purpose'},
    SDTM: {description: 'Comments', category: 'Core / Special Purpose'}},
  da: {SEND: {}, SDTM: {description: 'Drug Accountability', category: 'Interventions'}},
  dd: {SEND: {}, SDTM: {description: 'Death Details', category: 'Events'}},
  dm: {SEND: {description: 'Demographics', category: 'Core / Special Purpose'},
    SDTM: {description: 'Demographics', category: 'Core / Special Purpose'}},
  ds: {SEND: {description: 'Disposition', category: 'Events'}, SDTM: {description: 'Disposition', category: 'Events'}},
  dv: {SEND: {}, SDTM: {description: 'Protocol Deviations', category: 'Events'}},
  ec: {SEND: {}, SDTM: {description: 'Exposure as Collected', category: 'Interventions'}},
  eg: {SEND: {description: 'Electrocardiograms', category: 'Findings'},
    SDTM: {description: 'Electrocardiograms', category: 'Findings'}},
  ex: {SEND: {}, SDTM: {description: 'Exposure', category: 'Interventions'}},
  ey: {SEND: {description: 'Eye Examinations', category: 'Findings'}, SDTM: {}},
  fa: {SEND: {}, SDTM: {description: 'Findings About', category: 'Findings'}},
  ft: {SEND: {}, SDTM: {description: 'Functional Tests', category: 'Findings'}},
  fw: {SEND: {description: 'Food and Water Consumption', category: 'Findings'}, SDTM: {}},
  gf: {SEND: {}, SDTM: {description: 'Genetic Features', category: 'Genetics / Genomics'}},
  ho: {SEND: {}, SDTM: {description: 'Healthcare Encounters', category: 'Events'}},
  ie: {SEND: {}, SDTM: {description: 'Inclusion/Exclusion Criteria Not Met', category: 'Events'}},
  ig: {SEND: {description: 'In-Life Gestational Findings', category: 'Findings'}, SDTM: {}},
  is: {SEND: {}, SDTM: {description: 'Immunogenicity Specimen Assessments', category: 'Findings'}},
  lb: {SEND: {description: 'Laboratory Test Results', category: 'Findings'},
    SDTM: {description: 'Laboratory Test Results', category: 'Findings'}},
  ma: {SEND: {description: 'Macroscopic Findings', category: 'Findings'}, SDTM: {}},
  mb: {SEND: {}, SDTM: {description: 'Microbiology Findings', category: 'Findings'}},
  mh: {SEND: {}, SDTM: {description: 'Medical History', category: 'Medical History'}},
  mi: {SEND: {description: 'Microscopic Findings', category: 'Findings'},
    SDTM: {description: 'Microbiology Findings', category: 'Findings'}},
  ml: {SEND: {description: 'Morphology / Localization', category: 'Genetics / Genomics'}, SDTM: {}},
  ms: {SEND: {}, SDTM: {description: 'Microbiology Susceptibility', category: 'Findings'}},
  nc: {SEND: {description: 'Neurobehavioral Findings', category: 'Findings'}, SDTM: {}},
  oe: {SEND: {}, SDTM: {description: 'Objective Evidence', category: 'Findings'}},
  om: {SEND: {description: 'Organ Measurements', category: 'Findings'}, SDTM: {}},
  pc: {SEND: {description: 'Pharmacokinetic Concentrations', category: 'Findings'},
    SDTM: {description: 'Pharmacogenetics / Genomics', category: 'Genetics / Genomics'}},
  pe: {SEND: {}, SDTM: {description: 'Physical Examination', category: 'Findings'}},
  pm: {SEND: {description: 'Palpable Masses', category: 'Findings'},
    SDTM: {description: 'Pharmacometrics', category: 'Pharmacokinetics / Modeling'}},
  po: {SEND: {description: 'Physical Observations', category: 'Findings'}, SDTM: {}},
  pp: {SEND: {description: 'Pharmacokinetic Parameters', category: 'Pharmacokinetics / Modeling'},
    SDTM: {description: 'Pharmacokinetic Parameters', category: 'Pharmacokinetics / Modeling'}},
  pr: {SEND: {}, SDTM: {description: 'Procedures', category: 'Interventions'}},
  qs: {SEND: {}, SDTM: {description: 'Questionnaires', category: 'Findings'}},
  relrec: {SEND: {description: 'Related Records', category: 'Core / Special Purpose'},
    SDTM: {description: 'Related Records', category: 'Core / Special Purpose'}},
  rp: {SEND: {}, SDTM: {description: 'Reproductive Findings', category: 'Findings'}},
  rs: {SEND: {}, SDTM: {description: 'Disease Response / Clinical Classification',
    category: 'Tumor / Disease Response'}},
  sc: {SEND: {description: 'Subject Characteristics', category: 'Core / Special Purpose'},
    SDTM: {description: 'Subject Characteristics', category: 'Core / Special Purpose'}},
  se: {SEND: {description: 'Subject Elements', category: 'Core / Special Purpose'},
    SDTM: {description: 'Subject Elements', category: 'Core / Special Purpose'}},
  sm: {SEND: {description: 'Subject Milestones', category: 'Core / Special Purpose'},
    SDTM: {description: 'Subject Milestones', category: 'Core / Special Purpose'}},
  sr: {SEND: {description: 'Short-Term Routine Observations', category: 'Findings'}, SDTM: {}},
  su: {SEND: {}, SDTM: {description: 'Substance Use', category: 'Interventions'}},
  sv: {SEND: {description: 'Subject Visits', category: 'Core / Special Purpose'},
    SDTM: {description: 'Subject Visits', category: 'Core / Special Purpose'}},
  ta: {SEND: {}, SDTM: {description: 'Trial Arms', category: 'Trial Design'}},
  td: {SEND: {}, SDTM: {description: 'Trial Disease Assessments', category: 'Trial Design'}},
  te: {SEND: {}, SDTM: {description: 'Trial Elements', category: 'Trial Design'}},
  tf: {SEND: {description: 'Tumor Findings', category: 'Findings'}, SDTM: {}},
  ti: {SEND: {}, SDTM: {description: 'Trial Inclusion/Exclusion Criteria', category: 'Trial Design'}},
  tm: {SEND: {}, SDTM: {description: 'Trial Disease Milestones', category: 'Trial Design'}},
  tr: {SEND: {}, SDTM: {description: 'Tumor / Lesion Results', category: 'Tumor / Disease Response'}},
  ts: {SEND: {}, SDTM: {description: 'Trial Summary', category: 'Trial Design'}},
  tu: {SEND: {}, SDTM: {description: 'Tumor / Lesion Identification', category: 'Tumor / Disease Response'}},
  tv: {SEND: {}, SDTM: {description: 'Trial Visits', category: 'Trial Design'}},
  tx: {SEND: {description: 'SEND Trial Summary', category: 'Trial Design'}, SDTM: {}},
  vs: {SEND: {description: 'Vital Signs', category: 'Findings'},
    SDTM: {description: 'Vital Signs', category: 'Findings'}},
};

export const SUPP_DOMAIN_CATEGORY = 'Supplemental';

export const DOMAINS_CATEGORIES_LIST = ['Core / Special Purpose', 'Interventions', 'Events', 'Findings',
  'Tumor / Disease Response', 'Medical History', 'Genetics / Genomics', 'Pharmacokinetics / Modeling',
  'Associated Persons', 'Trial Design', 'Supplemental', 'Other'];
