export interface DomainInfo {
  description: string;
  category: string;
}

export const DOMAINS_DESCRIPTIONS: {[key: string]: any} = {
  ae: {SDTM: {description: 'Adverse Events', category: 'Events'}},
  apce: {SDTM: {description: 'Associated Persons Clinical Events', category: 'Associated Persons'}},
  apcm: {SDTM: {description: 'Associated Persons Concomitant Medications', category: 'Associated Persons'}},
  apeg: {SDTM: {description: 'Associated Persons ECG', category: 'Associated Persons'}},
  aplb: {SDTM: {description: 'Associated Persons Laboratory Tests', category: 'Associated Persons'}},
  apmh: {SDTM: {description: 'Associated Persons Medical History', category: 'Associated Persons'}},
  apvs: {SDTM: {description: 'Associated Persons Vital Signs', category: 'Associated Persons'}},
  ce: {SDTM: {description: 'Clinical Events', category: 'Events'}},
  cm: {SDTM: {description: 'Concomitant Medications', category: 'Interventions'}},
  co: {SDTM: {description: 'Comments', category: 'Core / Special Purpose'}},
  da: {SDTM: {description: 'Drug Accountability', category: 'Interventions'}},
  dd: {SDTM: {description: 'Death Details', category: 'Events'}},
  dm: {SDTM: {description: 'Demographics', category: 'Core / Special Purpose'}},
  ds: {SDTM: {description: 'Disposition', category: 'Events'}},
  dv: {SDTM: {description: 'Protocol Deviations', category: 'Events'}},
  ec: {SDTM: {description: 'Exposure as Collected', category: 'Interventions'}},
  eg: {SDTM: {description: 'Electrocardiograms', category: 'Findings'}},
  ex: {SDTM: {description: 'Exposure', category: 'Interventions'}},
  fa: {SDTM: {description: 'Findings About', category: 'Findings'}},
  ft: {SDTM: {description: 'Functional Tests', category: 'Findings'}},
  gf: {SDTM: {description: 'Genetic Features', category: 'Genetics / Genomics'}},
  ho: {SDTM: {description: 'Healthcare Encounters', category: 'Events'}},
  ie: {SDTM: {description: 'Inclusion/Exclusion Criteria Not Met', category: 'Events'}},
  is: {SDTM: {description: 'Immunogenicity Specimen Assessments', category: 'Findings'}},
  lb: {SDTM: {description: 'Laboratory Test Results', category: 'Findings'}},
  mb: {SDTM: {description: 'Microbiology Findings', category: 'Findings'}},
  mh: {SDTM: {description: 'Medical History', category: 'Medical History'}},
  mi: {SDTM: {description: 'Microbiology Findings', category: 'Findings'}},
  ms: {SDTM: {description: 'Microbiology Susceptibility', category: 'Findings'}},
  oe: {SDTM: {description: 'Objective Evidence', category: 'Findings'}},
  pc: {SDTM: {description: 'Pharmacogenetics / Genomics', category: 'Genetics / Genomics'}},
  pe: {SDTM: {description: 'Physical Examination', category: 'Findings'}},
  pm: {SDTM: {description: 'Pharmacometrics', category: 'Pharmacokinetics / Modeling'}},
  pp: {SDTM: {description: 'Pharmacokinetic Parameters', category: 'Pharmacokinetics / Modeling'}},
  pr: {SDTM: {description: 'Procedures', category: 'Interventions'}},
  qs: {SDTM: {description: 'Questionnaires', category: 'Findings'}},
  relrec: {SDTM: {description: 'Related Records', category: 'Core / Special Purpose'}},
  rp: {SDTM: {description: 'Reproductive Findings', category: 'Findings'}},
  rs: {SDTM: {description: 'Disease Response / Clinical Classification',
    category: 'Tumor / Disease Response'}},
  sc: {SDTM: {description: 'Subject Characteristics', category: 'Core / Special Purpose'}},
  se: {SDTM: {description: 'Subject Elements', category: 'Core / Special Purpose'}},
  sm: {SDTM: {description: 'Subject Milestones', category: 'Core / Special Purpose'}},
  su: {SDTM: {description: 'Substance Use', category: 'Interventions'}},
  sv: {SDTM: {description: 'Subject Visits', category: 'Core / Special Purpose'}},
  ta: {SDTM: {description: 'Trial Arms', category: 'Trial Design'}},
  td: {SDTM: {description: 'Trial Disease Assessments', category: 'Trial Design'}},
  te: {SDTM: {description: 'Trial Elements', category: 'Trial Design'}},
  ti: {SDTM: {description: 'Trial Inclusion/Exclusion Criteria', category: 'Trial Design'}},
  tm: {SDTM: {description: 'Trial Disease Milestones', category: 'Trial Design'}},
  tr: {SDTM: {description: 'Tumor / Lesion Results', category: 'Tumor / Disease Response'}},
  ts: {SDTM: {description: 'Trial Summary', category: 'Trial Design'}},
  tu: {SDTM: {description: 'Tumor / Lesion Identification', category: 'Tumor / Disease Response'}},
  tv: {SDTM: {description: 'Trial Visits', category: 'Trial Design'}},
  vs: {SDTM: {description: 'Vital Signs', category: 'Findings'}},
};

export const SUPP_DOMAIN_CATEGORY = 'Supplemental';

export const DOMAINS_CATEGORIES_LIST = ['Core / Special Purpose', 'Interventions', 'Events', 'Findings',
  'Tumor / Disease Response', 'Medical History', 'Genetics / Genomics', 'Pharmacokinetics / Modeling',
  'Associated Persons', 'Trial Design', 'Supplemental', 'Other'];
