export const DOMAINS_DESCRIPTIONS = {
  ae: 'Adverse Events',
  ag: 'Additional Genetic Tests',
  apce: 'Associated Persons Clinical Events',
  apcm: 'Associated Persons Concomitant Medications',
  apeg: 'Associated Persons Electrocardiograms',
  aplb: 'Associated Persons Laboratory Tests',
  apmh: 'Associated Persons Medical History',
  apvs: 'Associated Persons Vital Signs',
  bg: 'Background Genetics',
  bw: 'Body Weights',
  ce: 'Clinical Events',
  cg: 'Cardiovascular System Findings',
  cl: 'Clinical Observations',
  cm: 'Concomitant Medications',
  co: 'Comments',
  cv: 'Cardiovascular System Findings',
  da: 'Drug Accountability',
  dd: 'Death Details',
  dm: 'Demographics',
  ds: 'Disposition',
  dv: 'Protocol Deviations',
  ec: 'Exposure as Collected',
  eg: 'Electrocardiograms',
  ex: 'Exposure',
  ey: 'Eye Examinations',
  fa: 'Findings About',
  ft: 'Functional Tests',
  fw: 'Food and Water Consumption',
  gf: 'Genetic Features',
  ho: 'Healthcare Encounters',
  hp: 'Hematology Findings',
  ie: 'Inclusion/Exclusion Criteria Not Met',
  ig: 'In-Life Gestational Findings',
  is: 'Immunogenicity Specimen Assessments',
  la: 'Laboratory Findings',
  lb: 'Laboratory Test Results',
  ma: 'Macropathology Findings',
  mb: 'Microbiology Findings',
  mh: 'Medical History',
  mi: 'Microbiology Findings',
  mk: 'Microscopic Findings',
  ml: 'Morphology/Localization',
  mo: 'Morphology Findings',
  ms: 'Microbiology Susceptibility',
  nc: 'Neurobehavioral/Cognitive Findings',
  nv: 'Nervous System Findings',
  oe: 'Objective Evidence',
  om: 'Organ Measurements',
  pc: 'Pharmacogenetics/Genomics',
  pm: 'Pharmacometrics',
  pe: 'Physical Examination',
  po: 'Physical Observations',
  pp: 'Pharmacokinetic Parameters',
  pr: 'Procedures',
  qs: 'Questionnaires',
  re: 'Reproductive System Findings',
  relrec: 'Related Records',
  rp: 'Reproductive System Findings',
  rs: 'Disease Response/Clinical Classification',
  sc: 'Subject Characteristics',
  se: 'Subject Elements',
  sm: 'Subject Milestones',
  sr: 'Short-Term Routine Observations',
  su: 'Substance Use',
  sv: 'Subject Visits',
  ta: 'Trial Arms',
  td: 'Trial Disease Assessments',
  te: 'Trial Elements',
  ti: 'Trial Inclusion/Exclusion Criteria',
  tm: 'Trial Disease Milestones',
  tr: 'Tumor/Lesion Results',
  ts: 'Trial Summary',
  tu: 'Tumor/Lesion Identification',
  tv: 'Trial Visits',
  tx: 'SEND Trial Summary',
  ur: 'Urinalysis Findings',
  vs: 'Vital Signs',
};
