// @async-source: lbfgs-driver-sync.ts
// @codegen-rename: runLBFGSAsync=runLBFGSSync
// @codegen-rename: lineSearchAsync=lineSearch
// @codegen-rename: computeGradientAsync=computeGradient

// L-BFGS outer driver. The async version is the source of truth; the sync
// sibling (`lbfgs-driver-sync.ts`) is generated by the async-to-sync
// codegen. The `LBFGS` class in `lbfgs.ts` is a thin shim that delegates
// here.

import type {OptimizationResult, IterationCallback, IterationState} from '../types';
import type {LBFGSSettings} from './lbfgs';

/** Stateless helpers the driver borrows from the `LBFGS` class. */
export interface LBFGSDeps {
  notify: (cb: IterationCallback | undefined, state: IterationState) => boolean;
}

/** Reusable scratch struct for line search status. */
export interface LineSearchResult {
  stepSize: number;
  accepted: boolean;
  fNew: number;
}

/** Curvature-condition threshold: skip history update when y·s ≤ CURVATURE_EPS·max(1, y·y). */
export const CURVATURE_EPS = 1e-10;

/* ================================================================== */
/*  Shared helpers                                                     */
/* ================================================================== */

/**
 * Two-loop recursion for L-BFGS inverse-Hessian–gradient product.
 *
 * Computes H·g in-place into `direction` without ever forming H.
 * History is stored in a ring buffer: `histHead` is the next write
 * position, and `histCount` pairs (oldest first) live at logical
 * positions 0..histCount-1, mapped to physical positions via
 * `(histHead − histCount + k + m) % m`.
 *
 * Uses the most recent (s, y) pair for initial Hessian scaling
 * γ = (s · y) / (y · y). Writes into caller-provided `direction`
 * buffer; no allocations.
 */
export function twoLoopRecursion(
  grad: Float64Array,
  S: Float64Array[],
  Y: Float64Array[],
  rho: Float64Array,
  alphaScratch: Float64Array,
  histHead: number,
  count: number,
  m: number,
  n: number,
  direction: Float64Array,
): void {
  direction.set(grad);

  for (let k = count - 1; k >= 0; k--) {
    const phys = (histHead - count + k + m) % m;
    const sVec = S[phys];
    const yVec = Y[phys];
    let sq = 0;
    for (let i = 0; i < n; i++) sq += sVec[i] * direction[i];
    const a = rho[phys] * sq;
    alphaScratch[k] = a;
    for (let i = 0; i < n; i++) direction[i] -= a * yVec[i];
  }

  const newest = (histHead - 1 + m) % m;
  const sNewest = S[newest];
  const yNewest = Y[newest];
  let sy = 0;
  let yy = 0;
  for (let i = 0; i < n; i++) {
    sy += sNewest[i] * yNewest[i];
    yy += yNewest[i] * yNewest[i];
  }
  const gamma = (yy > 0) ? sy / yy : 1;
  for (let i = 0; i < n; i++) direction[i] *= gamma;

  for (let k = 0; k < count; k++) {
    const phys = (histHead - count + k + m) % m;
    const sVec = S[phys];
    const yVec = Y[phys];
    let yr = 0;
    for (let i = 0; i < n; i++) yr += yVec[i] * direction[i];
    const beta = rho[phys] * yr;
    const coef = alphaScratch[k] - beta;
    for (let i = 0; i < n; i++) direction[i] += coef * sVec[i];
  }
}

/* ================================================================== */
/*  Async helpers (twins; sync siblings are codegen-generated)         */
/* ================================================================== */

/**
 * Armijo backtracking line search.
 *
 * Finds a step size α along `direction` satisfying the Armijo
 * sufficient-decrease condition `f(x + α·d) ≤ f(x) + c₁·α·(∇f·d)`.
 * Starts at `initStep` and halves on each rejection or NaN/Inf eval.
 *
 * Writes the trial point into caller-provided `xNew`, and the status
 * (step, accepted, fNew) into caller-provided `result`. If no finite
 * eval is ever produced, `xNew` is restored to `x` and `stepSize=0`.
 */
async function lineSearchAsync(
  fn: (x: Float64Array) => Promise<number>,
  x: Float64Array,
  direction: Float64Array,
  fx: number,
  slope: number,
  c1: number,
  initStep: number,
  maxSteps: number,
  n: number,
  xNew: Float64Array,
  result: LineSearchResult,
): Promise<void> {
  let alpha = initStep;
  let bestAlpha = 0;
  let accepted = false;
  let fNew = fx;
  let foundFinite = false;

  for (let step = 0; step < maxSteps; step++) {
    for (let i = 0; i < n; i++) xNew[i] = x[i] + alpha * direction[i];
    const f = await fn(xNew);

    if (isFinite(f)) {
      foundFinite = true;
      bestAlpha = alpha;
      fNew = f;
      if (f <= fx + c1 * alpha * slope) {
        accepted = true;
        break;
      }
    }
    alpha *= 0.5;
  }

  if (!accepted) {
    if (foundFinite)
      for (let i = 0; i < n; i++) xNew[i] = x[i] + bestAlpha * direction[i];
    else {
      xNew.set(x);
      fNew = fx;
      bestAlpha = 0;
    }
  }

  result.stepSize = bestAlpha;
  result.accepted = accepted;
  result.fNew = fNew;
}

/** Central finite-difference gradient: ∂f/∂xᵢ ≈ (f(x+hᵢ) − f(x−hᵢ)) / 2h */
async function computeGradientAsync(
  fn: (x: Float64Array) => Promise<number>,
  x: Float64Array,
  grad: Float64Array,
  h: number,
  n: number,
): Promise<void> {
  for (let i = 0; i < n; i++) {
    const orig = x[i];
    x[i] = orig + h;
    const fPlus = await fn(x);
    x[i] = orig - h;
    const fMinus = await fn(x);
    x[i] = orig;
    grad[i] = (fPlus - fMinus) / (2 * h);
  }
}

/* ================================================================== */
/*  Driver                                                             */
/* ================================================================== */

export async function runLBFGSAsync(
  fn: (x: Float64Array) => Promise<number>,
  x0: Float64Array,
  s: LBFGSSettings,
  deps: LBFGSDeps,
): Promise<OptimizationResult> {
  const n = x0.length;
  const maxIter = s.maxIterations!;
  const tol = s.tolerance!;
  const m = s.historySize!;
  const h = s.finiteDiffStep!;
  const gradTol = s.gradTolerance!;
  const c1 = s.c1!;
  const maxLS = s.maxLineSearchSteps!;
  const initStep = s.initialStepSize!;

  const x = Float64Array.from(x0);
  const grad = new Float64Array(n);
  const direction = new Float64Array(n);
  const xNew = new Float64Array(n);
  const gradNew = new Float64Array(n);

  const S: Float64Array[] = new Array(m);
  const Y: Float64Array[] = new Array(m);
  for (let i = 0; i < m; i++) {
    S[i] = new Float64Array(n);
    Y[i] = new Float64Array(n);
  }
  const rho = new Float64Array(m);
  const alphaScratch = new Float64Array(m);

  const costHistory = new Float64Array(maxIter + 1);
  let costLen = 0;

  const bestPoint = new Float64Array(n);
  bestPoint.set(x);

  let fCur = await fn(x);
  await computeGradientAsync(fn, x, grad, h, n);

  let bestValue = fCur;
  let histCount = 0;
  let histHead = 0;
  let iteration = 0;
  let converged = false;
  const lsResult: LineSearchResult = {stepSize: 0, accepted: false, fNew: 0};

  while (iteration < maxIter) {
    // --- Gradient max-norm convergence (matches SciPy's pgtol) ---
    let gNormInf = 0;
    let gNaN = false;
    for (let i = 0; i < n; i++) {
      const g = Math.abs(grad[i]);
      if (g !== g) {gNaN = true; break;}
      if (g > gNormInf) gNormInf = g;
    }
    if (!gNaN && gNormInf < gradTol) {converged = true; break;}

    if (fCur < bestValue) {
      bestValue = fCur;
      bestPoint.set(x);
    }
    costHistory[costLen++] = bestValue;

    if (deps.notify(s.onIteration, {iteration, bestValue, bestPoint}))
      break;

    // --- Search direction via two-loop recursion (steepest descent if no history) ---
    if (histCount === 0)
      for (let i = 0; i < n; i++) direction[i] = -grad[i];
    else {
      twoLoopRecursion(
        grad, S, Y, rho, alphaScratch, histHead, histCount, m, n, direction,
      );
      for (let i = 0; i < n; i++) direction[i] = -direction[i];
    }

    // --- Descent check: if direction is not a descent, reset history ---
    let slope = 0;
    for (let i = 0; i < n; i++) slope += grad[i] * direction[i];
    if (!(slope < 0)) {
      histCount = 0;
      slope = 0;
      for (let i = 0; i < n; i++) {
        direction[i] = -grad[i];
        slope -= grad[i] * grad[i];
      }
    }

    // --- Line search ---
    await lineSearchAsync(fn, x, direction, fCur, slope, c1, initStep, maxLS, n, xNew, lsResult);

    // --- Gradient at new point ---
    await computeGradientAsync(fn, xNew, gradNew, h, n);

    // --- History update (only on accepted step, gated by curvature condition) ---
    if (lsResult.accepted) {
      const sBuf = S[histHead];
      const yBuf = Y[histHead];
      let ys = 0;
      let yy = 0;
      for (let i = 0; i < n; i++) {
        const si = xNew[i] - x[i];
        const yi = gradNew[i] - grad[i];
        sBuf[i] = si;
        yBuf[i] = yi;
        ys += yi * si;
        yy += yi * yi;
      }
      if (ys > CURVATURE_EPS * Math.max(1, yy)) {
        rho[histHead] = 1 / ys;
        histHead = (histHead + 1) % m;
        if (histCount < m) histCount++;
      }
    }

    // --- Function-value convergence: |Δf| / max(|f_k|, |f_{k+1}|, 1) < tolerance ---
    const fNew = lsResult.fNew;
    const denom = Math.max(Math.abs(fCur), Math.abs(fNew), 1);
    const fChange = Math.abs(fNew - fCur) / denom;

    // --- Advance state ---
    x.set(xNew);
    fCur = fNew;
    grad.set(gradNew);

    if (fCur < bestValue) {
      bestValue = fCur;
      bestPoint.set(x);
    }

    iteration++;

    if (fChange < tol) {converged = true; break;}
  }

  return {
    point: bestPoint,
    value: bestValue,
    iterations: iteration,
    converged,
    costHistory: costHistory.subarray(0, costLen),
  };
}
