// @async-source: nelder-mead-driver-sync.ts
// @codegen-rename: runNelderMeadAsync=runNelderMeadSync
// @codegen-rename: buildSimplexAsync=buildSimplex
// @codegen-rename: shrinkSimplexAsync=shrinkSimplex

// Nelder-Mead outer driver. The async version is the source of truth; the
// sync sibling (`nelder-mead-driver-sync.ts`) is generated by the
// async-to-sync codegen. The `NelderMead` class in `nelder-mead.ts` is a
// thin shim that delegates here.

import type {OptimizationResult, IterationCallback, IterationState} from '../types';
import type {NelderMeadSettings} from './nelder-mead';

/** Stateless helpers the driver borrows from the `NelderMead` class. */
export interface NelderMeadDeps {
  notify: (cb: IterationCallback | undefined, state: IterationState) => boolean;
}

export type SimplexVertex = { point: Float64Array; value: number };

/* ================================================================== */
/*  Shared helpers (no fn calls — used by both paths)                  */
/* ================================================================== */

/** Full sort of idx by simplex values. Used once at start and after shrink. */
export function sortIdx(idx: Uint32Array, simplex: { value: number }[]): void {
  idx.sort((a, b) => simplex[a].value - simplex[b].value);
}

/** Centroid of all vertices except the last one in idx (worst). */
export function computeCentroid(
  out: Float64Array,
  simplex: { point: Float64Array }[],
  idx: Uint32Array,
  nVerts: number,
  n: number,
): void {
  out.fill(0);
  const count = nVerts - 1;
  for (let k = 0; k < count; k++) {
    const pt = simplex[idx[k]].point;
    for (let i = 0; i < n; i++) out[i] += pt[i];
  }
  for (let i = 0; i < n; i++) out[i] /= count;
}

/** centroid + scale * (centroid - worst) */
export function transformPoint(
  out: Float64Array,
  centroid: Float64Array,
  worstPoint: Float64Array,
  scale: number,
  n: number,
): void {
  for (let i = 0; i < n; i++)
    out[i] = centroid[i] + scale * (centroid[i] - worstPoint[i]);
}

/**
 * Replace vertex `at` with new point/value, then re-insert into sorted idx.
 * O(n) insertion instead of O(n log n) full sort.
 */
export function acceptAndInsert(
  simplex: SimplexVertex[],
  idx: Uint32Array,
  at: number,
  pt: Float64Array,
  val: number,
): void {
  simplex[at].point.set(pt);
  simplex[at].value = val;

  const len = idx.length;
  let pos = len - 1;

  while (pos > 0 && simplex[idx[pos - 1]].value > val) {
    idx[pos] = idx[pos - 1];
    pos--;
  }
  idx[pos] = at;
}

/* ================================================================== */
/*  Async helpers (twins; sync versions are codegen-generated)         */
/* ================================================================== */

async function buildSimplexAsync(
  fn: (x: Float64Array) => Promise<number>,
  x0: Float64Array,
  s: NelderMeadSettings,
): Promise<SimplexVertex[]> {
  const n = x0.length;
  const simplex: SimplexVertex[] = [];

  const p0 = Float64Array.from(x0);
  simplex.push({point: p0, value: await fn(p0)});

  for (let i = 0; i < n; i++) {
    const p = Float64Array.from(x0);
    p[i] = p[i] === 0 ? s.nonZeroParam! : p[i] * (1 + s.initialScale!);
    simplex.push({point: p, value: await fn(p)});
  }

  return simplex;
}

async function shrinkSimplexAsync(
  simplex: SimplexVertex[],
  idx: Uint32Array,
  bestIdx: number,
  sigma: number,
  fn: (x: Float64Array) => Promise<number>,
): Promise<void> {
  const bestPt = simplex[bestIdx].point;
  const len = idx.length;
  for (let k = 0; k < len; k++) {
    const j = idx[k];
    if (j === bestIdx) continue;
    const pt = simplex[j].point;
    for (let i = 0; i < pt.length; i++)
      pt[i] = bestPt[i] + sigma * (pt[i] - bestPt[i]);
    simplex[j].value = await fn(pt);
  }
}

/* ================================================================== */
/*  Driver                                                             */
/* ================================================================== */

export async function runNelderMeadAsync(
  fn: (x: Float64Array) => Promise<number>,
  x0: Float64Array,
  s: NelderMeadSettings,
  deps: NelderMeadDeps,
): Promise<OptimizationResult> {
  const n = x0.length;
  const nVerts = n + 1;
  const maxIter = s.maxIterations!;
  const tol = s.tolerance!;
  const noImpMax = s.noImprovementLimit ?? 2 * nVerts;

  const simplex = await buildSimplexAsync(fn, x0, s);

  const idx = new Uint32Array(nVerts);
  for (let i = 0; i < nVerts; i++) idx[i] = i;

  const centroid = new Float64Array(n);
  const trial = new Float64Array(n);
  const savedRefl = new Float64Array(n);
  const costHistory = new Float64Array(maxIter);
  let costLen = 0;

  let iteration = 0;
  let prevBest = Infinity;
  let noImprovement = 0;
  let converged = false;

  sortIdx(idx, simplex);

  while (iteration < maxIter) {
    const bestIdx = idx[0];
    const worstIdx = idx[nVerts - 1];
    const bestVal = simplex[bestIdx].value;
    const secondWorstVal = simplex[idx[nVerts - 2]].value;
    const worstVal = simplex[worstIdx].value;
    costHistory[costLen++] = bestVal;

    if (iteration > 0 && prevBest - bestVal > tol)
      noImprovement = 0;
    else if (iteration > 0) {
      noImprovement++;
      if (noImprovement >= noImpMax) {converged = true; break;}
    }
    prevBest = bestVal;

    if (deps.notify(s.onIteration, {
      iteration,
      bestValue: bestVal,
      bestPoint: simplex[bestIdx].point,
    }))
      break;

    computeCentroid(centroid, simplex, idx, nVerts, n);

    // --- Reflection ---
    transformPoint(trial, centroid, simplex[worstIdx].point, s.reflection!, n);
    const reflVal = await fn(trial);

    if (reflVal < bestVal) {
      savedRefl.set(trial);
      transformPoint(trial, centroid, simplex[worstIdx].point, s.expansion!, n);
      const expVal = await fn(trial);

      if (expVal < reflVal)
        acceptAndInsert(simplex, idx, worstIdx, trial, expVal);
      else
        acceptAndInsert(simplex, idx, worstIdx, savedRefl, reflVal);

      iteration++;
      continue;
    }

    if (reflVal < secondWorstVal) {
      acceptAndInsert(simplex, idx, worstIdx, trial, reflVal);
      iteration++;
      continue;
    }

    // --- Contraction ---
    if (reflVal < worstVal) {
      transformPoint(trial, centroid, simplex[worstIdx].point, s.contraction!, n);
      const contrVal = await fn(trial);

      if (contrVal <= reflVal) {
        acceptAndInsert(simplex, idx, worstIdx, trial, contrVal);
        iteration++;
        continue;
      }
    } else {
      transformPoint(trial, centroid, simplex[worstIdx].point, -s.contraction!, n);
      const contrVal = await fn(trial);

      if (contrVal < worstVal) {
        acceptAndInsert(simplex, idx, worstIdx, trial, contrVal);
        iteration++;
        continue;
      }
    }

    // --- Shrink ---
    await shrinkSimplexAsync(simplex, idx, idx[0], s.shrink!, fn);
    sortIdx(idx, simplex);
    iteration++;
  }

  const finalBestIdx = idx[0];
  const finalVal = simplex[finalBestIdx].value;
  while (costLen < iteration) costHistory[costLen++] = finalVal;

  return {
    point: simplex[finalBestIdx].point,
    value: finalVal,
    iterations: iteration,
    converged,
    costHistory: costHistory.subarray(0, costLen),
  };
}
