// Async-form prototype ("New Grit issue") — the three async needs of property-driven forms:
// 1) async FK lookup: project via ui.typeAhead's callback source + a full-picker icon;
// 2) server-provided choices: assignee from the user list, priority from the schema manifest;
// 3) async server validation: debounced issue-number uniqueness probe marks the field BEFORE
//    save, and a rejected insert maps per-column server errors back onto the named inputs.
// In a package, use the typed `gritDb` clients generated by `grok api` (Grit/src/generated/db.ts).

const projects = grok.dapi.domains.table('grit.project');
const issues = grok.dapi.domains.table('grit.issue');

// per-field validation slots: async probes and server rejections feed sync validators
const fieldErrors = {};

// 1) async FK lookup (RefInput prototype): suggestions from a server query as you type
let project = null;
const projectInput = ui.typeAhead('Project', {
  minLength: 1,
  source: async (q) => (await projects.query().where('key', '~*', q).top(10)) // ~* = case-insensitive match
    .map((p) => ({label: `${p.key} — ${p.name}`, value: p})),
  onSubmit: async (_, item) => {
    project = item.value;
    delete fieldErrors.project_id;
    projectInput.validate();
    const [last] = await issues.query() // suggest the next free number in the picked project
      .where('project_id', '=', project.id).orderBy('number', true).top(1);
    numberInput.value = (last?.number ?? 0) + 1;
    probeNumber();
  },
});
// full picker: the platform's own lookup dialog — the target table's Domain View
// with search and single select, resolving to the picked row (null on cancel)
projectInput.addOptions(ui.icons.search(async () => {
  const picked = await DG.DomainObjectHandler.pickRow('grit.project');
  if (picked == null)
    return;
  project = picked.values;
  projectInput.value = `${project.key} — ${project.name}`;
  delete fieldErrors.project_id;
  projectInput.validate();
}, 'Pick a project'));
// project_id is required — a nullable ref would also get ui.icons.close(() => {...}) to clear the value

// 2) server-provided choices: assignee loads async (disabled until then); priority choices
//    come from the schema manifest — the same property vocabulary the server enforces
let users = [];
const assigneeInput = ui.input.choice('Assignee', {items: []});
assigneeInput.enabled = false;
grok.dapi.users.list().then((list) => {
  users = list;
  assigneeInput.items = ['', ...users.map((u) => u.friendlyName)];
  assigneeInput.enabled = true;
});
const priorityCol = (await grok.dapi.domains.schema('grit').manifest()).tables.issue.columns.priority;
const priorityInput = ui.input.choice('Priority', {items: priorityCol.choices, value: priorityCol.default});

// 3) async server validation: debounced uniqueness probe → sync validator slot → validate()
const numberInput = ui.input.int('Number');
const titleInput = ui.input.string('Title');
projectInput.addValidator(() => fieldErrors.project_id ?? null);
numberInput.addValidator(() => fieldErrors.number ?? null);
titleInput.addValidator(() => fieldErrors.title ?? null);

let probeTimer = null;
async function probeNumber() {
  const n = numberInput.value;
  if (project == null || n == null)
    return;
  const taken = await issues.query().where({project_id: project.id, number: n}).exists();
  if (n !== numberInput.value)
    return; // stale probe
  if (taken)
    fieldErrors.number = `${project.key}-${n} already exists — pick another number`;
  else
    delete fieldErrors.number;
  numberInput.validate();
}
numberInput.onInput.subscribe(() => {
  delete fieldErrors.number;
  clearTimeout(probeTimer);
  probeTimer = setTimeout(probeNumber, 300);
});
titleInput.onInput.subscribe(() => { delete fieldErrors.title; titleInput.validate(); });

const saveButton = ui.bigButton('Save', async () => {
  if (project == null || !titleInput.value) {
    fieldErrors.project_id = project == null ? 'Pick a project' : undefined;
    fieldErrors.title = titleInput.value ? undefined : 'Title is required';
    projectInput.validate();
    titleInput.validate();
    return;
  }
  try {
    const [res] = await issues.insert({
      project_id: project.id,
      number: numberInput.value,
      title: titleInput.value,
      priority: priorityInput.value ?? undefined,
      assignee: users.find((u) => u.friendlyName === assigneeInput.value)?.id,
    }, {errorOnDuplicate: true});
    grok.shell.info(`Created ${project.key}-${numberInput.value} (id ${res.id})`);
  }
  catch (e) {
    if (!(e instanceof DG.DomainValidationError))
      throw e;
    // the standard round-trip: per-column server errors land on the named inputs
    const inputs = {project_id: projectInput, number: numberInput, title: titleInput,
      priority: priorityInput, assignee: assigneeInput};
    for (const row of e.rows)
      for (const err of row.errors ?? []) {
        if (inputs[err.column] == null) { grok.shell.error(err.message); continue; } // cross-field → banner
        fieldErrors[err.column] = err.message;
        inputs[err.column].validate();
      }
    if (e.isDuplicate && fieldErrors.number == null) {
      fieldErrors.number = 'Issue number already exists in this project';
      numberInput.validate();
    }
  }
});

grok.shell.newView('New Grit issue', [
  ui.inputs([projectInput, numberInput, titleInput, priorityInput, assigneeInput]),
  saveButton,
]);
