/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace scripts {
  /**
  ETL process for Revvity Signals data - exports libraries, processes CSV files, and prepares data for MolTrack
  */
  export async function revvityETL(): Promise<DG.DataFrame> {
    return await grok.functions.call('RevvitySignalsLink:RevvityETL', {});
  }
}

export namespace funcs {
  export async function init(): Promise<void> {
    return await grok.functions.call('RevvitySignalsLink:Init', {});
  }

  export async function revvitySignalsLinkApp(path?: string ): Promise<DG.View> {
    return await grok.functions.call('RevvitySignalsLink:RevvitySignalsLinkApp', { path });
  }

  export async function revvitySignalsLinkAppTreeBrowser(treeNode: any , browseView: DG.View ): Promise<void> {
    return await grok.functions.call('RevvitySignalsLink:RevvitySignalsLinkAppTreeBrowser', { treeNode, browseView });
  }

  export async function searchEntities(query: string , params: string , libId: string , entityType: string ): Promise<DG.DataFrame> {
    return await grok.functions.call('RevvitySignalsLink:SearchEntities', { query, params, libId, entityType });
  }

  export async function searchEntitiesWithStructures(query: string , params: string , libId: string , entityType: string , doNotAddStructures?: boolean ): Promise<DG.DataFrame> {
    return await grok.functions.call('RevvitySignalsLink:SearchEntitiesWithStructures', { query, params, libId, entityType, doNotAddStructures });
  }

  export async function getUsers(): Promise<string> {
    return await grok.functions.call('RevvitySignalsLink:GetUsers', {});
  }

  export async function getLibraries(): Promise<string> {
    return await grok.functions.call('RevvitySignalsLink:GetLibraries', {});
  }

  export async function registerRevvityIdsFormats(): Promise<void> {
    return await grok.functions.call('RevvitySignalsLink:RegisterRevvityIdsFormats', {});
  }

  export async function getTags(type: string , assetTypeId: string ): Promise<string> {
    return await grok.functions.call('RevvitySignalsLink:GetTags', { type, assetTypeId });
  }

  export async function searchTerms(query: string ): Promise<string> {
    return await grok.functions.call('RevvitySignalsLink:SearchTerms', { query });
  }

  export async function getTermsForField(fieldName: string , type: string , assetTypeId: string , isMaterial: boolean ): Promise<any> {
    return await grok.functions.call('RevvitySignalsLink:GetTermsForField', { fieldName, type, assetTypeId, isMaterial });
  }

  export async function getStructureById(id: string ): Promise<string> {
    return await grok.functions.call('RevvitySignalsLink:GetStructureById', { id });
  }

  export async function entityTreeWidget(id: any ): Promise<any> {
    return await grok.functions.call('RevvitySignalsLink:EntityTreeWidget', { id });
  }

  export async function revvityLabelWidget(id: any ): Promise<any> {
    return await grok.functions.call('RevvitySignalsLink:RevvityLabelWidget', { id });
  }
}
