-- Domain schema grit: 2.0.0 -> 2.1.0
-- ems-migration: from=7597582b0485e715a35b205172812800a0dcce0a066742905d429418c344b969 to=679c60dfc21d72db793736248aa1641baa8663b945b3ea8950f54efbee21ab4c
-- Generated by the schema snapshot tool from snapshot 7597582b0485 to 679c60dfc21d.
-- Registry-only changes (no SQL; converged by the next registration):
--   * column-meta issue.number: description "Per-project issue number; assigned by the app" -> "Per-project issue number; assigned by the engine", immutable (none) -> true

-- change-required issue.number: required true -> false [manual]
ALTER TABLE grit.issue ALTER COLUMN number DROP NOT NULL;

-- change-auto-number issue.number: autoNumber (none) -> {"scope":"project_id"} [manual]
CREATE UNIQUE INDEX IF NOT EXISTS ux_issue_number ON grit.issue (project_id, number);
INSERT INTO public.domain_counters (table_id, scope_id, last) SELECT (SELECT t.id FROM domain_tables t JOIN domain_schemas s ON s.id = t.schema_id WHERE s.name = 'grit' AND t.name = 'issue'), project_id, max(number) FROM grit.issue WHERE number IS NOT NULL GROUP BY 2 ON CONFLICT (table_id, scope_id) DO UPDATE SET last = GREATEST(domain_counters.last, excluded.last);
