CREATE TABLE NUMERIC_DATA (
    data NUMERIC
);

CREATE TABLE DOUBLES (
    data DOUBLE PRECISION
);

CREATE TABLE REALS (
    data REAL
);

CREATE TABLE BIGINT_DATA (
    data BIGINT
);

CREATE TABLE NUMERIC_DATA_PRECISION (
    data NUMERIC(5)
);

CREATE TABLE NUMERIC_DATA_PRECISION_SCALE (
    data NUMERIC(4, 2)
);

INSERT INTO NUMERIC_DATA_PRECISION (data) VALUES (2.2221);
INSERT INTO NUMERIC_DATA_PRECISION (data) VALUES (2222.2);

INSERT INTO NUMERIC_DATA_PRECISION_SCALE (data) VALUES (22.22);
INSERT INTO NUMERIC_DATA_PRECISION_SCALE (data) VALUES (55.55);

INSERT INTO BIGINT_DATA (data) VALUES (-9223372036854775808); -- min value for big int
INSERT INTO BIGINT_DATA (data) VALUES (9223372036854775807); -- max value for big int

INSERT INTO REALS (data) VALUES (1E-37); -- min value for real
INSERT INTO REALS (data) VALUES (1E+37); -- max value for float

INSERT INTO DOUBLES (data) VALUES ('-Infinity'::float); --edge case
INSERT INTO DOUBLES (data) VALUES ('+Infinity'::float); ----edge case
INSERT INTO DOUBLES (data) VALUES (1E-307); -- close zero value
INSERT INTO DOUBLES (data) VALUES (1E+308); -- max value for double

INSERT INTO NUMERIC_DATA (data) VALUES ('NaN'::numeric); --edge case
INSERT INTO NUMERIC_DATA (data) VALUES (2.22222222222);
INSERT INTO NUMERIC_DATA (data) VALUES (222222222222222222.2);
