CREATE TABLE CARS_SMALL (
    id SMALLSERIAL PRIMARY KEY,
    brand VARCHAR NOT NULL
);

CREATE TABLE CARS (
    id SERIAL PRIMARY KEY,
    brand VARCHAR NOT NULL
);

CREATE TABLE CARS_BIG (
    id BIGSERIAL PRIMARY KEY,
    brand VARCHAR NOT NULL
);

INSERT INTO CARS_SMALL(brand)
VALUES('Fiat');

INSERT INTO CARS_SMALL(id, brand)
VALUES(DEFAULT, 'Honda');

INSERT INTO CARS(brand)
VALUES('Fiat');

INSERT INTO CARS(id, brand)
VALUES(DEFAULT, 'Honda');

INSERT INTO CARS_BIG(brand)
VALUES('Fiat');

INSERT INTO CARS_BIG(id, brand)
VALUES(DEFAULT, 'Honda');