/** Functions that survive the structural/role/tag filters but are still not
 *  usable as Flow pipeline nodes — cluttering the toolbox. This is a curated
 *  **denylist keyed by `Func.nqName`** (namespace-qualified, e.g. `Chem:foo`),
 *  looked up as a Set in `shouldExcludeFunc`.
 *
 *  It was produced empirically: the real catalog on a live server was dumped,
 *  then each surviving function was assessed (by signature + package source)
 *  against "can a scientist wire this into a data pipeline?". Everything here
 *  is one of:
 *    - an internal engine/helper returning an `object`/handle/model/`dynamic`
 *      that no downstream node can consume (module accessors, fingerprint /
 *      embedding / matrix getters, lib/helper getters, config-list getters);
 *    - an internal near-duplicate of a user-facing function — the canonical
 *      twin is kept (e.g. `Chem:getInchis` over `Chem:addInchisTopMenu`,
 *      `Eda:apply*` over `Eda:train*`, `Chembl:ChemblMolregNoBySmiles` over
 *      `Chembl:chemblMolregno`);
 *    - a right-click / menu / dialog / editor action (empty output, mutates UI);
 *    - a demo / test / autocomplete-suggestion / unit-test helper;
 *    - state/plumbing RPCs (campaign locks, project caches).
 *
 *  Whole categories (panels, widgets, sketchers, cell renderers, file handlers,
 *  `semantic_value` right-click actions, filter-DSL builders, `Internal`/
 *  `@editors`-tagged funcs) are handled *generically* in `shouldExcludeFunc`
 *  (role+tag and signature rules) — those are deliberately NOT repeated here, so
 *  this list stays focused on the case-by-case judgement calls. Edit freely:
 *  add an nqName to hide a function, remove one to surface it. */
export const EXCLUDED_FUNC_NQNAMES: ReadonlySet<string> = new Set<string>([
  // (core) — platform plumbing / entity management / UI builders that survive the
  // structural rules but are not pipeline steps a scientist would chain:
  //   plumbing/entities: CallQuery, Convert*ToFunc, CreateViewer, Db(Scalar)Query,
  //     Drop*Cache, HttpPost, IndexFiles, Job, Open{Folder,Project,ServerFile},
  //     Project, Publish(Table), Show size, BatchCall, ApplyNotebook, Admin:MyDemo;
  //   widget chrome / UI builders: FilesWidget, FunctionsWidget, NotificationsWidget,
  //     Radio, TabControl(_AddPane), Accordion.
  'Admin:MyDemo',
  'core:Accordion',
  'core:ApplyNotebook',
  'core:BatchCall',
  'core:CallQuery',
  'core:ConvertDbTableToFunc',
  'core:ConvertFileInfoToFunc',
  'core:CreateViewer',
  'core:DbQuery',
  'core:DbScalarQuery',
  'core:DropConnectionCache',
  'core:DropFuncCache',
  'core:DropQueryCache',
  'core:FilesWidget',
  'core:FunctionsWidget',
  'core:HttpPost',
  'core:IndexFiles',
  'core:Job',
  'core:NotificationsWidget',
  'core:OpenFolder',
  'core:OpenProject',
  'core:OpenServerFile',
  'core:Project',
  'core:Publish',
  'core:PublishTable',
  'core:Radio',
  'core:Show size',
  'core:TabControl',
  'core:TabControl_AddPane',
  'core:AddPropertiesColumn',
  'core:ColumnGridWidget',
  'core:FilterToColumn',
  // Admetica
  'Admetica:admeticaHT',
  'Admetica:admeticaMenu',
  'Admetica:getModels',
  // Bio
  'Bio:MolToHelmConverterPy',
  'Bio:SequenceGenerator_1',
  'Bio:SubsequenceSearchTopMenu',
  'Bio:activityCliffs',
  'Bio:addCopyMenu',
  'Bio:alignSequences',
  'Bio:getMolFromHelm',
  'Bio:bioSubstructureFilterTest',
  'Bio:convertColumnAction',
  'Bio:detectMacromoleculeEnableStore',
  'Bio:detectMacromoleculeProbe',
  'Bio:getBioLib',
  'Bio:getHelmMonomers',
  'Bio:getMonomerLibHelper',
  'Bio:getRegion',
  'Bio:getSeqHandler',
  'Bio:getSeqHelper',
  'Bio:helmPreprocessingFunction',
  'Bio:macromoleculePreprocessingFunction',
  'Bio:matchWithMonomerLibrary',
  'Bio:sdfToJsonLib',
  'Bio:seqActivityCliffsInitFunction',
  'Bio:seqActivityCliffsTransform',
  'Bio:sequenceAlignment',
  'Bio:toAtomicLevelAction',
  // Bionemo
  'Bionemo:diffDockModel',
  'Bionemo:esmFoldModel',
  'Bionemo:getTargetFiles',
  // BiostructureViewer
  'BiostructureViewer:biostructureDataToJson',
  'BiostructureViewer:copyRawBiostructureValue',
  'BiostructureViewer:downloadRawBiostructureValue',
  'BiostructureViewer:getNglGlService',
  'BiostructureViewer:getPdbHelper',
  'BiostructureViewer:mol3dAtomPickerLinkWidget',
  'BiostructureViewer:openPdbResidues',
  'BiostructureViewer:openTableResiduesMenuItem',
  'BiostructureViewer:showBiostructureViewerMenuItem',
  'BiostructureViewer:showNglViewerMenuItem',
  // Chem — heavy analyses / dialogs / scripts that need their own app UI or a
  // FuncCall, not a pipeline node (from docs/things-to-do-with-functions.md):
  'Chem:AmideReaction',
  'Chem:Desc',
  'Chem:FindMCS',
  'Chem:FindRGroups',
  'Chem:FindRGroupsWithCore',
  'Chem:GenerateScaffoldTree',
  'Chem:SimilarityMapsUsingFingerprints',
  'Chem:activityCliffs',
  'Chem:applyChemprop',
  'Chem:callChemDiversitySearch',
  'Chem:callChemSimilaritySearch',
  'Chem:getDescriptors',
  'Chem:getProperties',
  'Chem:getToxicityRisks',
  'Chem:mmpAnalysis',
  'Chem:mpoCalculate',
  'Chem:rGroupDecomposition',
  'Chem:searchSubstructure',
  'Chem:trainChemprop',
  // Chem
  'Chem:SubstructureSearchTopMenu',
  'Chem:activityCliffsInitFunction',
  'Chem:activityCliffsTransform',
  'Chem:addInchisKeysTopMenu',
  'Chem:addInchisTopMenu',
  'Chem:beautifyMols',
  'Chem:calculateDescriptorsTransform',
  'Chem:canvasMol',
  'Chem:chemDescriptors',
  'Chem:chemDescriptorsTree',
  'Chem:convertMixtureToSmiles',
  'Chem:convertMolNotationAction',
  'Chem:convertMoleculeNotation',
  'Chem:convertToV3KViaOCL',
  'Chem:detectSmiles',
  'Chem:drawMolecule',
  'Chem:elementalAnalysis',
  'Chem:getChemPropertyFunction',
  'Chem:getChemSimilaritiesMatrix',
  'Chem:getChemSpaceEmbeddings',
  'Chem:getFingerprints',
  'Chem:getMolFileHandler',
  'Chem:getMorganFingerprint',
  'Chem:getRdKitModule',
  'Chem:getScaffoldTree',
  'Chem:getStructuralAlerts',
  'Chem:getMapIdentifiers',
  'Chem:getSynthonSpacesFunc',
  'Chem:isApplicableNN',
  'Chem:isInteractiveNN',
  'Chem:mapIdentifiersTransform',
  'Chem:mpoProfilesAppTreeBrowser',
  'Chem:mpoTransformFunction',
  'Chem:performClusterMCS',
  'Chem:rdKitCellRenderer',
  'Chem:removeDuplicates',
  'Chem:runPharmacophoreFeatures',
  'Chem:runStructuralAlerts',
  'Chem:validateMolecule',
  // Chembl
  'Chembl:AssayTypes',
  'Chembl:CompoundNames',
  'Chembl:Organisms',
  'Chembl:ProteinTypes',
  'Chembl:RelationshipTypes',
  'Chembl:TargetTypes',
  'Chembl:UnichemUnitTestQuery',
  'Chembl:chemblMolregno',
  // ChemblApi
  'ChemblApi:chemblSimilaritySearchPanel',
  'ChemblApi:chemblSubstructureSearchPanel',
  'ChemblApi:getCompoundsIds',
  // Chemspace
  'Chemspace:getChemspaceIds',
  'Chemspace:getChemspacePrices',
  'Chemspace:pricesPanel',
  'Chemspace:samplesPanel',
  // ClinicalCase
  'ClinicalCase:Covariates',
  'ClinicalCase:SurvivalPlot',
  // Curves
  'Curves:addAggrStatisticsColumn',
  'Curves:addStatisticsColumn',
  'Curves:dataToCurves',
  // Dendrogram
  'Dendrogram:HierarchicalClusteringByDistanceScript',
  'Dendrogram:HierarchicalClusteringScript',
  'Dendrogram:getDendrogramService',
  'Dendrogram:getTreeHelper',
  'Dendrogram:hierarchicalClustering',
  // DiffStudio
  'DiffStudio:serializeEquations',
  // Docking
  'Docking:getAutoDockService',
  'Docking:getAutodockResults',
  'Docking:getConfigFiles',
  'Docking:runAutodock',
  // Eda
  'Eda:dbscanPostProcessingFunction',
  'Eda:getPmpoAppItems',
  'Eda:isApplicableLinearKernelSVM',
  'Eda:isApplicableLinearRegression',
  'Eda:isApplicablePLSRegression',
  'Eda:isApplicablePolynomialKernelSVM',
  'Eda:isApplicableRBFkernelSVM',
  'Eda:isApplicableSigmoidKernelSVM',
  'Eda:isApplicableSoftmax',
  'Eda:isApplicableXGBooster',
  'Eda:isInteractiveLinearKernelSVM',
  'Eda:isInteractiveLinearRegression',
  'Eda:isInteractivePLSRegression',
  'Eda:isInteractivePolynomialKernelSVM',
  'Eda:isInteractiveRBFkernelSVM',
  'Eda:isInteractiveSigmoidKernelSVM',
  'Eda:isInteractiveSoftmax',
  'Eda:isInteractiveXGBooster',
  'Eda:numberPreprocessingFunction',
  'Eda:stringPreprocessingFunction',
  'Eda:trainLinearKernelSVM',
  'Eda:trainLinearRegression',
  'Eda:trainPLSRegression',
  'Eda:trainPolynomialKernelSVM',
  'Eda:trainRBFkernelSVM',
  'Eda:trainSigmoidKernelSVM',
  'Eda:trainSoftmax',
  'Eda:trainXGBooster',
  'Eda:visualizeLinearKernelSVM',
  'Eda:visualizePLSRegression',
  'Eda:visualizePolynomialKernelSVM',
  'Eda:visualizeRBFkernelSVM',
  'Eda:visualizeSigmoidKernelSVM',
  // Helm
  'Helm:getHelmHelper',
  'Helm:getMolfiles',
  'Helm:helmAsync',
  // HitTriage
  'HitTriage:AcquireCampaignLock',
  'HitTriage:GetLastModified',
  'HitTriage:ReleaseCampaignLock',
  'HitTriage:demoFileIngest',
  'HitTriage:demoFileIngest1',
  'HitTriage:demoFileIngest2',
  'HitTriage:demoFileSubmit',
  'HitTriage:demoPeptideSequences',
  // Jiraconnect
  'Jiraconnect:getJiraField',
  'Jiraconnect:getJiraTicketsByFilter',
  'Jiraconnect:issueData',
  'Jiraconnect:projectData',
  'Jiraconnect:projectsList',
  // OligoBatchCalculator
  'OligoBatchCalculator:getUnits',
  // PhyloTreeViewer
  'PhyloTreeViewer:getPhylocanvasGlService',
  'PhyloTreeViewer:injectTreeToGrid',
  'PhyloTreeViewer:treeToGridApp',
  // PowerGrid
  'PowerGrid:addFormColumn',
  'PowerGrid:addPinnedColumn',
  'PowerGrid:summarizeColumns',
  // PowerPack
  'PowerPack:formulaLinesDialog',
  'PowerPack:getFuncTableViewWidget',
  'PowerPack:htmlWidget',
  'PowerPack:isFormulaColumn',
  'PowerPack:kpiWidget',
  'PowerPack:webWidget',
  // Proteomics
  'Proteomics:NumberAntibodySequencesAbNumber',
  'Proteomics:NumberAntibodySequencesANARCI',
  // PubchemApi
  'PubchemApi:pubChemIdentitySearch',
  'PubchemApi:pubChemSimilaritySearchPanel',
  'PubchemApi:pubChemSubstructureSearchPanel',
  // Pyodide
  'Pyodide:DataFrameInputCallJS',
  'Pyodide:DataFrameInputCallPy',
  'Pyodide:DatetimeInputCallJS',
  'Pyodide:DatetimeInputCallPy',
  'Pyodide:DatetimeTestJS',
  'Pyodide:DatetimeTestPy',
  'Pyodide:EditDFJS',
  'Pyodide:EditDFPy',
  'Pyodide:PyodideBlobInputOutput',
  'Pyodide:PyodideCalcColumnCall',
  'Pyodide:PyodideColumnList',
  'Pyodide:PyodideDate',
  'Pyodide:PyodideEmptyDataframe',
  'Pyodide:PyodideGraphics',
  'Pyodide:PyodideMap',
  'Pyodide:PyodideSingleDf',
  'Pyodide:expectDate',
  'Pyodide:expectTable',
  'Pyodide:makeVectorCode',
  // SequenceTranslator
  'SequenceTranslator:applyNotationProviderForCyclized',
  'SequenceTranslator:createMonomerLibraryForPolyTool',
  'SequenceTranslator:getCodeToWeightsMap',
  'SequenceTranslator:getPtChemEnumeratorDialog',
  'SequenceTranslator:getPtHelmEnumeratorDialog',
  'SequenceTranslator:getPtOligoEnumeratorDialog',
  'SequenceTranslator:getTranslationHelper',
  'SequenceTranslator:linkStrands',
  'SequenceTranslator:polyToolColumnChoice',
  'SequenceTranslator:polyToolConvert2',
]);
