/** The Flow toolbox allowlist by `Func.nqName` (see `shouldIncludeFunc` for the other inclusion routes).
 *  For a function you own, prefer declaring `meta.includeInFlow: true` instead of editing this. */
export const INCLUDED_FUNC_NQNAMES: ReadonlySet<string> = new Set<string>([
  // core
  'core:AddNewColumn',
  'core:AddNewColumnList',
  // 'core:AddStickyPropertiesColumns',
  // 'core:Aggregate',
  'core:AppendTables',
  // 'core:ApplyModel',
  // 'core:BinByDateTime',
  // 'core:BinBySpecificLimits',
  'core:ChangeColumnsType',
  'core:ChangeType',
  'core:CloneColumn',
  'core:CloneTable',
  // 'core:Cluster',
  // 'core:CompareTables',
  // 'core:Date',
  // 'core:DateAdd',
  // 'core:DateDiff',
  // 'core:DateDifference',
  // 'core:DateDifferenceWithColumn',
  // 'core:DateFromUnixTimestamp',
  // 'core:DateNow',
  'core:DateParse',
  // 'core:DateTime',
  'core:DayOfMonth',
  'core:DayOfWeek',
  'core:DayOfYear',
  // 'core:DeleteColumns',
  // 'core:DeleteRows',
  'core:ExtractColumns',
  'core:ExtractNumbers',
  // 'core:ExtractRows',
  'core:ExtractValue',
  // 'core:FilterRows',
  // 'core:FormatColumns',
  // 'core:GetColumn',
  'core:GetTable',
  // 'core:Hour',
  'core:InsertRows',
  'core:InvertSelection',
  'core:JoinTables',
  // 'core:KeepColumns',
  // 'core:KeepRows',
  // 'core:KSTest',
  'core:LinkTables',
  // 'core:Millisecond',
  // 'core:Minute',
  // 'core:MissingValuesImputation',
  'core:Month',
  'core:Normalize',
  'core:OpenFile',
  'core:OpenTable',
  'core:ParseQnum',
  // 'core:PCA',
  'core:Percentile',
  'core:Qnum',
  'core:Quarter',
  // 'core:RandomData',
  'core:RenameColumn',
  'core:ReplaceValues',
  // 'core:RoundNumbers',
  // 'core:SaveAsColumn',
  // 'core:Second',
  'core:SelectAll',
  // 'core:SelectCols',
  'core:SelectionToColumn',
  'core:SelectNone',
  // 'core:SelectRows',
  'core:SplitByRegExp',
  'core:SplitColumn',
  // 'core:Subset',
  // 'core:TagColumns',
  'core:Time',
  'core:TimeParse',
  'core:Today',
  // 'core:TransformString',
  'core:TTest',
  'core:UnixTimestamp',
  'core:Unpivot',
  'core:Weeknum',
  'core:Year',
  // Admetica
  // 'Admetica:run_admetica',
  'Admetica:getAdmeProperties',
  // Bio
  'Bio:applyAntibodyNumbering',
  'Bio:convertNotation',
  'Bio:extractRegion',
  // NB not `SequenceGenerator` — the parameterless sequence_generator.md doc entity registers under that name.
  'Bio:GenerateSequences',
  // 'Bio:getRegionTopMenu',        → Bio:extractRegion (returns the column)
  // 'Bio:immunumAntibodyNumbering' → Bio:applyAntibodyNumbering
  // 'Bio:moleculesToHelmTopMenu'   → Bio:moleculesToHelmColumn
  'Bio:moleculesToHelmColumn',
  'Bio:motifSearch',
  'Bio:pepseaMsa',
  'Bio:sequenceIdentityScoring',
  'Bio:sequenceSimilarityScoring',
  // 'Bio:splitToMonomersTopMenu'   → Bio:splitToMonomersColumns
  'Bio:splitToMonomersColumns',
  'Bio:tagAsMacromolecule',
  // 'Bio:toAtomicLevel'            → Bio:toAtomicLevelColumn
  'Bio:toAtomicLevelColumn',
  'Bio:toAtomicLevelSingleSeq',
  // Bionemo
  // 'Bionemo:DiffdockPython',
  // BiostructureViewer
  'BiostructureViewer:fetchSequencesFromPdb',
  'BiostructureViewer:importPdb',
  'BiostructureViewer:importPdbqt',
  'BiostructureViewer:importWithNgl',
  'BiostructureViewer:importXYZ',
  'BiostructureViewer:ProteinLigandInteractionDiagram',
  // Chem
  'Chem:addChemPropertiesColumns',
  'Chem:addChemRisksColumns',
  'Chem:addInchisKeysTopMenu',
  'Chem:addInchisTopMenu',
  'Chem:applyReaction',
  'Chem:bitbirchClusteringTopMenu',
  'Chem:ButinaMoleculesClustering',
  'Chem:CalculateLogD',
  'Chem:CalculateLogP',
  'Chem:CalculateLogS',
  'Chem:CalculatePI',
  'Chem:CalculatePKa',
  'Chem:callChemSimilaritySearch',
  // 'Chem:ChemicalSpaceUsingTSNE',
  // 'Chem:ChemicalSpaceUsingUMAP',
  'Chem:chemSpaceColumns',
  'Chem:clusterMCSTopMenu',
  'Chem:convertNotation',
  'Chem:Curate',
  'Chem:deprotect',
  'Chem:descriptorsDocker',
  'Chem:diverseSubset',
  'Chem:FilterByCatalogs',
  'Chem:filterBySubstructure',
  // 'Chem:findSimilar',  → superseded by Chem:callChemSimilaritySearch
  'Chem:GenerateConformers',
  // 'Chem:getDiversities',      → Chem:diverseSubset
  // 'Chem:getSimilarities',     → Chem:similarityTo
  // 'Chem:searchSubstructure',  → Chem:filterBySubstructure
  // 'Chem:getInchiKeys',  → superseded by Chem:addInchisKeysTopMenu
  // 'Chem:getInchis',     → superseded by Chem:addInchisTopMenu
  // 'Chem:getMorganFingerprints',
  // 'Chem:importMol',
  // 'Chem:importMol2',
  // 'Chem:importSdf',
  // 'Chem:importSmi',
  'Chem:mpoScoreByProfile',
  'Chem:MurckoScaffolds',
  'Chem:Mutate',
  'Chem:namesToSmiles',
  'Chem:pharmacophoreFeaturesTopMenu',
  'Chem:recalculateCoords',
  'Chem:removeWaterAndSaltsTopMenu',
  'Chem:runElementalAnalysis',
  'Chem:similarityMatrixTopMenu',
  'Chem:similarityTo',
  'Chem:structuralAlertsTopMenu',
  // 'Chem:SynthonSearch',
  // 'Chem:synthonSearchFunc',
  'Chem:toSdf',
  'Chem:TwoComponentReaction',
  // 'Chem:USRCAT',
  // Chembl
  'Chembl:getChemblCompounds',
  'Chembl:getChemblCompoundsByOrganism',
  // ChemblApi
  // 'ChemblApi:chemblSearchWidget',
  'ChemblApi:getById',
  // Chemspace
  'Chemspace:getChemspaceIds',
  'Chemspace:getChemspacePrices',
  // Curves
  'Curves:addAggrCurveStatistic',
  'Curves:addCurveStatistic',
  'Curves:CalculateMSR',
  'Curves:dataToCurves',
  'Curves:pzfxFileHandler',
  // DiffStudio
  'DiffStudio:ballFlight',
  'DiffStudio:ivpModel_Acid_Production',
  'DiffStudio:ivpModel_Bioreactor',
  'DiffStudio:ivpModel_PK_PD',
  'DiffStudio:ivpModel_Pollution',
  'DiffStudio:solve',
  'DiffStudio:solveEquations',
  'DiffStudio:solveODE',
  // Eda
  // 'Eda:applyLinearKernelSVM',
  // 'Eda:applyLinearRegression',
  // 'Eda:applyPLSRegression',
  // 'Eda:applyPolynomialKernelSVM',
  // 'Eda:applyRBFkernelSVM',
  // 'Eda:applySigmoidKernelSVM',
  // 'Eda:applySoftmax',
  // 'Eda:applyXGBooster',
  'Eda:dbScan',
  'Eda:generatePmpoDataset',
  'Eda:kNNImputationForTable',
  'Eda:MCLClustering',
  'Eda:PCA',
  'Eda:PLS',
  // FileEditors
  // 'FileEditors:viewDocx',
  // 'FileEditors:viewPdf',
  // Proteomics
  'Proteomics:DeqmsDE',
  'Proteomics:LimmaDE',
  'Proteomics:VsnNormalize',
  // SequenceTranslator
  'SequenceTranslator:combineSenseAntisenseToOligoNucleotide',
  'SequenceTranslator:convertHelmToOligoNucleotide',
  'SequenceTranslator:enumerateSingleHelmSequence',
  'SequenceTranslator:enumerateSingleHelmSequenceWithNaturalAAs',
  // Sequenceutils
  'Sequenceutils:helmMsa',
  // Surechembl
  'Surechembl:sureChemblSimilaritySearch',
  'Surechembl:sureChemblSubstructureSearch',]);
