import {STRAND, TERMINUS, STRAND_END} from '../../model/const';

export const LEGEND_PADDING = 20;

export const enum LUMINANCE_COEFFICIENTS {
  RED = 0.299,
  GREEN = 0.587,
  BLUE = 0.114,
  THRESHOLD = 186,
};

export const enum TEXT_COLOR {
  DARK = '#333333',
  LIGHT = '#ffffff',
};

export const enum SVG_CIRCLE_SIZES {
  NUCLEOBASE_RADIUS = 15,
  NUCLEOBASE_DIAMETER = 2 * NUCLEOBASE_RADIUS,
  LEGEND_RADIUS = 6,
  LINKAGE_STAR_RADIUS = 5,
};

export const enum SVG_TEXT_FONT_SIZES {
  NUCLEOBASE = 17,
  COMMENT = 15,
  MODIFICATION_LABEL = 11,
};

export const enum SVG_ELEMENT_COLORS {
  LINKAGE_STAR = 'red',
  TEXT = 'var(--grey-6)',
  TITLE_TEXT = 'black',
  MODIFICATION_TEXT = 'red',
  MODIFICATION_LABEL = 'var(--grey-4)',
};

export const STRAND_END_LABEL_TEXT = {
  [STRAND_END.LEFT]: {
    [STRAND.SENSE]: `${STRAND.SENSE}: ${TERMINUS.FIVE_PRIME}`,
    [STRAND.ANTISENSE]: `${STRAND.ANTISENSE}: ${TERMINUS.THREE_PRIME}`,
  },
  [STRAND_END.RIGHT]: {
    [STRAND.SENSE]: `${TERMINUS.THREE_PRIME}`,
    [STRAND.ANTISENSE]: `${TERMINUS.FIVE_PRIME}`,
  }
} as const;

export const NUMERIC_LABEL_POSITION_OFFSET = {
  ONE_DIGIT: -5,
  TWO_DIGIT: -10,
} as const;

export const DEFAULT_FONT_FAMILY = 'Arial';

export const Y_POSITION_OFFSET = 15;

export const Y_POSITIONS_FOR_STRAND_ELEMENTS = {
  [STRAND.SENSE]: {
    NUMERIC_LABEL: 2 * SVG_CIRCLE_SIZES.NUCLEOBASE_RADIUS,
    NUCLEOBASE_CIRCLE: 3.5 * SVG_CIRCLE_SIZES.NUCLEOBASE_RADIUS,
    NUCLEOBASE_LABEL: 4 * SVG_CIRCLE_SIZES.NUCLEOBASE_RADIUS,
  },
  [STRAND.ANTISENSE]: {
    NUMERIC_LABEL: 8.5 * SVG_CIRCLE_SIZES.NUCLEOBASE_RADIUS,
    NUCLEOBASE_CIRCLE: 6.5 * SVG_CIRCLE_SIZES.NUCLEOBASE_RADIUS,
    NUCLEOBASE_LABEL: 7 * SVG_CIRCLE_SIZES.NUCLEOBASE_RADIUS,
  }
};

export const MIN_WIDTH = 200;

export const TITLE_SHIFT = 10;

export const enum FONT_SIZE {
  TITLE = 17,
  LEGEND = 14,
  NUCLEOBASE = 17,
  COMMENT = 14,
}

