/** Main FuncFlow view — Datagrok ViewBase that hosts the Rete editor.
 *
 * Layout: [function-browser]  |  [Rete canvas container]
 *                                  + status bar at the bottom
 *                                  (property panel goes into the native context panel)
 *
 * The canvas container is a plain `<div>`; the Rete `AreaPlugin` builds the
 * scrollable/zoomable inner content inside it. Drag-and-drop from the
 * Datagrok browse tree is bound to this div via `ui.makeDroppable`. */

import * as grok from 'datagrok-api/grok';
import * as ui from 'datagrok-api/ui';
import * as DG from 'datagrok-api/dg';

// @ts-ignore
import '../css/funcflow.css';

import {FlowEditor} from './rete/flow-editor';
import {FlowNode} from './rete/scheme';
import {FunctionBrowser, FF_DRAG_MIME} from './panel/function-browser';
import {PropertyPanel} from './panel/property-panel';
import {
  registerBuiltinNodes, registerAllFunctions, getRegisteredFuncs,
  createNode, FuncInfo,
} from './rete/node-factory';
import {validateGraph} from './compiler/validator';
import {emitScript} from './compiler/script-emitter';
import {
  serializeFlow, deserializeFlow, downloadFlow, loadFlowFromFile,
} from './serialization/flow-serializer';
import {FlowSettings} from './serialization/flow-schema';
import {ExecutionController} from './execution/execution-controller';
import {ValueSummary} from './execution/execution-state';
import {buildPreview} from './execution/value-inspector';

export class FuncFlowView extends DG.ViewBase {
  private flow!: FlowEditor;
  private functionBrowser!: FunctionBrowser;
  private propertyPanel!: PropertyPanel;
  private executionController!: ExecutionController;
  private canvasContainer!: HTMLElement;
  private statusBar!: HTMLElement;
  private nodeCountLabel!: HTMLElement;
  private linkCountLabel!: HTMLElement;
  private validationLabel!: HTMLElement;

  private flowSettings: FlowSettings = {
    scriptName: 'MyFuncFlow',
    scriptDescription: 'Generated by FuncFlow',
    tags: ['funcflow'],
  };

  constructor() {
    super();
    this.name = 'FuncFlow';

    registerBuiltinNodes();

    this.initUI();
    this.setupRibbon();
    this.setupStatusBar();

    // Browser lives in the platform toolbox window now — make sure both panels are visible.
    this.toolbox = this.functionBrowser.root;
    grok.shell.windows.showToolbox = true;
    grok.shell.windows.showContextPanel = true;

    setTimeout(() => {
      try {
        registerAllFunctions();
        this.functionBrowser.render();
      } catch (e) {
        console.warn('FuncFlow: error registering functions:', e);
      }
    }, 100);
  }

  private initUI(): void {
    this.functionBrowser = new FunctionBrowser({
      onFunctionDoubleClick: (info: FuncInfo) => void this.addNodeByType(info.nodeTypeName),
      onBuiltinNodeDoubleClick: (typeName: string) => void this.addNodeByType(typeName),
    });

    this.canvasContainer = ui.div([], 'funcflow-canvas-container');

    this.nodeCountLabel = ui.divText('Nodes: 0');
    this.linkCountLabel = ui.divText('Links: 0');
    this.validationLabel = ui.divText('');
    ui.tooltip.bind(this.nodeCountLabel, 'Total number of nodes in the graph');
    ui.tooltip.bind(this.linkCountLabel, 'Total number of connections between nodes');
    this.statusBar = ui.div(
      [this.nodeCountLabel, this.linkCountLabel, this.validationLabel],
      'funcflow-status-bar',
    );

    const mainLayout = ui.div([this.canvasContainer], 'funcflow-root');
    this.root.style.cssText = 'width:100%;height:100%;display:flex;flex-direction:column;';
    this.root.appendChild(mainLayout);
    this.root.appendChild(this.statusBar);
    mainLayout.style.flex = '1';
    mainLayout.style.overflow = 'hidden';

    this.setupFileDropTarget();
    this.installPortContextMenu();

    setTimeout(() => this.initEditor(), 50);
  }

  // ---------- per-port "View Output" preview (KNIME pattern #2) ----------

  /** Right-click on an output socket → menu with "View output" if a runtime
   *  value is captured for that port. The handler runs in capture phase so
   *  it intercepts the contextmenu before AreaPlugin emits its `'contextmenu'`
   *  signal (which would route to the node menu). */
  private installPortContextMenu(): void {
    this.canvasContainer.addEventListener('contextmenu', (ev) => {
      const target = ev.target as HTMLElement | null;
      // Suppress root menu on input sockets — there's no output value to
      // show, and without this we'd otherwise leak the "Add annotation
      // here" item from the area-plugin's container-level emission.
      if (target?.closest('.ff-socket-row-input')) {
        ev.preventDefault();
        ev.stopPropagation();
        return;
      }
      // Match anywhere in an output row — dot, wrapper, or label — so the
      // user doesn't have to right-click the 12px socket dot precisely.
      const rowEl = target?.closest('.ff-socket-row-output') as HTMLElement | null;
      if (!rowEl) return;
      const nodeEl = rowEl.closest('.ff-node') as HTMLElement | null;
      if (!nodeEl) return;
      const nodeId = nodeEl.dataset.nodeId;
      if (!nodeId) return;
      const node = this.flow?.getNodeById(nodeId);
      if (!node) return;
      // Output key by row index — same convention as the suggestion menu.
      const rows = Array.from(nodeEl.querySelectorAll('.ff-socket-row-output')) as HTMLElement[];
      const idx = rows.indexOf(rowEl);
      const outputKey = Object.keys(node.outputs)[idx];
      if (!outputKey) return;

      ev.preventDefault();
      ev.stopPropagation();

      const state = this.executionController?.state.getNodeState(nodeId);
      const summary = state?.outputs?.[outputKey];

      const menu = DG.Menu.popup();
      if (summary && this.isPortPreviewable(summary)) {
        menu.item('View output', () => this.showPortPreview(rowEl, outputKey, summary));
      } else {
        menu.item('No output captured yet', () => {});
      }
      menu.show({causedBy: ev});
    }, true);
  }

  private isPortPreviewable(summary: ValueSummary): boolean {
    if (summary.type === 'dataframe' && summary.clone) return true;
    if (summary.type === 'column' && Array.isArray(summary.sample) && summary.sample.length > 0) return true;
    if (summary.type === 'graphics' && typeof summary.value === 'string') return true;
    return false;
  }

  private currentPortPopup: HTMLElement | null = null;

  /** Floating popover anchored next to a port's screen position. Reuses the
   *  same `buildPreview` renderer the docked panel uses. Auto-closes on
   *  Esc or click-outside. */
  private showPortPreview(anchorEl: HTMLElement, name: string, summary: ValueSummary): void {
    if (this.currentPortPopup) this.currentPortPopup.remove();
    const inner = buildPreview(name, summary);
    if (!inner) return;

    const popup = ui.div([inner], 'ff-port-preview');
    document.body.appendChild(popup);
    this.currentPortPopup = popup;

    const rect = anchorEl.getBoundingClientRect();
    const popupRect = popup.getBoundingClientRect();
    const vw = window.innerWidth, vh = window.innerHeight;
    let left = rect.right + 12;
    if (left + popupRect.width > vw - 8) left = rect.left - popupRect.width - 12;
    if (left < 8) left = 8;
    let top = rect.top;
    if (top + popupRect.height > vh - 8) top = vh - popupRect.height - 8;
    if (top < 8) top = 8;
    popup.style.left = `${left}px`;
    popup.style.top = `${top}px`;

    const close = (): void => {
      popup.remove();
      this.currentPortPopup = null;
      document.removeEventListener('mousedown', onDoc, true);
      document.removeEventListener('keydown', onKey, true);
    };
    const onDoc = (ev: MouseEvent): void => {
      if (!popup.contains(ev.target as Node)) close();
    };
    const onKey = (ev: KeyboardEvent): void => {
      if (ev.key === 'Escape') close();
    };
    document.addEventListener('mousedown', onDoc, true);
    document.addEventListener('keydown', onKey, true);
  }

  private initEditor(): void {
    this.flow = new FlowEditor(this.canvasContainer, {
      onNodeSelected: (node: FlowNode) => {
        const execState = this.executionController?.state.getNodeState(node.id);
        this.propertyPanel.showNode(node, execState);
        grok.shell.o = this.propertyPanel.root;
        // Lazy: opens (or updates) the bottom-docked output panel only if
        // this node has captured runtime values from a prior run.
        this.executionController?.showOutputsForNode(node);
      },
      onNodeDeselected: () => {
        this.propertyPanel.clear();
        grok.shell.o = this.propertyPanel.root;
      },
      onGraphChanged: () => {
        this.updateStatusBar();
        this.executionController?.onGraphChanged();
      },
    });

    this.propertyPanel = new PropertyPanel(this.flow);
    this.executionController = new ExecutionController(this.flow);
    this.executionController.outputPreview.setViewRoot(this.root);
    this.executionController.onBreakpointHit = () => {
      grok.shell.info('Breakpoint hit — click Continue in the ribbon to resume');
    };
    this.executionController.onRunEnd = (success: boolean) => {
      if (!success) return;
      grok.shell.info('Flow execution completed');
      // Land the user on the first output node — selecting it opens the
      // bottom-docked panel with the captured value (if any).
      this.autoSelectFirstOutputNode();
    };
  }

  /** Find the first output node in the graph (preferring one that has
   *  captured runtime values) and programmatically select it. */
  private autoSelectFirstOutputNode(): void {
    if (!this.flow) return;
    const outputs = this.flow.getNodes().filter((n) => n.dgNodeType === 'output');
    if (outputs.length === 0) return;
    const withValue = outputs.find((n) => {
      const s = this.executionController?.state.getNodeState(n.id);
      return s && s.outputs && Object.keys(s.outputs).length > 0;
    });
    void this.flow.selectNode((withValue ?? outputs[0]).id);
  }

  /** Accept drops of Datagrok files (→ OpenFile node), DG.Func (→ matching node),
   *  and HTML5 native drags from the function browser (carry typeName via the
   *  FF_DRAG_MIME data type). */
  private setupFileDropTarget(): void {
    ui.makeDroppable(this.canvasContainer, {
      acceptDrop: (drag: any) =>
        (drag instanceof DG.FileInfo && drag.isFile) || drag instanceof DG.Func,
      doDrop: (args) => {
        const drag = args.dragObject;
        if (drag instanceof DG.Func) {void this.addFuncNode(drag); return;}
        const fi = drag as DG.FileInfo;
        void this.addOpenFileNode(fi.fullPath);
      },
    });

    // Native HTML5 drag/drop from the function browser.
    this.canvasContainer.addEventListener('dragover', (ev) => {
      if (!ev.dataTransfer) return;
      if (Array.from(ev.dataTransfer.types).includes(FF_DRAG_MIME)) {
        ev.preventDefault();
        ev.dataTransfer.dropEffect = 'copy';
      }
    });
    this.canvasContainer.addEventListener('drop', (ev) => {
      const typeName = ev.dataTransfer?.getData(FF_DRAG_MIME);
      if (!typeName) return;
      ev.preventDefault();
      void this.addNodeByTypeAt(typeName, ev.clientX, ev.clientY);
    });
  }

  /** Add a node and place it at the canvas position corresponding to the given
   *  screen-space pointer event. Used by drop handlers. */
  private async addNodeByTypeAt(typeName: string, clientX: number, clientY: number): Promise<FlowNode | null> {
    if (!this.flow) return null;
    const node = createNode(typeName);
    if (!node) {
      grok.shell.warning(`Unknown node type: ${typeName}`);
      return null;
    }
    const {x, y} = this.flow.screenToCanvas(clientX, clientY);
    await this.flow.addNodeAt(node, x, y);
    this.updateStatusBar();
    return node;
  }

  private async addNodeByType(typeName: string): Promise<FlowNode | null> {
    if (!this.flow) return null;
    const node = createNode(typeName);
    if (!node) {
      grok.shell.warning(`Unknown node type: ${typeName}`);
      return null;
    }
    await this.flow.addNodeAtCenter(node);
    this.updateStatusBar();
    return node;
  }

  private async addOpenFileNode(filePath: string): Promise<void> {
    const typeName = this.findOpenFileNodeType();
    if (!typeName) {
      grok.shell.warning('OpenFile function not found in registered nodes');
      return;
    }
    const node = await this.addNodeByType(typeName);
    if (node) {
      node.inputValues['fullPath'] = filePath;
      await this.flow.updateNode(node.id);
      grok.shell.info(`Added OpenFile node for: ${filePath}`);
    }
  }

  private async addFuncNode(func: DG.Func): Promise<void> {
    const info = getRegisteredFuncs().find((f) => f.func.name === func.name);
    if (!info) {
      grok.shell.warning(`Function "${func.name}" is not available as a node`);
      return;
    }
    if (await this.addNodeByType(info.nodeTypeName))
      grok.shell.info(`Added node: ${func.name}`);
  }

  private findOpenFileNodeType(): string | null {
    for (const info of getRegisteredFuncs()) {
      if (info.func.name === 'OpenFile' || info.func.name === 'openFile')
        return info.nodeTypeName;
    }
    return null;
  }

  // ---------- ribbon ----------

  private setupRibbon(): void {
    this.ribbonMenu = DG.Menu.create()
      .group('File')
      .item('New Flow', () => void this.newFlow())
      .item('Open Flow...', () => void this.openFlow())
      .item('Save Flow...', () => this.saveFlow())
      .separator()
      .item('Export Settings...', () => this.editSettings())
      .endGroup()
      .group('Edit')
      .item('Undo', () => void this.flow?.undo())
      .item('Redo', () => void this.flow?.redo())
      .endGroup()
      .group('View')
      .item('Zoom to Fit', () => void this.flow?.zoomToFit())
      .item('Zoom In', () => this.flow?.zoomIn())
      .item('Zoom Out', () => this.flow?.zoomOut())
      .separator()
      .item('Toggle Function Browser', () => this.toggleToolbox())
      .endGroup()
      .group('Script')
      .item('Run Script (Classic)', () => this.runScript())
      .item('View Script', () => this.generateAndPreview())
      .item('Copy Script to Clipboard', () => this.copyScriptToClipboard())
      .item('Export as .js File', () => this.exportAsJs())
      .separator()
      .item('Validate Graph', () => this.showValidation())
      .endGroup()
      .group('Execution')
      .item('Run', () => this.runInstrumented())
      .item('Debug', () => this.debugInstrumented())
      .item('Continue', () => this.executionController?.continueBreakpoint())
      .item('Stop', () => this.executionController?.stopRun())
      .separator()
      .item('Reset Visuals', () => this.executionController?.resetVisuals())
      .endGroup();

    this.setRibbonPanels([
      [
        ui.iconFA('play', () => this.runInstrumented(), 'Run'),
        ui.iconFA('bug', () => this.debugInstrumented(), 'Debug'),
        ui.iconFA('forward', () => this.executionController?.continueBreakpoint(), 'Continue'),
        ui.iconFA('stop', () => this.executionController?.stopRun(), 'Stop'),
      ],
      [
        ui.iconFA('code', () => this.generateAndPreview(), 'View Script'),
        ui.iconFA('copy', () => this.copyScriptToClipboard(), 'Copy Script'),
        ui.iconFA('download', () => this.exportAsJs(), 'Export .js'),
      ],
      [
        ui.iconFA('undo', () => void this.flow?.undo(), 'Undo (Ctrl+Z)'),
        ui.iconFA('redo', () => void this.flow?.redo(), 'Redo (Ctrl+Shift+Z)'),
      ],
      [
        ui.iconFA('search-plus', () => this.flow?.zoomIn(), 'Zoom In'),
        ui.iconFA('search-minus', () => this.flow?.zoomOut(), 'Zoom Out'),
        ui.iconFA('compress-arrows-alt', () => void this.flow?.zoomToFit(), 'Zoom to Fit (double-click empty canvas)'),
        ui.iconFA('list-ul', () => this.toggleToolbox(), 'Toggle Function Browser'),
      ],
    ]);
  }

  private setupStatusBar(): void {
    this.statusBarPanels = [this.statusBar as HTMLDivElement];
  }

  private toggleToolbox(): void {
    grok.shell.windows.showToolbox = !grok.shell.windows.showToolbox;
  }

  private updateStatusBar(): void {
    if (!this.flow) return;
    this.nodeCountLabel.textContent = `Nodes: ${this.flow.getNodeCount()}`;
    this.linkCountLabel.textContent = `Links: ${this.flow.getConnectionCount()}`;
  }

  // ---------- file actions ----------

  private async newFlow(): Promise<void> {
    await this.flow.clear();
    this.propertyPanel.clear();
    this.updateStatusBar();
    grok.shell.info('New flow created');
  }

  private async openFlow(): Promise<void> {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.ffjson,.json';
    input.addEventListener('change', async () => {
      const file = input.files?.[0];
      if (!file) return;
      try {
        const doc = await loadFlowFromFile(file);
        await deserializeFlow(doc, this.flow);
        if (doc.metadata?.settings) this.flowSettings = doc.metadata.settings;
        this.updateStatusBar();
        grok.shell.info(`Loaded flow: ${doc.name}`);
      } catch (e: any) {
        grok.shell.error(`Failed to load flow: ${e.message}`);
      }
    });
    input.click();
  }

  private saveFlow(): void {
    const doc = serializeFlow(this.flow, this.flowSettings);
    downloadFlow(doc);
    grok.shell.info('Flow saved');
  }

  private editSettings(): void {
    const nameInput = ui.input.string('Script Name', {value: this.flowSettings.scriptName});
    const descInput = ui.input.string('Description', {value: this.flowSettings.scriptDescription});
    const tagsInput = ui.input.string('Tags', {value: this.flowSettings.tags.join(', ')});

    ui.dialog({title: 'Flow Settings'})
      .add(nameInput).add(descInput).add(tagsInput)
      .onOK(() => {
        this.flowSettings.scriptName = nameInput.value;
        this.flowSettings.scriptDescription = descInput.value;
        this.flowSettings.tags = tagsInput.value.split(',').map((s: string) => s.trim()).filter(Boolean);
      })
      .show();
  }

  // ---------- run / debug ----------

  private runInstrumented(): void {
    this.executionController?.runInstrumented({
      name: this.flowSettings.scriptName,
      description: this.flowSettings.scriptDescription,
      tags: this.flowSettings.tags,
    });
  }

  private debugInstrumented(): void {
    this.executionController?.debugInstrumented({
      name: this.flowSettings.scriptName,
      description: this.flowSettings.scriptDescription,
      tags: this.flowSettings.tags,
    });
  }

  private generateScript(): string | null {
    const errors = validateGraph(this.flow);
    if (errors.some((e) => e.severity === 'error')) {
      const msgs = errors.filter((e) => e.severity === 'error').map((e) => e.message).join('\n');
      grok.shell.error('Validation errors:\n' + msgs);
      return null;
    }
    try {
      return emitScript(this.flow, {
        name: this.flowSettings.scriptName,
        description: this.flowSettings.scriptDescription,
        tags: this.flowSettings.tags,
      });
    } catch (e: any) {
      grok.shell.error(`Script generation failed: ${e.message}`);
      return null;
    }
  }

  private runScript(): void {
    const script = this.generateScript();
    if (!script) return;
    // Classic (non-instrumented) run — no per-node values are captured, so
    // the click-to-inspect docked panel doesn't apply here. Outputs are
    // surfaced by Datagrok's standard script-run dialog.
    const func = DG.Script.create(script);
    const fc = func.prepare();
    if (func.inputs.length === 0)
      void fc.call(undefined, undefined, {processed: true});
    else {
      fc.getEditor(false).then((e: HTMLElement) => {
        ui.dialog({title: func.friendlyName ?? func.name}).add(e).show().onOK(async () => {
          await fc.call(undefined, undefined, {processed: true});
        });
      });
    }
  }

  private generateAndPreview(): void {
    const script = this.generateScript();
    if (!script) return;
    const pre = document.createElement('pre');
    pre.className = 'funcflow-script-preview';
    pre.textContent = script;
    const d = ui.dialog({title: 'Generated Script'})
      .add(pre)
      .addButton('Copy to Clipboard', () => {
        navigator.clipboard.writeText(script);
        grok.shell.info('Script copied to clipboard');
      })
      .addButton('Export .js', () => this.downloadScriptAsJs(script))
      .addButton('Open in Script View', () => {
        const sv = DG.ScriptView.create(DG.Script.create(script));
        grok.shell.addView(sv);
        d.close();
      })
      .addButton('Run', () => {
        DG.Script.create(script).prepare().edit();
        d.close();
      })
      .show({width: 700, height: 500});
  }

  private copyScriptToClipboard(): void {
    const script = this.generateScript();
    if (!script) return;
    navigator.clipboard.writeText(script);
    grok.shell.info('Script copied to clipboard');
  }

  private exportAsJs(): void {
    const script = this.generateScript();
    if (script) this.downloadScriptAsJs(script);
  }

  private downloadScriptAsJs(script: string): void {
    const blob = new Blob([script], {type: 'text/javascript'});
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${this.flowSettings.scriptName || 'script'}.js`;
    a.click();
    URL.revokeObjectURL(url);
  }

  /** Load a flow from a JSON string (file viewer entry point). */
  async loadFromJson(json: string): Promise<void> {
    const doc = JSON.parse(json) as import('./serialization/flow-schema').FuncFlowDocument;
    const load = async () => {
      await deserializeFlow(doc, this.flow);
      if (doc.metadata?.settings) this.flowSettings = doc.metadata.settings;
      this.name = doc.name || 'FuncFlow';
      this.updateStatusBar();
    };
    if (this.flow) await load();
    else setTimeout(() => void load(), 100);
  }

  private showValidation(): void {
    const results = validateGraph(this.flow);
    if (results.length === 0) {
      grok.shell.info('Graph is valid!');
      return;
    }
    const items = results.map((r) => {
      const icon = r.severity === 'error' ? '!!' : '!';
      return ui.divText(`[${icon}] ${r.message}`);
    });
    ui.dialog({title: 'Validation Results'}).add(ui.divV(items)).show({width: 500, height: 400});
  }
}
