import * as grok from 'datagrok-api/grok';
import * as ui from 'datagrok-api/ui';
import * as DG from 'datagrok-api/dg';
import {LGraphNode, LiteGraph} from 'litegraph.js';

import 'litegraph.js/css/litegraph.css';
import '../css/funcflow.css';

import {GraphManager} from './canvas/graph-manager';
import {CanvasController} from './canvas/canvas-controller';
import {FunctionBrowser} from './panel/function-browser';
import {PropertyPanel} from './panel/property-panel';
import {registerBuiltinNodes, registerAllFunctions, FuncInfo} from './nodes/node-factory';
import {validateGraph, ValidationResult} from './compiler/validator';
import {emitScript} from './compiler/script-emitter';
import {serializeFlow, deserializeFlow, downloadFlow, loadFlowFromFile} from './serialization/flow-serializer';
import {FlowSettings} from './serialization/flow-schema';
import {UndoManager} from './history/undo-manager';

/** Main FuncFlow view - the full-screen function chain designer */
export class FuncFlowView extends DG.ViewBase {
  private graphManager: GraphManager;
  private canvasController!: CanvasController;
  private functionBrowser!: FunctionBrowser;
  private propertyPanel!: PropertyPanel;
  private undoManager: UndoManager;

  private canvasContainer!: HTMLElement;
  private statusBar!: HTMLElement;
  private nodeCountLabel!: HTMLElement;
  private linkCountLabel!: HTMLElement;
  private validationLabel!: HTMLElement;

  private flowSettings: FlowSettings = {
    scriptName: 'MyFuncFlow',
    scriptDescription: 'Generated by FuncFlow',
    tags: ['funcflow'],
  };

  constructor() {
    super();
    this.name = 'FuncFlow';
    this.graphManager = new GraphManager();
    this.undoManager = new UndoManager();

    // Register all node types
    registerBuiltinNodes();

    this.initUI();
    this.setupRibbon();
    this.setupStatusBar();

    // Show the native context panel
    grok.shell.windows.showContextPanel = true;

    // Register DG functions asynchronously (may take time)
    setTimeout(() => {
      try {
        registerAllFunctions();
        this.functionBrowser.render();
      } catch (e) {
        console.warn('FuncFlow: Error registering functions:', e);
      }
    }, 100);
  }

  private initUI(): void {
    // Left panel: Function Browser
    this.functionBrowser = new FunctionBrowser({
      onFunctionDoubleClick: (info: FuncInfo) => {
        this.canvasController.addNodeAtCenter(info.nodeTypeName);
        this.updateStatusBar();
      },
      onBuiltinNodeDoubleClick: (nodeTypeName: string) => {
        this.canvasController.addNodeAtCenter(nodeTypeName);
        this.updateStatusBar();
      },
    });

    const leftPanel = ui.div([this.functionBrowser.root], 'funcflow-left-panel');

    // Center: Canvas
    this.canvasContainer = ui.div([], 'funcflow-canvas-container');

    // Property Panel (renders into context panel, not inline)
    this.propertyPanel = new PropertyPanel();

    // Status bar
    this.nodeCountLabel = ui.divText('Nodes: 0');
    this.linkCountLabel = ui.divText('Links: 0');
    this.validationLabel = ui.divText('');
    ui.tooltip.bind(this.nodeCountLabel, 'Total number of nodes in the graph');
    ui.tooltip.bind(this.linkCountLabel, 'Total number of connections between nodes');
    this.statusBar = ui.div(
      [this.nodeCountLabel, this.linkCountLabel, this.validationLabel],
      'funcflow-status-bar',
    );

    // Main layout — no right panel, just left + canvas
    const mainLayout = ui.div([leftPanel, this.canvasContainer], 'funcflow-root');

    this.root.style.width = '100%';
    this.root.style.height = '100%';
    this.root.style.display = 'flex';
    this.root.style.flexDirection = 'column';
    this.root.appendChild(mainLayout);
    this.root.appendChild(this.statusBar);

    // Make main layout fill available space
    mainLayout.style.flex = '1';
    mainLayout.style.overflow = 'hidden';

    // Make canvas container droppable for files
    this.setupFileDropTarget();

    // Initialize canvas after DOM is ready
    setTimeout(() => this.initCanvas(), 50);
  }

  private initCanvas(): void {
    this.canvasController = new CanvasController(this.canvasContainer, this.graphManager, {
      onNodeSelected: (node: LGraphNode) => {
        this.propertyPanel.showNode(node);
        grok.shell.o = this.propertyPanel.root;
      },
      onNodeDeselected: () => {
        this.propertyPanel.clear();
        grok.shell.o = this.propertyPanel.root;
      },
      onGraphChanged: () => {
        this.updateStatusBar();
      },
    });
    this.canvasController.startRendering();
  }

  /** Makes the canvas container accept file drops from the platform file browser */
  private setupFileDropTarget(): void {
    ui.makeDroppable(this.canvasContainer, {
      acceptDrop: (dragObject: any) => {
        return dragObject instanceof DG.FileInfo && dragObject.isFile;
      },
      doDrop: (dragObject: any, _copying: boolean) => {
        const fileInfo = dragObject as DG.FileInfo;
        // console.log(fileInfo.fullPath);
        this.addOpenFileNode(fileInfo.fullPath);
      },
    });
  }

  /** Adds an OpenFile function node to the canvas with the given file path */
  private addOpenFileNode(filePath: string): void {
    if (!this.canvasController) return;

    // Find and add the OpenFile function node
    const nodeTypeName = this.findOpenFileNodeType();
    if (nodeTypeName) {
      const node = this.canvasController.addNodeAtCenter(nodeTypeName);
      if (node) {
        // Set the path parameter on the node
        if (node.properties)
          node.properties['_input_fullPath'] = filePath;
        // Try to set the widget value too
        if ((node as any).widgets) {
          for (const w of (node as any).widgets) {
            if (w.name === 'fullPath') {
              w.value = filePath;
              break;
            }
          }
        }
        this.updateStatusBar();
        grok.shell.info(`Added OpenFile node for: ${filePath}`);
      }
    } else
      grok.shell.warning('OpenFile function not found in registered nodes');
  }

  /** Searches registered node types for the OpenFile function */
  private findOpenFileNodeType(): string | null {
    const registered = LiteGraph.registered_node_types;
    for (const key of Object.keys(registered)) {
      if (key.includes('OpenFile') || key.includes('openFile'))
        return key;
    }
    return null;
  }

  private setupRibbon(): void {
    // Ribbon menu
    this.ribbonMenu = DG.Menu.create()
      .group('File')
      .item('New Flow', () => this.newFlow())
      .item('Open Flow...', () => this.openFlow())
      .item('Save Flow...', () => this.saveFlow())
      .separator()
      .item('Export Settings...', () => this.editSettings())
      .endGroup()
      .group('Edit')
      .item('Undo', () => this.undoManager.undo())
      .item('Redo', () => this.undoManager.redo())
      .endGroup()
      .group('View')
      .item('Zoom to Fit', () => this.canvasController?.zoomToFit())
      .item('Zoom In', () => this.canvasController?.zoomIn())
      .item('Zoom Out', () => this.canvasController?.zoomOut())
      .endGroup()
      .group('Script')
      .item('Run Script', () => this.runScript())
      .item('View Script', () => this.generateAndPreview())
      .item('Copy Script to Clipboard', () => this.copyScriptToClipboard())
      .item('Export as .js File', () => this.exportAsJs())
      .separator()
      .item('Validate Graph', () => this.showValidation())
      .endGroup();

    // Ribbon button panels
    this.setRibbonPanels([
      [
        ui.iconFA('play', () => this.runScript(), 'Run Script'),
        ui.iconFA('code', () => this.generateAndPreview(), 'View Script'),
        ui.iconFA('copy', () => this.copyScriptToClipboard(), 'Copy Script'),
        ui.iconFA('download', () => this.exportAsJs(), 'Export .js'),
      ],
      [
        ui.iconFA('undo', () => this.undoManager.undo(), 'Undo'),
        ui.iconFA('redo', () => this.undoManager.redo(), 'Redo'),
      ],
      [
        ui.iconFA('search-plus', () => this.canvasController?.zoomIn(), 'Zoom In'),
        ui.iconFA('search-minus', () => this.canvasController?.zoomOut(), 'Zoom Out'),
        ui.iconFA('compress-arrows-alt', () => this.canvasController?.zoomToFit(), 'Zoom to Fit'),
      ],
    ]);
  }

  private setupStatusBar(): void {
    this.statusBarPanels = [this.statusBar as HTMLDivElement];
  }

  private updateStatusBar(): void {
    this.nodeCountLabel.textContent = `Nodes: ${this.graphManager.getNodeCount()}`;
    this.linkCountLabel.textContent = `Links: ${this.graphManager.getLinkCount()}`;
  }

  // --- Actions ---

  private newFlow(): void {
    this.graphManager.clear();
    this.propertyPanel.clear();
    this.undoManager.clear();
    this.updateStatusBar();
    grok.shell.info('New flow created');
  }

  private async openFlow(): Promise<void> {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.funcflow.json,.json,.ffjson';
    input.addEventListener('change', async () => {
      const file = input.files?.[0];
      if (!file) return;
      try {
        const doc = await loadFlowFromFile(file);
        deserializeFlow(doc, this.graphManager.graph);
        if (doc.metadata?.settings)
          this.flowSettings = doc.metadata.settings;
        this.updateStatusBar();
        grok.shell.info(`Loaded flow: ${doc.name}`);
      } catch (e: any) {
        grok.shell.error(`Failed to load flow: ${e.message}`);
      }
    });
    input.click();
  }

  private saveFlow(): void {
    const doc = serializeFlow(this.graphManager.graph, this.flowSettings);
    downloadFlow(doc);
    grok.shell.info('Flow saved');
  }

  private editSettings(): void {
    const nameInput = ui.input.string('Script Name', {value: this.flowSettings.scriptName});
    const descInput = ui.input.string('Description', {value: this.flowSettings.scriptDescription});
    const tagsInput = ui.input.string('Tags', {value: this.flowSettings.tags.join(', ')});

    ui.dialog({title: 'Flow Settings'})
      .add(nameInput)
      .add(descInput)
      .add(tagsInput)
      .onOK(() => {
        this.flowSettings.scriptName = nameInput.value;
        this.flowSettings.scriptDescription = descInput.value;
        this.flowSettings.tags = tagsInput.value.split(',').map((s: string) => s.trim()).filter(Boolean);
      })
      .show();
  }

  private generateScript(): string | null {
    const errors = validateGraph(this.graphManager.graph);
    const hasErrors = errors.some((e) => e.severity === 'error');

    if (hasErrors) {
      const errorMessages = errors
        .filter((e) => e.severity === 'error')
        .map((e) => e.message)
        .join('\n');
      grok.shell.error('Validation errors:\n' + errorMessages);
      return null;
    }

    try {
      return emitScript(this.graphManager.graph, {
        name: this.flowSettings.scriptName,
        description: this.flowSettings.scriptDescription,
        tags: this.flowSettings.tags,
      });
    } catch (e: any) {
      grok.shell.error(`Script generation failed: ${e.message}`);
      return null;
    }
  }

  /** Compiles, validates and runs the script directly */
  private runScript(): void {
    const script = this.generateScript();
    if (!script) return;
    DG.Script.create(script).prepare().edit();
  }

  private generateAndPreview(): void {
    const script = this.generateScript();
    if (!script) return;

    const pre = document.createElement('pre');
    pre.className = 'funcflow-script-preview';
    pre.textContent = script;

    const d = ui.dialog({title: 'Generated Script'})
      .add(pre)
      .addButton('Copy to Clipboard', () => {
        navigator.clipboard.writeText(script);
        grok.shell.info('Script copied to clipboard');
      })
      .addButton('Export .js', () => {
        const blob = new Blob([script], {type: 'text/javascript'});
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${this.flowSettings.scriptName || 'script'}.js`;
        a.click();
        URL.revokeObjectURL(url);
      })
      .addButton('Open in Script View', () => {
        const sv = DG.ScriptView.create(DG.Script.create(script));
        grok.shell.addView(sv);
        d.close();
      })
      .addButton('Run', () => {
        DG.Script.create(script).prepare().edit();
        d.close();
      })
      .show({width: 700, height: 500});
  }

  private copyScriptToClipboard(): void {
    const script = this.generateScript();
    if (!script) return;
    navigator.clipboard.writeText(script);
    grok.shell.info('Script copied to clipboard');
  }

  private exportAsJs(): void {
    const script = this.generateScript();
    if (!script) return;
    const blob = new Blob([script], {type: 'text/javascript'});
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${this.flowSettings.scriptName || 'script'}.js`;
    a.click();
    URL.revokeObjectURL(url);
  }

  /** Load a flow from a JSON string (used by file viewer) */
  loadFromJson(json: string): void {
    const doc = JSON.parse(json) as import('./serialization/flow-schema').FuncFlowDocument;
    const load = () => {
      deserializeFlow(doc, this.graphManager.graph);
      if (doc.metadata?.settings)
        this.flowSettings = doc.metadata.settings;
      this.name = doc.name || 'FuncFlow';
      this.updateStatusBar();
    };
    // Canvas initializes after 50ms; deserialize after it's ready
    if (this.canvasController)
      load();
    else
      setTimeout(load, 100);
  }

  private showValidation(): void {
    const results = validateGraph(this.graphManager.graph);
    if (results.length === 0) {
      grok.shell.info('Graph is valid!');
      return;
    }

    const items = results.map((r) => {
      const icon = r.severity === 'error' ? '!!' : '!';
      return ui.divText(`[${icon}] ${r.message}`);
    });

    ui.dialog({title: 'Validation Results'})
      .add(ui.divV(items))
      .show({width: 500, height: 400});
  }
}
