/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('Flow:Info', {});
  }

  /**
   * Interactive function chain designer
   * @param {string} path
   *   meta.url: true
   *   optional: true
   * @returns {Promise<DG.View>}
   */
  export async function funcflowApp(path?: string ): Promise<DG.View> {
    return await grok.functions.call('Flow:FuncflowApp', { path });
  }

  /**
   * @param {DG.FileInfo} file
   * @returns {Promise<DG.View>}
   */
  export async function viewFuncFlow(file: DG.FileInfo ): Promise<DG.View> {
    return await grok.functions.call('Flow:ViewFuncFlow', { file });
  }
}
