/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('Flow:Info', {});
  }

  export async function flowScriptHandler(scriptCall: any ): Promise<void> {
    return await grok.functions.call('Flow:FlowScriptHandler', { scriptCall });
  }

  /**
  Reads a file uploaded into a flow and parses it into a table
  */
  export async function readUploadedFile(fileId: string , fileName: string ): Promise<DG.DataFrame> {
    return await grok.functions.call('Flow:ReadUploadedFile', { fileId, fileName });
  }

  /**
  Keeps uploaded-file permissions in sync when a flow script is shared
  */
  export async function flowShareSync(): Promise<void> {
    return await grok.functions.call('Flow:FlowShareSync', {});
  }

  /**
  Interactive function chain designer
  */
  export async function funcflowApp(path?: string ): Promise<DG.View> {
    return await grok.functions.call('Flow:FuncflowApp', { path });
  }

  export async function viewFuncFlow(file: DG.FileInfo ): Promise<DG.View> {
    return await grok.functions.call('Flow:ViewFuncFlow', { file });
  }

  /**
  Builds a flow diagram from a table creation script and opens it in the Flow editor
  */
  export async function flowFromCreationScript(script: string ): Promise<DG.View> {
    return await grok.functions.call('Flow:FlowFromCreationScript', { script });
  }

  export async function openCreationScriptFlowDialog(script: string , tableIds: any , show: boolean ): Promise<any> {
    return await grok.functions.call('Flow:OpenCreationScriptFlowDialog', { script, tableIds, show });
  }

  /**
  Opens the visual Flow editor for a flow script entity
  */
  export async function flowScriptEditor(script: any ): Promise<DG.View> {
    return await grok.functions.call('Flow:FlowScriptEditor', { script });
  }

  export async function flowScriptPreview(script: any ): Promise<DG.View> {
    return await grok.functions.call('Flow:FlowScriptPreview', { script });
  }

  export async function flowScriptWidget(script: any ): Promise<any> {
    return await grok.functions.call('Flow:FlowScriptWidget', { script });
  }

  /**
  List the current flow graph: all nodes (id, label, type, status, set input values) and connections. Call this first to understand what is on the canvas
  */
  export async function listFlowNodes(view: DG.View ): Promise<any> {
    return await grok.functions.call('Flow:ListFlowNodes', { view });
  }

  /**
  Ports (with DG types), editable input values, unmet requirements, and last-run outputs of one node
  */
  export async function getFlowNodeDetails(view: DG.View , nodeId: string ): Promise<any> {
    return await grok.functions.call('Flow:GetFlowNodeDetails', { view, nodeId });
  }

  /**
  Search the flow node catalog (a curated subset of platform functions plus input/output/utility nodes). ALWAYS filter: pass a query with what the node should do (e.g. "join tables", "open file"), and/or a DG type it must accept or produce (dataframe, column, string, ...). Returns at most limit (default 15) matches with their input/output types
  */
  export async function findFlowNodeTypes(view: DG.View , query?: string , acceptsInputType?: string , producesOutputType?: string , limit?: number ): Promise<any> {
    return await grok.functions.call('Flow:FindFlowNodeTypes', { view, query, acceptsInputType, producesOutputType, limit });
  }

  /**
  Add a node to the canvas by its registered typeName (from findFlowNodeTypes). Optionally set editable input values right away. Returns the new node id and its ports
  */
  export async function addFlowNode(view: DG.View , typeName: string , label?: string , inputValues?: any ): Promise<any> {
    return await grok.functions.call('Flow:AddFlowNode', { view, typeName, label, inputValues });
  }

  /**
  Connect a source node output to a target node input (port keys from getFlowNodeDetails / addFlowNode). Types must be compatible
  */
  export async function connectFlowNodes(view: DG.View , sourceNodeId: string , sourceOutput: string , targetNodeId: string , targetInput: string ): Promise<any> {
    return await grok.functions.call('Flow:ConnectFlowNodes', { view, sourceNodeId, sourceOutput, targetNodeId, targetInput });
  }

  /**
  Set editable input values of a node (key to value; keys from getFlowNodeDetails). Marks the node and its downstream stale
  */
  export async function setFlowNodeInputs(view: DG.View , nodeId: string , values: any ): Promise<any> {
    return await grok.functions.call('Flow:SetFlowNodeInputs', { view, nodeId, values });
  }

  /**
  Select a node on the canvas so the user sees it (opens its properties panel)
  */
  export async function selectFlowNode(view: DG.View , nodeId: string ): Promise<any> {
    return await grok.functions.call('Flow:SelectFlowNode', { view, nodeId });
  }

  /**
  List Flow built-in interactive guides: step-by-step tutorials and short "how do I" walkthroughs that highlight the actual UI. When the user asks how to do something in Flow, check here first — a matching guide beats a textual explanation
  */
  export async function listFlowGuides(view: DG.View , query?: string ): Promise<any> {
    return await grok.functions.call('Flow:ListFlowGuides', { view, query });
  }

  /**
  Start an interactive guide (id from listFlowGuides) — it highlights the real UI step by step and waits for the user to act. ALWAYS confirm with the user first before starting one; never launch it unasked
  */
  export async function startFlowGuide(view: DG.View , guideId: string ): Promise<any> {
    return await grok.functions.call('Flow:StartFlowGuide', { view, guideId });
  }

  /**
  Validate and execute the whole flow. Returns validation problems instead of running if the graph is invalid; otherwise waits for the run and reports per-node failures
  */
  export async function runFlow(view: DG.View ): Promise<any> {
    return await grok.functions.call('Flow:RunFlow', { view });
  }

  /**
  Keeps the rows matching a condition, as a new table
  */
  export async function filterRows(table: DG.DataFrame , condition: string ): Promise<DG.DataFrame> {
    return await grok.functions.call('Flow:FilterRows', { table, condition });
  }

  /**
  Removes the rows matching a condition, as a new table
  */
  export async function deleteRows(table: DG.DataFrame , condition: string ): Promise<DG.DataFrame> {
    return await grok.functions.call('Flow:DeleteRows', { table, condition });
  }

  /**
  Rows matching a condition, keeping only the chosen columns
  */
  export async function extractRows(table: DG.DataFrame , condition: string , columns: string[] | null): Promise<DG.DataFrame> {
    return await grok.functions.call('Flow:ExtractRows', { table, condition, columns });
  }

  /**
  Selects the rows matching a condition and passes the table on
  */
  export async function selectRows(table: DG.DataFrame , condition: string , clearSelection: boolean ): Promise<DG.DataFrame> {
    return await grok.functions.call('Flow:SelectRows', { table, condition, clearSelection });
  }

  /**
  Sets the current row of the table
  */
  export async function setCurrentRow(table: DG.DataFrame , index: number ): Promise<DG.DataFrame> {
    return await grok.functions.call('Flow:SetCurrentRow', { table, index });
  }

  /**
  A reproducible random sample of rows, as a new table
  */
  export async function filterRandomRows(table: DG.DataFrame , count: number , seed: number ): Promise<DG.DataFrame> {
    return await grok.functions.call('Flow:FilterRandomRows', { table, count, seed });
  }

  /**
  Selects a reproducible random sample of rows and passes the table on
  */
  export async function selectRandomRows(table: DG.DataFrame , count: number , seed: number , clearSelection: boolean ): Promise<DG.DataFrame> {
    return await grok.functions.call('Flow:SelectRandomRows', { table, count, seed, clearSelection });
  }

  /**
  A copy of the table without the chosen columns. Removes selected columns
  */
  export async function deleteColumns(table: DG.DataFrame , columns: string[] ): Promise<DG.DataFrame> {
    return await grok.functions.call('Flow:DeleteColumns', { table, columns });
  }

  /**
  Sets a tag on the chosen columns and passes the table on
  */
  export async function tagColumns(table: DG.DataFrame , columns: string[] , tag: string , value: string | null): Promise<DG.DataFrame> {
    return await grok.functions.call('Flow:TagColumns', { table, columns, tag, value });
  }

  /**
  Computes an expression into a new column of the table
  */
  export async function expressionToColumn(table: DG.DataFrame , expression: string , name: string , type: string ): Promise<DG.Column> {
    return await grok.functions.call('Flow:ExpressionToColumn', { table, expression, name, type });
  }

  /**
  Groups rows and aggregates columns. Add a pivot column to build a pivot table
  */
  export async function aggregate(table: DG.DataFrame , groupByColumns: string[] | null, aggregations: string , pivotColumns: string[] | null): Promise<DG.DataFrame> {
    return await grok.functions.call('Flow:Aggregate', { table, groupByColumns, aggregations, pivotColumns });
  }

  /**
  Wide to long. Each merged column becomes a category and value row pair
  */
  export async function unpivot(table: DG.DataFrame , copyColumns: string[] | null, mergeColumns: string[] , categoryColumnName: string , valueColumnName: string ): Promise<DG.DataFrame> {
    return await grok.functions.call('Flow:Unpivot', { table, copyColumns, mergeColumns, categoryColumnName, valueColumnName });
  }

  /**
  Renders a molecule as a widget. Drawn once on a large square canvas so the preview stays crisp at any size
  */
  export async function renderMolecule(molecule: string ): Promise<any> {
    return await grok.functions.call('Flow:RenderMolecule', { molecule });
  }

  export async function viewFlowFile(file: DG.FileInfo ): Promise<DG.View> {
    return await grok.functions.call('Flow:ViewFlowFile', { file });
  }
}
