/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('Flow:Info', {});
  }

  export async function flowScriptHandler(scriptCall: any ): Promise<void> {
    return await grok.functions.call('Flow:FlowScriptHandler', { scriptCall });
  }

  /**
  Interactive function chain designer
  */
  export async function funcflowApp(path?: string ): Promise<DG.View> {
    return await grok.functions.call('Flow:FuncflowApp', { path });
  }

  export async function viewFuncFlow(file: DG.FileInfo ): Promise<DG.View> {
    return await grok.functions.call('Flow:ViewFuncFlow', { file });
  }

  /**
  Builds a flow diagram from a table creation script and opens it in the Flow editor
  */
  export async function flowFromCreationScript(script: string ): Promise<DG.View> {
    return await grok.functions.call('Flow:FlowFromCreationScript', { script });
  }

  export async function openCreationScriptFlowDialog(script: string , tableIds: any , show: boolean ): Promise<any> {
    return await grok.functions.call('Flow:OpenCreationScriptFlowDialog', { script, tableIds, show });
  }

  export async function testDialog(): Promise<void> {
    return await grok.functions.call('Flow:TestDialog', {});
  }

  /**
  Opens the visual Flow editor for a flow script entity
  */
  export async function flowScriptEditor(script: any ): Promise<DG.View> {
    return await grok.functions.call('Flow:FlowScriptEditor', { script });
  }

  export async function flowScriptPreview(script: any ): Promise<DG.View> {
    return await grok.functions.call('Flow:FlowScriptPreview', { script });
  }

  export async function flowScriptWidget(script: any ): Promise<any> {
    return await grok.functions.call('Flow:FlowScriptWidget', { script });
  }

  export async function viewFlowFile(file: DG.FileInfo ): Promise<DG.View> {
    return await grok.functions.call('Flow:ViewFlowFile', { file });
  }
}
