/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function u2DemoApp(): Promise<DG.View> {
    return await grok.functions.call('U2Demo:U2DemoApp', {});
  }

  export async function reportsBrowserApp(): Promise<DG.View> {
    return await grok.functions.call('U2Demo:ReportsBrowserApp', {});
  }

  export async function u2DesignerApp(): Promise<DG.View> {
    return await grok.functions.call('U2Demo:U2DesignerApp', {});
  }

  /**
  Registers u2 value editors for the property types enabled in `u2.valueEditors`
  */
  export async function u2AutoRegisterEditors(): Promise<void> {
    return await grok.functions.call('U2Demo:U2AutoRegisterEditors', {});
  }

  export async function info(): Promise<void> {
    return await grok.functions.call('U2Demo:Info', {});
  }
}
