/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('Boltz1:Info', {});
  }

  export async function getBoltzConfigFolders(): Promise<any> {
    return await grok.functions.call('Boltz1:GetBoltzConfigFolders', {});
  }

  export async function runBoltz(config: string , msa: string ): Promise<string> {
    return await grok.functions.call('Boltz1:RunBoltz', { config, msa });
  }

  /**
   * @param {DG.Column} sequences
   *   semType: Macromolecule
   */
  export async function folding(table: DG.DataFrame , sequences: DG.Column ): Promise<DG.DataFrame> {
    return await grok.functions.call('Boltz1:Folding', { table, sequences });
  }

  /**
   * @param {DG.Column} ligands
   *   semType: Molecule
   * @param {string} config - 'Folder with config files for docking'
   *   choices: Boltz1:getBoltzConfigFolders
   */
  export async function docking(table: DG.DataFrame , ligands: DG.Column , config: string ): Promise<DG.DataFrame> {
    return await grok.functions.call('Boltz1:Docking', { table, ligands, config });
  }

  /**
   * @param {any} molecule
   *   semType: Molecule3D
   */
  export async function boltzWidget(molecule: any ): Promise<any> {
    return await grok.functions.call('Boltz1:BoltzWidget', { molecule });
  }

  export async function isApplicableBoltz(molecule: string ): Promise<boolean> {
    return await grok.functions.call('Boltz1:IsApplicableBoltz', { molecule });
  }

  export async function boltz1App(): Promise<DG.View> {
    return await grok.functions.call('Boltz1:Boltz1App', {});
  }

  /**
   * WDR5 protein-ligand complexes with Boltz-predicted affinity
   */
  export async function demoBoltz(): Promise<void> {
    return await grok.functions.call('Boltz1:DemoBoltz', {});
  }

  export async function getBoltzStructureBindingConfigs(): Promise<any> {
    return await grok.functions.call('Boltz1:GetBoltzStructureBindingConfigs', {});
  }

  export async function getBoltzSmDesignConfigs(): Promise<any> {
    return await grok.functions.call('Boltz1:GetBoltzSmDesignConfigs', {});
  }

  export async function getBoltzSmScreenConfigs(): Promise<any> {
    return await grok.functions.call('Boltz1:GetBoltzSmScreenConfigs', {});
  }

  export async function getBoltzProteinDesignConfigs(): Promise<any> {
    return await grok.functions.call('Boltz1:GetBoltzProteinDesignConfigs', {});
  }

  export async function getBoltzProteinScreenConfigs(): Promise<any> {
    return await grok.functions.call('Boltz1:GetBoltzProteinScreenConfigs', {});
  }

  /**
   * @param {DG.Column} ligands
   *   semType: Molecule
   * @param {string} config
   *   choices: Boltz1:getBoltzStructureBindingConfigs
   */
  export async function boltzStructureAndBinding(table: DG.DataFrame , ligands: DG.Column , config: string ): Promise<DG.DataFrame> {
    return await grok.functions.call('Boltz1:BoltzStructureAndBinding', { table, ligands, config });
  }

  /**
   * @param {DG.Column} molecules
   *   semType: Molecule
   */
  export async function boltzAdme(table: DG.DataFrame , molecules: DG.Column ): Promise<DG.DataFrame> {
    return await grok.functions.call('Boltz1:BoltzAdme', { table, molecules });
  }

  /**
   * @param {string} config
   *   choices: Boltz1:getBoltzSmDesignConfigs
   */
  export async function boltzDesignSmallMolecules(config: string , numMolecules: number ): Promise<DG.DataFrame> {
    return await grok.functions.call('Boltz1:BoltzDesignSmallMolecules', { config, numMolecules });
  }

  /**
   * @param {DG.Column} molecules
   *   semType: Molecule
   * @param {string} config
   *   choices: Boltz1:getBoltzSmScreenConfigs
   */
  export async function boltzScreenSmallMolecules(table: DG.DataFrame , molecules: DG.Column , config: string ): Promise<DG.DataFrame> {
    return await grok.functions.call('Boltz1:BoltzScreenSmallMolecules', { table, molecules, config });
  }

  /**
   * @param {string} config
   *   choices: Boltz1:getBoltzProteinDesignConfigs
   */
  export async function boltzDesignProteins(config: string , numProteins: number ): Promise<DG.DataFrame> {
    return await grok.functions.call('Boltz1:BoltzDesignProteins', { config, numProteins });
  }

  /**
   * @param {DG.Column} proteins
   *   semType: Macromolecule
   * @param {string} config
   *   choices: Boltz1:getBoltzProteinScreenConfigs
   */
  export async function boltzScreenProteins(table: DG.DataFrame , proteins: DG.Column , config: string ): Promise<DG.DataFrame> {
    return await grok.functions.call('Boltz1:BoltzScreenProteins', { table, proteins, config });
  }
}
