/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_collection_free: (a: number, b: number) => void;
export const __wbg_collectionbuilder_free: (a: number, b: number) => void;
export const __wbg_similarityresult_free: (a: number, b: number) => void;
export const __wbg_synthoncollection_free: (a: number, b: number) => void;
export const __wbg_synthonhits_free: (a: number, b: number) => void;
export const __wbg_synthonsimhits_free: (a: number, b: number) => void;
export const collection_fromSmiles: (a: number, b: number) => number;
export const collection_isIndexed: (a: number) => number;
export const collection_similaritySearch: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const collection_size: (a: number) => number;
export const collection_substructureSearch: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const collectionbuilder_addMany: (a: number, b: number, c: number) => number;
export const collectionbuilder_failed: (a: number) => number;
export const collectionbuilder_finish: (a: number) => number;
export const collectionbuilder_new: (a: number) => number;
export const similarityresult_indices: (a: number) => [number, number];
export const similarityresult_scores: (a: number) => [number, number];
export const synthoncollection_fromCsv: (a: number, b: number) => [number, number, number];
export const synthoncollection_numProducts: (a: number) => bigint;
export const synthoncollection_numReactions: (a: number) => number;
export const synthoncollection_numSynthons: (a: number) => number;
export const synthoncollection_similaritySearch: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const synthoncollection_substructureSearch: (a: number, b: number, c: number, d: number) => [number, number, number];
export const synthonhits_len: (a: number) => number;
export const synthonhits_names: (a: number) => [number, number];
export const synthonhits_smiles: (a: number) => [number, number];
export const synthonsimhits_names: (a: number) => [number, number];
export const synthonsimhits_scores: (a: number) => [number, number];
export const synthonsimhits_smiles: (a: number) => [number, number];
export const start: () => void;
export const collectionbuilder_added: (a: number) => number;
export const synthonsimhits_len: (a: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_alloc: () => number;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
