#!/usr/bin/env bash
# Builds the Patinae web viewer (WASM + JS) from the pinned upstream tag and vendors the
# artefacts into wasm/ and css/. Prerequisites: Rust stable with the wasm32-unknown-unknown
# target, Node 22. wasm-pack is pulled in by upstream's npm devDependencies.
set -euo pipefail

TAG="${PATINAE_TAG:-v0.4.7}"
REPO="https://github.com/zmactep/patinae"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG="$(dirname "$HERE")"
WORK="${PATINAE_WORK:-$(mktemp -d)}"

if [ ! -d "$WORK/patinae" ]; then
  git clone --depth 1 --branch "$TAG" "$REPO" "$WORK/patinae"
  for p in "$HERE"/patches/*.patch; do
    [ -e "$p" ] || continue
    git -C "$WORK/patinae" apply "$p"
  done
fi

pushd "$WORK/patinae/web" > /dev/null
npm ci
npm run build
popd > /dev/null

DIST="$WORK/patinae/web/dist"
mkdir -p "$PKG/wasm" "$PKG/css"
cp "$DIST/patinae-viewer.js" "$PKG/wasm/patinae-viewer.js"
cp "$DIST/patinae_web_bg.wasm" "$PKG/wasm/patinae_web_bg.wasm"
cp "$DIST"/patinae_web-*.js "$PKG/wasm/patinae_web.js"
sed -i -E 's#\./patinae_web-[A-Za-z0-9_-]+\.js#./patinae_web.js#g' "$PKG/wasm/patinae-viewer.js"
grep -q 'patinae_web-' "$PKG/wasm/patinae-viewer.js" && { echo "hashed glue import remains"; exit 1; }

BANNER="/*! Patinae $TAG — BSD-3-Clause — Copyright (c) Pavel Yakovlev — $REPO — see wasm/LICENSE */"
cp "$WORK/patinae/LICENSE" "$PKG/wasm/LICENSE"
sed -i "1i $BANNER" "$PKG/wasm/patinae-viewer.js" "$PKG/wasm/patinae_web.js"

# Scope the upstream panel CSS under .patinae-view (native CSS nesting) so its unprefixed
# selectors (.panel-header, .object-row, ...) cannot leak into the platform. Its :root token
# block is dropped: css/patinae.css defines the --patinae-* tokens from Datagrok's palette.
{
  echo "$BANNER"
  echo "/* Vendored from web/ts/src/styles/viewer.css; regenerated by wasm-src/build.sh */"
  echo ".patinae-view {"
  awk '/^:root \{/ {skip=1} skip && /^\}/ {skip=0; next} !skip' "$WORK/patinae/web/ts/src/styles/viewer.css"
  echo "}"
} > "$PKG/css/patinae-panels.css"

{
  echo "tag: $TAG"
  echo "commit: $(git -C "$WORK/patinae" rev-parse HEAD)"
  for p in "$HERE"/patches/*.patch; do
    [ -e "$p" ] || continue
    echo "patch: $(basename "$p") $(sha256sum "$p" | cut -d' ' -f1)"
  done
} > "$PKG/wasm/VERSION"

ls -la "$PKG/wasm"
