/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmelasticnet_free: (a: number, b: number) => void;
export const __wbg_wasmpca_free: (a: number, b: number) => void;
export const __wbg_wasmpls_free: (a: number, b: number) => void;
export const __wbg_wasmsoftmax_free: (a: number, b: number) => void;
export const wasmelasticnet_coefficientsWithBias: (a: number) => [number, number];
export const wasmelasticnet_fit: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const wasmelasticnet_new: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasmelasticnet_predict: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wasmelasticnet_setFeatureStats: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasmpca_explainedVarianceRatio: (a: number) => [number, number];
export const wasmpca_fit: (a: number, b: number, c: number, d: number) => [number, number];
export const wasmpca_loadings: (a: number) => [number, number, number, number];
export const wasmpca_nComponents: (a: number) => number;
export const wasmpca_new: (a: number, b: number, c: number) => [number, number, number];
export const wasmpca_scores: (a: number) => [number, number, number, number];
export const wasmpca_setFeatureStats: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasmpca_transform: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wasmpls_bias: (a: number) => number;
export const wasmpls_explainedVariance: (a: number) => [number, number];
export const wasmpls_fit: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const wasmpls_new: (a: number) => [number, number, number];
export const wasmpls_predict: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wasmpls_regressionCoefficients: (a: number) => [number, number];
export const wasmpls_setFeatureStats: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const wasmpls_tScores: (a: number) => [number, number, number, number];
export const wasmpls_uScores: (a: number) => [number, number, number, number];
export const wasmpls_xLoadings: (a: number) => [number, number, number, number];
export const wasmpls_yLoadings: (a: number) => [number, number, number, number];
export const wasmsoftmax_fit: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const wasmsoftmax_lossHistory: (a: number) => [number, number];
export const wasmsoftmax_new: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasmsoftmax_params: (a: number) => [number, number];
export const wasmsoftmax_predict: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wasmsoftmax_setFeatureStats: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
