"""Generate `.kg/docs/COVERAGE.md` — test-gap and doc-gap report per package.

Surfaces which user-facing Features have:
  - zero `IS_TESTED_IN` edges     (test gap)
  - zero incoming `DOCUMENTS` edges  (doc gap)

Run any time after a fresh build: `py .kg/scripts/coverage_report.py`.
"""

from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import urllib.request
import json


SERVER = "http://127.0.0.1:7475"


def q(cypher: str) -> list[dict]:
    req = urllib.request.Request(
        f"{SERVER}/query",
        data=json.dumps({"cypher": cypher}).encode(),
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req) as r:
        body = json.loads(r.read())
    cols = body["columns"]
    return [dict(zip(cols, row)) for row in body["rows"]]


def render() -> str:
    test_gaps = q("""
        MATCH (p:Package)-[:HAS_FEATURE]->(f:Feature)
        WHERE NOT EXISTS { MATCH (f)-[:IS_TESTED_IN]->(:File) }
        RETURN p.name AS pkg, count(f) AS untested ORDER BY untested DESC, pkg
    """)
    doc_gaps = q("""
        MATCH (p:Package)-[:HAS_FEATURE]->(f:Feature)
        WHERE NOT EXISTS { MATCH (:DocPage)-[:DOCUMENTS]->(f) }
          AND f.is_user_facing = true
        RETURN p.name AS pkg, count(f) AS undocumented ORDER BY undocumented DESC, pkg
    """)
    totals = q("MATCH (p:Package)-[:HAS_FEATURE]->(f:Feature) RETURN p.name AS pkg, count(f) AS total")
    total_by_pkg = {row["pkg"]: row["total"] for row in totals}

    impl_total = q("MATCH ()-[r:IS_IMPLEMENTED_IN]->() RETURN count(r) AS n")[0]["n"]
    test_total = q("MATCH ()-[r:IS_TESTED_IN]->() RETURN count(r) AS n")[0]["n"]
    docs_total = q("MATCH (:DocPage)-[r:DOCUMENTS]->(:Feature) RETURN count(r) AS n")[0]["n"]
    feat_count = q("MATCH (f:Feature) RETURN count(f) AS n")[0]["n"]
    feat_uf = q("MATCH (f:Feature) WHERE f.is_user_facing = true RETURN count(f) AS n")[0]["n"]

    lines: list[str] = []
    lines.append("# Coverage report")
    lines.append("")
    lines.append("Auto-generated by `scripts/coverage_report.py`. Surfaces test- and doc-gaps")
    lines.append("at the Feature level.")
    lines.append("")
    lines.append("## Totals")
    lines.append("")
    lines.append(f"- Features: **{feat_count}** total ({feat_uf} user-facing)")
    lines.append(f"- IS_IMPLEMENTED_IN edges: **{impl_total}**")
    lines.append(f"- IS_TESTED_IN edges: **{test_total}**")
    lines.append(f"- DOCUMENTS edges (DocPage → Feature): **{docs_total}**")
    lines.append("")
    lines.append("## Test gaps — features with zero IS_TESTED_IN edges")
    lines.append("")
    lines.append("| Package | Untested features | Total features | % gap |")
    lines.append("|---------|------------------:|---------------:|------:|")
    for row in test_gaps:
        pkg, n = row["pkg"], row["untested"]
        total = total_by_pkg.get(pkg, 0)
        pct = (n / total * 100) if total else 0.0
        lines.append(f"| {pkg} | {n} | {total} | {pct:.0f}% |")
    lines.append("")
    lines.append("## Doc gaps — user-facing features with no DocPage → DOCUMENTS edge")
    lines.append("")
    lines.append("| Package | Undocumented user-facing features |")
    lines.append("|---------|----------------------------------:|")
    for row in doc_gaps:
        lines.append(f"| {row['pkg']} | {row['undocumented']} |")
    lines.append("")
    lines.append("## How to query yourself")
    lines.append("")
    lines.append("```cypher")
    lines.append("// Untested features in a specific package")
    lines.append("MATCH (p:Package {name:'Bio'})-[:HAS_FEATURE]->(f:Feature)")
    lines.append("WHERE NOT EXISTS { MATCH (f)-[:IS_TESTED_IN]->(:File) }")
    lines.append("RETURN f.name, f.interaction_kind")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    out_path = ROOT / "docs" / "COVERAGE.md"
    out_path.write_text(render(), encoding="utf-8")
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
