/** Domain hits as Bio sequence annotations, in the storage Bio's renderer and
 * annotation manager read (Bio's `utils/annotations/annotation-manager.ts`):
 * definitions in the column's `.annotations` tag, per-row hits in the hidden
 * companion column named by the `.annotationColumnName` tag. Re-running
 * replaces this package's annotations (ids starting with `hmm-`) only. */
import * as DG from 'datagrok-api/dg';
import {
  AnnotationCategory, AnnotationVisualType, type SeqAnnotation, type SeqAnnotationHit,
} from '@datagrok-libraries/bio/src/utils/macromolecule/annotations';

export const ANNOTATION_PREFIX = 'hmm-';
/** Bio's `TAGS.annotations` and `TAGS.annotationColumnName` (imported literally:
 * the macromolecule index would pull most of the Bio library into package.js). */
const TAG_ANNOTATIONS = '.annotations';
const TAG_ANNOTATION_COLUMN = '.annotationColumnName';
const PALETTE = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f',
  '#bcbd22', '#17becf', '#393b79', '#637939', '#8c6d31', '#843c39', '#7b4173'];

/** A domain found in one row: 0-based inclusive residue indices (see sequences.ts). */
export interface DomainHitSpan {
  model: string;
  from: number;
  to: number;
  score: number;
}

export interface ModelLabel {
  id: string;
  name: string;
  description: string;
}

/** Replace this package's domain annotations on `column` with `rows` (one list
 * per row); `positions[row][k]` is the monomer position of residue `k`. */
export function setDomainAnnotations(df: DG.DataFrame, column: DG.Column<string>, models: ModelLabel[],
  rows: DomainHitSpan[][], positions: number[][]): void {
  const definitions: SeqAnnotation[] = models.map((m, i) => ({
    id: `${ANNOTATION_PREFIX}${m.id}`,
    name: m.name,
    description: m.description,
    start: null,
    end: null,
    visualType: AnnotationVisualType.Region,
    category: AnnotationCategory.Custom,
    color: PALETTE[i % PALETTE.length],
    sourceScheme: 'HMMER',
    autoGenerated: true,
  }));
  let existing: SeqAnnotation[] = [];
  try {
    existing = JSON.parse(column.getTag(TAG_ANNOTATIONS) || '[]');
  } catch {/* replaced below */}
  const kept = existing.filter((a) => !a.id.startsWith(ANNOTATION_PREFIX));
  column.setTag(TAG_ANNOTATIONS, JSON.stringify([...kept, ...definitions]));

  const companionName = `~${column.name}_annotations`;
  let companion = df.col(companionName) as DG.Column<string> | null;
  if (!companion) {
    companion = df.columns.addNewString(companionName);
    column.setTag(TAG_ANNOTATION_COLUMN, companionName);
  }
  for (let i = 0; i < df.rowCount; i++) {
    let hits: SeqAnnotationHit[] = [];
    try {
      hits = JSON.parse(companion.get(i) || '[]');
    } catch {/* replaced below */}
    hits = hits.filter((h) => !h.annotationId.startsWith(ANNOTATION_PREFIX));
    const at = positions[i] ?? [];
    for (const d of rows[i] ?? []) {
      if (d.to >= at.length) continue;
      hits.push({
        annotationId: `${ANNOTATION_PREFIX}${d.model}`,
        positionIndex: at[d.from],
        endPositionIndex: at[d.to],
        matchedMonomers: '',
        score: d.score,
      });
    }
    companion.set(i, hits.length > 0 ? JSON.stringify(hits) : '', false);
  }
  df.fireValuesChanged();
}
