/** ANARCI numbering of a macromolecule column, shaped for Bio's numbering
 * dialog (`meta.role: antibodyNumbering`; see Bio's CLAUDE.md, "Adding a New
 * Antibody Numbering Engine"): `position_names`, `chain_type`,
 * `annotations_json`, `numbering_detail`, `numbering_map`, plus ANARCI's
 * chain, species, germline and E-value columns. */
import * as DG from 'datagrok-api/dg';
import {
  ChainType as RegionChain, NumberingScheme, SCHEME_REGIONS, type SchemeRegionDef,
} from '@datagrok-libraries/bio/src/utils/macromolecule/numbering-schemes';
import type {AnarciOptions, DomainDetails, SequenceResult} from './hmmer/anarci/anarci.ts';
import type {Numbering, Scheme} from './hmmer/anarci/types.ts';
import {HmmerPool} from './pool';
import {columnResidues} from './sequences';

export const SCHEMES: Scheme[] = ['imgt', 'kabat', 'chothia', 'martin', 'aho', 'wolfguy'];
const SCHEME_LABELS: Record<Scheme, string> = {
  imgt: 'IMGT', kabat: 'Kabat', chothia: 'Chothia', martin: 'Martin', aho: 'AHo', wolfguy: 'Wolfguy',
};
export const CHAIN_NAMES: Record<string, string> = {
  H: 'Heavy', K: 'Kappa', L: 'Lambda', A: 'Alpha', B: 'Beta', G: 'Gamma', D: 'Delta',
};
/** Bio's `chain_type` groups: Heavy / Light; TCR chains by name. */
const CHAIN_GROUPS: Record<string, string> = {
  H: 'Heavy', K: 'Light', L: 'Light', A: 'Alpha', B: 'Beta', G: 'Gamma', D: 'Delta',
};

/** The residues Bio's dialog indexes: gaps (`-`, `.`) removed, upper case. */
export function extractSequence(raw: string | null | undefined): string {
  return (raw ?? '').replace(/[-.]/g, '').toUpperCase();
}

/** Run ANARCI on a column in the worker pool (numbering indices refer to the
 * gap-free residues, as Bio's numbering dialog expects). */
export async function numberColumn(pool: HmmerPool, column: DG.Column<string>, options: AnarciOptions):
  Promise<{sequences: string[]; results: SequenceResult[]}> {
  const sequences = (await columnResidues(column)).residues;
  const results = await pool.anarci(sequences.map((s, i) => [String(i), s]), options);
  return {sequences, results};
}

const code = ([number, insertion]: [number, string]) => `${number}${insertion.trim()}`;

/** Region definitions (FR/CDR with scheme position bounds) for a scheme and ANARCI chain. */
function regionDefs(scheme: Scheme, chain: string): {name: string; type: 'FR' | 'CDR'; from: number; to: number}[] {
  if (scheme === 'wolfguy') {
    // Wolfguy encodes regions in the number: hundreds = region, x01-x50 framework, x51-x99 CDR.
    const first = chain === 'H' ? 1 : 5;
    const names = ['FR1', 'CDR1', 'FR2', 'CDR2', 'FR3', 'CDR3', 'FR4'];
    return names.map((name, i) => {
      const hundred = (first + Math.floor(i / 2)) * 100;
      const cdr = i % 2 === 1;
      return {name, type: cdr ? 'CDR' : 'FR', from: hundred + (cdr ? 51 : 1), to: hundred + (cdr ? 99 : 50)};
    });
  }
  const key = {imgt: NumberingScheme.IMGT, kabat: NumberingScheme.Kabat, chothia: NumberingScheme.Chothia,
    martin: NumberingScheme.Chothia, aho: NumberingScheme.AHo}[scheme];
  const regionChain = chain === 'K' ? RegionChain.Light_Kappa : chain === 'L' ? RegionChain.Light_Lambda :
    RegionChain.Heavy;
  const defs: SchemeRegionDef[] = SCHEME_REGIONS[key]?.[regionChain] ?? [];
  return defs.map((r) => ({name: r.name, type: r.type, from: parseInt(r.startPosition), to: parseInt(r.endPosition)}));
}

/** Per-row region annotations whose bounds are the first and last numbered
 * positions of each region in this row, so gapped boundaries still resolve. */
function rowRegions(scheme: Scheme, chain: string, positions: [number, string][]): object[] {
  const label = SCHEME_LABELS[scheme];
  const group = CHAIN_GROUPS[chain] ?? chain;
  const regions: object[] = [];
  for (const def of regionDefs(scheme, chain)) {
    const inside = positions.filter(([n]) => n >= def.from && n <= def.to);
    if (inside.length === 0) continue;
    regions.push({
      id: `${scheme}-${group}-${def.name}`.toLowerCase(),
      name: def.name,
      description: `${def.name} (${label} ${def.from}-${def.to})`,
      start: code(inside[0]),
      end: code(inside[inside.length - 1]),
      visualType: 'region',
      category: 'structure',
      sourceScheme: label,
      autoGenerated: true,
    });
  }
  return regions;
}

interface RowNumbering {
  positions: [number, string][];
  detail: {position: string; aa: string}[];
  map: Record<string, number>;
}

/** Residue positions of one numbered domain; `start` is its first sequence index. */
function rowNumbering(numbering: Numbering, start: number | null): RowNumbering {
  const positions: [number, string][] = [];
  const detail: {position: string; aa: string}[] = [];
  const map: Record<string, number> = {};
  let index = start ?? 0;
  for (const [position, aa] of numbering) {
    if (aa === '-') continue;
    positions.push(position);
    detail.push({position: code(position), aa});
    map[code(position)] = index++;
  }
  return {positions, detail, map};
}

/** The numbering DataFrame: one row per input sequence; the first (N-terminal)
 * numbered domain of each sequence is reported. */
export function numberingFrame(scheme: Scheme, results: SequenceResult[]): DG.DataFrame {
  const n = results.length;
  const string = (name: string) => DG.Column.fromType(DG.COLUMN_TYPE.STRING, name, n);
  // E-values reach 1e-60 and identities are exact ratios, so floats are doubles.
  const double = (name: string) => DG.Column.fromFloat64Array(name, new Float64Array(n).fill(DG.FLOAT_NULL));
  const cols = {
    position_names: string('position_names'), chain_type: string('chain_type'),
    annotations_json: string('annotations_json'), numbering_detail: string('numbering_detail'),
    numbering_map: string('numbering_map'), chain: string('chain'), species: string('species'),
    v_gene: string('v_gene'), j_gene: string('j_gene'),
    v_identity: double('v_identity'), j_identity: double('j_identity'),
    evalue: double('evalue'), bitscore: double('bitscore'),
    domains: DG.Column.fromType(DG.COLUMN_TYPE.INT, 'domains', n),
    error: string('error'),
  };
  for (let i = 0; i < n; i++) {
    const r = results[i];
    cols.annotations_json.set(i, '[]', false);
    cols.domains.set(i, r.numbered?.length ?? 0, false);
    if (r.error) cols.error.set(i, r.error, false);
    if (!r.numbered || !r.details) continue;
    const [numbering, start] = r.numbered[0];
    const details: DomainDetails = r.details[0];
    // ANARCI recognizes the domain but returns an empty numbering when a CDR
    // exceeds what the scheme can number; chain, species and germlines remain.
    const row = rowNumbering(numbering, start);
    if (row.positions.length > 0) {
      cols.position_names.set(i, row.detail.map((d) => d.position).join(', '), false);
      cols.chain_type.set(i, CHAIN_GROUPS[details.chain_type] ?? '', false);
      cols.annotations_json.set(i, JSON.stringify(rowRegions(scheme, details.chain_type, row.positions)), false);
      cols.numbering_detail.set(i, JSON.stringify(row.detail), false);
      cols.numbering_map.set(i, JSON.stringify(row.map), false);
    }
    cols.chain.set(i, CHAIN_NAMES[details.chain_type] ?? details.chain_type, false);
    cols.species.set(i, details.species, false);
    cols.evalue.set(i, details.evalue, false);
    cols.bitscore.set(i, details.bitscore, false);
    const germlines = details.germlines;
    if (germlines && 'v_gene' in germlines) {
      if (germlines.v_gene[0]) {
        cols.v_gene.set(i, germlines.v_gene[0][1], false);
        cols.v_identity.set(i, germlines.v_gene[1], false);
      }
      if (germlines.j_gene[0]) {
        cols.j_gene.set(i, germlines.j_gene[0][1], false);
        cols.j_identity.set(i, germlines.j_gene[1], false);
      }
    }
  }
  cols.evalue.meta.format = 'scientific';
  for (const col of [cols.v_identity, cols.j_identity]) col.meta.format = '0.00';
  return DG.DataFrame.fromColumns(Object.values(cols));
}

/** ANARCI's chain types per scheme (as its command line: TCRs only in IMGT and AHo). */
export function allowedChains(scheme: Scheme): string[] {
  return scheme === 'imgt' || scheme === 'aho' ? ['H', 'K', 'L', 'A', 'B', 'G', 'D'] : ['H', 'K', 'L'];
}

/** Species choices: ANARCI's default (human and mouse preferred), all, or one species. */
export const SPECIES_CHOICES = ['human, mouse', 'all', 'human', 'mouse', 'rat', 'rabbit', 'rhesus', 'pig', 'alpaca',
  'cow'];

export function speciesOption(choice: string | null | undefined): string[] | null {
  if (!choice || choice === 'human, mouse') return ['human', 'mouse'];
  if (choice === 'all') return null;
  return [choice];
}
