/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  /**
  Opens Minitab Worksheet file
  */
  export async function importMwx(bytes: any ): Promise<any> {
    return await grok.functions.call('Minitab:ImportMwx', { bytes });
  }

  export async function previewMwx(file: DG.FileInfo ): Promise<DG.View> {
    return await grok.functions.call('Minitab:PreviewMwx', { file });
  }

  /**
  Opens Minitab Project file
  */
  export async function importMpx(bytes: any ): Promise<any> {
    return await grok.functions.call('Minitab:ImportMpx', { bytes });
  }

  export async function previewMpx(file: DG.FileInfo ): Promise<DG.View> {
    return await grok.functions.call('Minitab:PreviewMpx', { file });
  }
}
