/**
 * Test helpers: fixture loading + tolerance comparison.
 *
 * Fixtures are JSON files generated by `scripts/generate-fixtures.py` from
 * the original Python `validate_*.py` suite. Each file contains:
 *
 *   { metadata: { tolerances: {...} }, cases: [{...}], threshold_cases?: [{...}] }
 */

import * as fs from 'fs';
import * as path from 'path';

export interface FixtureMetadata {
  source: string;
  generated_at: string;
  python_version: string;
  numpy_version: string;
  scipy_version: string;
  tolerances: {p_value: number; statistic: number; [key: string]: number};
}

export interface Fixture<TCase> {
  metadata: FixtureMetadata;
  cases: TCase[];
  threshold_cases?: TCase[];
}

const FIXTURES_DIR = path.join(__dirname, 'fixtures');

/** Load a JSON fixture by base name (without `.json`). */
export function loadFixture<TCase>(name: string): Fixture<TCase> {
  const file = path.join(FIXTURES_DIR, `${name}.json`);
  return JSON.parse(fs.readFileSync(file, 'utf-8'));
}

/** Convert a fixture array (with `null` sentinels for NaN) to a Float64Array. */
export function arrayWithNaN(values: readonly (number | null)[]): Float64Array {
  const out = new Float64Array(values.length);
  for (let i = 0; i < values.length; i++)
    out[i] = values[i] === null ? NaN : (values[i] as number);
  return out;
}

/**
 * Decode a JSON-fixture numeric value: `"NaN"` → `NaN`, `"Infinity"` →
 * `Infinity`, `"-Infinity"` → `-Infinity`, `null` passes through, raw
 * numbers pass through.
 */
export function decodeNum(v: number | string | null | undefined): number | null {
  if (v === null || v === undefined) return null;
  if (typeof v === 'string') {
    if (v === 'NaN') return NaN;
    if (v === 'Infinity') return Infinity;
    if (v === '-Infinity') return -Infinity;
    throw new Error(`Unknown sentinel: ${v}`);
  }
  return v;
}

/**
 * Assert two values match within tolerance, with `null` parity (both null
 * passes; one null fails). NaN parity supported via the `nanIsEqual` flag.
 */
export function expectClose(
  actual: number | null,
  expected: number | null,
  tol: number,
  label: string,
  nanIsEqual = false,
): void {
  if (expected === null && actual === null) return;
  if (expected === null || actual === null)
    throw new Error(`${label}: actual=${actual}, expected=${expected} (one is null)`);
  if (Number.isNaN(expected as number) && Number.isNaN(actual as number)) {
    if (nanIsEqual) return;
    throw new Error(`${label}: both NaN but nanIsEqual=false`);
  }
  if (Number.isNaN(expected as number) || Number.isNaN(actual as number))
    throw new Error(`${label}: NaN mismatch — actual=${actual}, expected=${expected}`);
  const diff = Math.abs((actual as number) - (expected as number));
  if (diff >= tol) {
    throw new Error(
      `${label}: |${actual} − ${expected}| = ${diff.toExponential(3)} ≥ ${tol}`,
    );
  }
}
