/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function retroSynthesisPath(smiles: string ): Promise<any> {
    return await grok.functions.call(':RetroSynthesisPath', { smiles });
  }

  export async function retrosynthesisTopMenu(): Promise<void> {
    return await grok.functions.call(':RetrosynthesisTopMenu', {});
  }

  /**
  Generate retrosynthesis paths
  */
  export async function retrosynthesisDemo(): Promise<void> {
    return await grok.functions.call(':RetrosynthesisDemo', {});
  }
}
