export const SDTM_VERSION = '1.7';
export const SDTMIG_VERSION = '3.3';

export const classes = {
  'Events': {
    'AE': 'Adverse Events',
    'CE': 'Clinical Events',
    'DS': 'Disposition',
    'DV': 'Protocol Deviations',
    'HO': 'Healthcare Encounters',
    'MH': 'Medical History',
  },
  'Findings': {
    'CV': 'Cardiovascular System Findings',
    'DA': 'Drug Accountability',
    'DD': 'Death Details',
    'EG': 'ECG Test Results',
    'FA': 'Findings About Events or Interventions',
    'FT': 'Functional Tests',
    'IE': 'Inclusion/Exclusion Criteria Not Met',
    'IS': 'Immunogenicity Specimen Assessments',
    'LB': 'Laboratory Test Results',
    'MB': 'Microbiology Specimen',
    'MI': 'Microscopic Findings',
    'MK': 'Musculoskeletal System Findings',
    'MO': 'Morphology',
    'MS': 'Microbiology Susceptibility',
    'NV': 'Nervous System Findings',
    'OE': 'Ophthalmic Examinations',
    'PC': 'Pharmacokinetics Concentrations',
    'PE': 'Physical Examination',
    'PP': 'Pharmacokinetics Parameters',
    'QS': 'Questionnaires',
    'RE': 'Respiratory System Findings',
    'RP': 'Reproductive System Findings',
    'RS': 'Disease Response and Clin Classification',
    'SC': 'Subject Characteristics',
    'SR': 'Skin Response',
    'SS': 'Subject Status',
    'TR': 'Tumor/Lesion Results',
    'TU': 'Tumor/Lesion Identification',
    'UR': 'Urinary System Findings',
    'VS': 'Vital Signs',
  },
  'Interventions': {
    'AG': 'Procedure Agents',
    'CM': 'Concomitant/Prior Medications',
    'EC': 'Exposure as Collected',
    'EX': 'Exposure',
    'ML': 'Meal Data',
    'PR': 'Procedures',
    'SU': 'Substance Use',
  },
  'Special Purpose': {
    'CO': 'Comments',
    'DM': 'Demographics',
    'SE': 'Subject Elements',
    'SM': 'Subject Disease Milestones',
    'SV': 'Subject Visits',
  },
  'Trial Design': {
    'TA': 'Trial Arms',
    'TD': 'Trial Disease Assessments',
    'TE': 'Trial Elements',
    'TI': 'Trial Inclusion/Exclusion Criteria',
    'TM': 'Trial Disease Milestones',
    'TS': 'Trial Summary',
    'TV': 'Trial Visits',
  },
  'Relationships': {
    'RELREC': 'Related Records',
    'RELSUB': 'Related Subjects',
  },
};

export const domains = {
  ae: {
    'STUDYID': 'Study Identifier',
    'DOMAIN': 'Domain Abbreviation',
    'USUBJID': 'Unique Subject Identifier',
    'AESEQ': 'Sequence Number',
    'AEGRPID': 'Group ID',
    'AEREFID': 'Reference ID',
    'AESPID': 'Sponsor-Defined Identifier',
    'AETERM': 'Reported Term for the Adverse Event',
    'AEMODIFY': 'Modified Reported Term',
    'AELLT': 'Lowest Level Term',
    'AELLTCD': 'Lowest Level Term Code',
    'AEDECOD': 'Dictionary-Derived Term',
    'AEPTCD': 'Preferred Term Code',
    'AEHLT': 'High Level Term',
    'AEHLTCD': 'High Level Term Code',
    'AEHLGT': 'High Level Group Term',
    'AEHLGTCD': 'High Level Group Term Code',
    'AECAT': 'Category for Adverse Event',
    'AESCAT': 'Subcategory for Adverse Event',
    'AEPRESP': 'Pre-Specified Adverse Event',
    'AEBODSYS': 'Body System or Organ Class',
    'AEBDSYCD': 'Body System or Organ Class Code',
    'AESOC': 'Primary System Organ Class',
    'AESOCCD': 'Primary System Organ Class Code',
    'AELOC': 'Location of Event',
    'AESEV': 'Severity/Intensity',
    'AESER': 'Serious Event',
    'AEACN': 'Action Taken with Study Treatment',
    'AEACNOTH': 'Other Action Taken',
    'AEREL': 'Causality',
    'AERELNST': 'Relationship to Non-Study Treatment',
    'AEPATT': 'Pattern of Adverse Event',
    'AEOUT': 'Outcome of Adverse Event',
    'AESCAN': 'Involves Cancer',
    'AESCONG': 'Congenital Anomaly or Birth Defect',
    'AESDISAB': 'Persist or Signif Disability/Incapacity',
    'AESDTH': 'Results in Death',
    'AESHOSP': 'Requires or Prolongs Hospitalization',
    'AESLIFE': 'Is Life Threatening',
    'AESOD': 'Occurred with Overdose',
    'AESMIE': 'Other Medically Important Serious Event',
    'AECONTRT': 'Concomitant or Additional Trtmnt Given',
    'AETOXGR': 'Standard Toxicity Grade',
    'TAETORD': 'Planned Order of Element within Arm',
    'EPOCH': 'Epoch',
    'AESTDTC': 'Start Date/Time of Adverse Event',
    'AEENDTC': 'End Date/Time of Adverse Event',
    'AESTDY': 'Study Day of Start of Adverse Event',
    'AEENDY': 'Study Day of End of Adverse Event',
    'AEDUR': 'Duration of Adverse Event',
    'AEENRF': 'End Relative to Reference Period',
    'AEENRTPT': 'End Relative to Reference Time Point',
    'AEENTPT': 'End Reference Time Point',
  },
  cm: {
    'STUDYID': 'Study Identifier',
    'DOMAIN': 'Domain Abbreviation',
    'USUBJID': 'Unique Subject Identifier',
    'CMSEQ': 'Sequence Number',
    'CMGRPID': 'Group ID',
    'CMSPID': 'Sponsor-Defined Identifier',
    'CMTRT': 'Reported Name of Drug, Med, or Therapy',
    'CMMODIFY': 'Modified Reported Name',
    'CMDECOD': 'Standardized Medication Name',
    'CMCAT': 'Category for Medication',
    'CMSCAT': 'Subcategory for Medication',
    'CMPRESP': 'CM Pre-specified',
    'CMOCCUR': 'CM Occurrence',
    'CMSTAT': 'Completion Status',
    'CMREASND': 'Reason Medication Not Collected',
    'CMINDC': 'Indication',
    'CMCLAS': 'Medication Class',
    'CMCLASCD': 'Medication Class Code',
    'CMDOSE': 'Dose per Administration',
    'CMDOSTXT': 'Dose Description',
    'CMDOSU': 'Dose Units',
    'CMDOSFRM': 'Dose Form',
    'CMDOSFRQ': 'Dosing Frequency per Interval',
    'CMDOSTOT': 'Total Daily Dose',
    'CMDOSRGM': 'Intended Dose Regimen',
    'CMROUTE': 'Route of Administration',
    'CMADJ': 'Reason for Dose Adjustment',
    'CMRSDISC': 'Reason the Intervention Was Discontinued',
    'TAETORD': 'Planned Order of Element within Arm',
    'EPOCH': 'Epoch',
    'CMSTDTC': 'Start Date/Time of Medication',
    'CMENDTC': 'End Date/Time of Medication',
    'CMSTDY': 'Study Day of Start of Medication',
    'CMENDY': 'Study Day of End of Medication',
    'CMDUR': 'Duration',
    'CMSTRF': 'Start Relative to Reference Period',
    'CMENRF': 'End Relative to Reference Period',
    'CMSTRTPT': 'Start Relative to Reference Time Point',
    'CMSTTPT': 'Start Reference Time Point',
    'CMENRTPT': 'End Relative to Reference Time Point',
    'CMENTPT': 'End Reference Time Point',
  },
  dm: {
    'STUDYID': 'Study Identifier',
    'DOMAIN': 'Domain Abbreviation',
    'USUBJID': 'Unique Subject Identifier',
    'SUBJID': 'Subject Identifier for the Study',
    'RFSTDTC': 'Subject Reference Start Date/Time',
    'RFENDTC': 'Subject Reference End Date/Time',
    'RFXSTDTC': 'Date/Time of First Study Treatment',
    'RFXENDTC': 'Date/Time of Last Study Treatment',
    'RFICDTC': 'Date/Time of Informed Consent',
    'RFPENDTC': 'Date/Time of End of Participation',
    'DTHDTC': 'Date/Time of Death',
    'DTHFL': 'Subject Death Flag',
    'SITEID': 'Study Site Identifier',
    'INVID': 'Investigator Identifier',
    'INVNAM': 'Investigator Name',
    'BRTHDTC': 'Date/Time of Birth',
    'AGE': 'Age',
    'AGEU': 'Age Units',
    'SEX': 'Sex',
    'RACE': 'Race',
    'ETHNIC': 'Ethnicity',
    'ARMCD': 'Planned Arm Code',
    'ARM': 'Description of Planned Arm',
    'ACTARMCD': 'Actual Arm Code',
    'ACTARM': 'Description of Actual Arm',
    'ARMNRS': 'Reason Arm and/or Actual Arm is Null',
    'ACTARMUD': 'Description of Unplanned Actual Arm',
    'COUNTRY': 'Country',
    'DMDTC': 'Date/Time of Collection',
    'DMDY': 'Study Day of Collection',
  },
  ex: {
    'STUDYID': 'Study Identifier',
    'DOMAIN': 'Domain Abbreviation',
    'USUBJID': 'Unique Subject Identifier',
    'EXSEQ': 'Sequence Number',
    'EXGRPID': 'Group ID',
    'EXREFID': 'Reference ID',
    'EXSPID': 'Sponsor-Defined Identifier',
    'EXLNKID': 'Link ID',
    'EXLNKGRP': 'Link Group ID',
    'EXTRT': 'Name of Treatment',
    'EXCAT': 'Category of Treatment',
    'EXSCAT': 'Subcategory of Treatment',
    'EXDOSE': 'Dose',
    'EXDOSTXT': 'Dose Description',
    'EXDOSU': 'Dose Units',
    'EXDOSFRM': 'Dose Form',
    'EXDOSFRQ': 'Dosing Frequency per Interval',
    'EXDOSRGM': 'Intended Dose Regimen',
    'EXROUTE': 'Route of Administration',
    'EXLOT': 'Lot Number',
    'EXLOC': 'Location of Dose Administration',
    'EXLAT': 'Laterality',
    'EXDIR': 'Directionality',
    'EXFAST': 'Fasting Status',
    'EXADJ': 'Reason for Dose Adjustment',
    'TAETORD': 'Planned Order of Element within Arm',
    'EPOCH': 'Epoch',
    'EXSTDTC': 'Start Date/Time of Treatment',
    'EXENDTC': 'End Date/Time of Treatment',
    'EXSTDY': 'Study Day of Start of Treatment',
    'EXENDY': 'Study Day of End of Treatment',
    'EXDUR': 'Duration of Treatment',
    'EXTPT': 'Planned Time Point Name',
    'EXTPTNUM': 'Planned Time Point Number',
    'EXELTM': 'Planned Elapsed Time from Time Point Ref',
    'EXTPTREF': 'Time Point Reference',
    'EXRFTDTC': 'Date/Time of Reference Time Point',
  },
  lb: {
    'STUDYID': 'Study Identifier',
    'DOMAIN': 'Domain Abbreviation',
    'USUBJID': 'Unique Subject Identifier',
    'LBSEQ': 'Sequence Number',
    'LBGRPID': 'Group ID',
    'LBREFID': 'Specimen ID',
    'LBSPID': 'Sponsor-Defined Identifier',
    'LBTESTCD': 'Lab Test or Examination Short Name',
    'LBTEST': 'Lab Test or Examination Name',
    'LBCAT': 'Category for Lab Test',
    'LBSCAT': 'Subcategory for Lab Test',
    'LBORRES': 'Result or Finding in Original Units',
    'LBORRESU': 'Original Units',
    'LBORNRLO': 'Reference Range Lower Limit in Orig Unit',
    'LBORNRHI': 'Reference Range Upper Limit in Orig Unit',
    'LBSTRESC': 'Character Result/Finding in Std Format',
    'LBSTRESN': 'Numeric Result/Finding in Standard Units',
    'LBSTRESU': 'Standard Units',
    'LBSTNRLO': 'Reference Range Lower Limit-Std Units',
    'LBSTNRHI': 'Reference Range Upper Limit-Std Units',
    'LBSTNRC': 'Reference Range for Char Rslt-Std Units',
    'LBSTREFC': 'Reference Result in Standard Format',
    'LBNRIND': 'Reference Range Indicator',
    'LBSTAT': 'Completion Status',
    'LBREASND': 'Reason Test Not Done',
    'LBNAM': 'Vendor Name',
    'LBLOINC': 'LOINC Code',
    'LBSPEC': 'Specimen Type',
    'LBSPCCND': 'Specimen Condition',
    'LBMETHOD': 'Method of Test or Examination',
    'LBLOBXFL': 'Last Observation Before Exposure Flag',
    'LBBLFL': 'Baseline Flag',
    'LBFAST': 'Fasting Status',
    'LBDRVFL': 'Derived Flag',
    'LBTOX': 'Toxicity',
    'LBTOXGR': 'Standard Toxicity Grade',
    'VISITNUM': 'Visit Number',
    'VISIT': 'Visit Name',
    'VISITDY': 'Planned Study Day of Visit',
    'TAETORD': 'Planned Order of Element within Arm',
    'EPOCH': 'Epoch',
    'LBDTC': 'Date/Time of Specimen Collection',
    'LBENDTC': 'End Date/Time of Specimen Collection',
    'LBDY': 'Study Day of Specimen Collection',
    'LBENDY': 'Study Day of End of Observation',
    'LBTPT': 'Planned Time Point Name',
    'LBTPTNUM': 'Planned Time Point Number',
    'LBELTM': 'Planned Elapsed Time from Time Point Ref',
    'LBTPTREF': 'Time Point Reference',
    'LBRFTDTC': 'Date/Time of Reference Time Point',
  },
};
