import { ACT_TRT_ARM, AE_DECOD_TERM, AE_TERM, CON_MED_TRT, INV_DRUG_NAME, MH_TERM } from "./columns-constants";
import { ADVERSE_EVENTS_VIEW_NAME, AE_BROWSER_VIEW_NAME, AE_RISK_ASSESSMENT_VIEW_NAME, CORRELATIONS_VIEW_NAME, DISTRIBUTIONS_VIEW_NAME, LABORATORY_VIEW_NAME, MEDICAL_HISTORY_VIEW_NAME, PATIENT_PROFILE_VIEW_NAME, STUDY_CONFIGURATIN_VIEW_NAME, SUMMARY_VIEW_NAME, SURVIVAL_ANALYSIS_VIEW_NAME, TIMELINES_VIEW_NAME, TIME_PROFILE_VIEW_NAME, TREE_MAP_VIEW_NAME, VALIDATION_VIEW_NAME, VISITS_VIEW_NAME } from "./view-names-constants";


export const TRT_ARM_FIELD = 'TREATMENT_ARM';
export const AE_TERM_FIELD = 'AE_TERM';
export const INV_DRUG_NAME_FIELD = 'INV_DRUG_NAME';
export const CON_MED_NAME_FIELD = 'CON_MED_NAME';
export const MH_TERM_FIELD = 'MH_TERM';

export const VIEWS_CONFIG = {
    [SUMMARY_VIEW_NAME]: {
        [TRT_ARM_FIELD]: ACT_TRT_ARM
    },
    [TIMELINES_VIEW_NAME]: {
        [TRT_ARM_FIELD]: ACT_TRT_ARM,
        [AE_TERM_FIELD]: AE_TERM,
        [INV_DRUG_NAME_FIELD]: INV_DRUG_NAME,
        [CON_MED_NAME_FIELD]: CON_MED_TRT,

    },
    [LABORATORY_VIEW_NAME]: {
        [TRT_ARM_FIELD]: ACT_TRT_ARM
    },
    [PATIENT_PROFILE_VIEW_NAME]: {
        [AE_TERM_FIELD]: AE_TERM,
        [INV_DRUG_NAME_FIELD]: INV_DRUG_NAME,
        [CON_MED_NAME_FIELD]: CON_MED_TRT,
    },
    [ADVERSE_EVENTS_VIEW_NAME]: {
        [TRT_ARM_FIELD]: ACT_TRT_ARM,
        [AE_TERM_FIELD]: AE_DECOD_TERM,
    },
    [AE_RISK_ASSESSMENT_VIEW_NAME]: {
        [TRT_ARM_FIELD]: ACT_TRT_ARM,
        [AE_TERM_FIELD]: AE_TERM
    },
    [SURVIVAL_ANALYSIS_VIEW_NAME]: {
        [TRT_ARM_FIELD]: ACT_TRT_ARM
    },
    [DISTRIBUTIONS_VIEW_NAME]: {
        [TRT_ARM_FIELD]: ACT_TRT_ARM
    },
    [CORRELATIONS_VIEW_NAME]: {

    },
    [TIME_PROFILE_VIEW_NAME]: {
        [TRT_ARM_FIELD]: ACT_TRT_ARM
    },
    [TREE_MAP_VIEW_NAME]: {
        [TRT_ARM_FIELD]: ACT_TRT_ARM
    },
    [MEDICAL_HISTORY_VIEW_NAME]: {
        [MH_TERM_FIELD]: MH_TERM
    },
    [VISITS_VIEW_NAME]: {
        [TRT_ARM_FIELD]: ACT_TRT_ARM,
        [AE_TERM_FIELD]: AE_TERM,
        [INV_DRUG_NAME_FIELD]: INV_DRUG_NAME,
        [CON_MED_NAME_FIELD]: CON_MED_TRT,
    },
    [STUDY_CONFIGURATIN_VIEW_NAME]: {

    },
    [VALIDATION_VIEW_NAME]: {

    },
    [AE_BROWSER_VIEW_NAME]: {
        [TRT_ARM_FIELD]: ACT_TRT_ARM,
        [AE_TERM_FIELD]: AE_TERM
    }
}