/* AUTO-GENERATED by tools/generate-control-comparisons-fixtures.py - do not edit by hand.
 *
 * External references:
 *   - scipy.stats.dunnett                      -> Dunnett statistic + adjusted p
 *   - scipy.stats.ttest_ind(equal_var=False)   -> Welch t, df, raw p, CI on the mean diff
 *   - statsmodels multipletests(method='holm') -> Holm over the k-1 control-vs-each p's
 *
 *   numpy 2.4.3 | scipy 1.17.1 | statsmodels 0.14.6
 *   python 3.13.12 | generated 2026-06-03T07:35:38.334564+00:00
 *
 * Regenerate from packages/EDA with the SEND-TEST env:
 *   <env>/python.exe tools/generate-control-comparisons-fixtures.py
 */

/* eslint-disable */

export const ALPHA = 0.05;

export interface DunnettExpected {statistic: number; pValueAdj: number;}
export interface HolmWelchExpected {
  meanDiff: number; statistic: number; df: number;
  pValueRaw: number; pValueAdj: number; ciLow: number; ciHigh: number; hedgesG: number;
}
export interface ControlComparisonsFixture {
  name: string;
  control: number[];
  treated: number[][];
  dunnett: DunnettExpected[];
  holmWelch: HolmWelchExpected[];
}

export const FIXTURES: ControlComparisonsFixture[] = [
  {
    "name": "[Dunnett 1955] blood counts",
    "control": [
      7.4,
      8.5,
      7.2,
      8.24,
      9.84,
      8.32
    ],
    "treated": [
      [
        9.76,
        8.8,
        7.68,
        9.36
      ],
      [
        12.8,
        9.68,
        12.16,
        9.2,
        10.55
      ]
    ],
    "dunnett": [
      {
        "statistic": 0.8570321259343803,
        "pValueAdj": 0.6200707342637051
      },
      {
        "statistic": 3.693752311235726,
        "pValueAdj": 0.005826516237714796
      }
    ],
    "holmWelch": [
      {
        "meanDiff": 0.6499999999999986,
        "statistic": 1.0963745079232525,
        "df": 6.7758809316942905,
        "pValueRaw": 0.31034466666098365,
        "ciLow": -0.7613533565627968,
        "ciHigh": 2.061353356562794,
        "hedgesG": 0.6233611465235627,
        "pValueAdj": 0.31034466666098365
      },
      {
        "meanDiff": 2.6279999999999983,
        "statistic": 3.3053143622690477,
        "df": 6.333034350606968,
        "pValueRaw": 0.01505982907786063,
        "ciLow": 0.7070340249846427,
        "ciHigh": 4.548965975015354,
        "hedgesG": 1.7897225709422269,
        "pValueAdj": 0.03011965815572126
      }
    ]
  },
  {
    "name": "balanced, 3 treated",
    "control": [
      1.0,
      2.0,
      3.0,
      2.5,
      1.5
    ],
    "treated": [
      [
        3.0,
        4.0,
        5.0,
        4.5
      ],
      [
        5.0,
        6.0,
        7.0,
        6.5
      ],
      [
        7.0,
        8.0,
        9.0,
        8.5
      ]
    ],
    "dunnett": [
      {
        "statistic": 3.7940263593345884,
        "pValueAdj": 0.006091500668091165
      },
      {
        "statistic": 7.364874697531849,
        "pValueAdj": 9.465229999339186e-06
      },
      {
        "statistic": 10.93572303572911,
        "pValueAdj": 3.4240084101355706e-09
      }
    ],
    "holmWelch": [
      {
        "meanDiff": 2.125,
        "statistic": 3.833394742814427,
        "df": 6.302353651176825,
        "pValueRaw": 0.007852719505041753,
        "ciLow": 0.7842004551727213,
        "ciHigh": 3.465799544827279,
        "hedgesG": 2.260273609589547,
        "pValueAdj": 0.007852719505041753
      },
      {
        "meanDiff": 4.125,
        "statistic": 7.4412956772280054,
        "df": 6.302353651176825,
        "pValueRaw": 0.0002404659202038211,
        "ciLow": 2.784200455172721,
        "ciHigh": 5.465799544827279,
        "hedgesG": 4.387589948026768,
        "pValueAdj": 0.0004809318404076422
      },
      {
        "meanDiff": 6.125,
        "statistic": 11.049196611641584,
        "df": 6.302353651176825,
        "pValueRaw": 2.3353045069891925e-05,
        "ciLow": 4.784200455172721,
        "ciHigh": 7.465799544827279,
        "hedgesG": 6.514906286463989,
        "pValueAdj": 7.005913520967577e-05
      }
    ]
  },
  {
    "name": "unbalanced, 2 treated",
    "control": [
      10.0,
      11.0,
      9.5,
      10.5,
      10.2,
      11.3,
      9.8
    ],
    "treated": [
      [
        12.0,
        11.5,
        13.0
      ],
      [
        14.0,
        15.0,
        14.5,
        13.5
      ]
    ],
    "dunnett": [
      {
        "statistic": 3.9784013687041444,
        "pValueAdj": 0.004212473213860424
      },
      {
        "statistic": 9.34453984503784,
        "pValueAdj": 1.8164189143909937e-06
      }
    ],
    "holmWelch": [
      {
        "meanDiff": 1.8380952380952387,
        "statistic": 3.6449171884618377,
        "df": 3.3162790406416565,
        "pValueRaw": 0.03012243700520494,
        "ciLow": 0.3164279150082958,
        "ciHigh": 3.3597625611821815,
        "hedgesG": 1.9534108135663144,
        "pValueAdj": 0.03012243700520494
      },
      {
        "meanDiff": 3.9214285714285726,
        "statistic": 9.682374038919848,
        "df": 6.384644421604948,
        "pValueRaw": 4.753739379366951e-05,
        "ciLow": 2.944706384752858,
        "ciHigh": 4.898150758104287,
        "hedgesG": 5.319716898821222,
        "pValueAdj": 9.507478758733902e-05
      }
    ]
  },
  {
    "name": "k=5 dose-response",
    "control": [
      5.0,
      5.2,
      4.8,
      5.1,
      4.9,
      5.05
    ],
    "treated": [
      [
        9.0,
        9.5,
        8.5,
        9.2,
        8.8,
        9.1
      ],
      [
        6.0,
        6.3,
        5.7,
        6.1,
        5.9,
        6.05
      ],
      [
        5.6,
        5.9,
        5.3,
        5.7,
        5.5,
        5.65
      ],
      [
        5.3,
        5.5,
        5.1,
        5.4,
        5.2,
        5.35
      ]
    ],
    "dunnett": [
      {
        "statistic": 31.732761314901744,
        "pValueAdj": 0.0
      },
      {
        "statistic": 7.916697209538889,
        "pValueAdj": 3.2727598020532156e-07
      },
      {
        "statistic": 4.750018325723334,
        "pValueAdj": 0.0003245257034795168
      },
      {
        "statistic": 2.375009162861667,
        "pValueAdj": 0.08145919956302905
      }
    ],
    "holmWelch": [
      {
        "meanDiff": 4.008333333333334,
        "statistic": 26.422190798003182,
        "df": 6.6844153359019485,
        "pValueRaw": 5.1699641365361224e-08,
        "ciLow": 3.6461501031186008,
        "ciHigh": 4.370516563548066,
        "hedgesG": 13.465246659104707,
        "pValueAdj": 2.067985654614449e-07
      },
      {
        "meanDiff": 0.9999999999999991,
        "statistic": 9.931270663228414,
        "df": 9.024555461473334,
        "pValueRaw": 3.713099413024925e-06,
        "ciLow": 0.772313200419234,
        "ciHigh": 1.227686799580764,
        "hedgesG": 5.241384207731871,
        "pValueAdj": 1.1139298239074776e-05
      },
      {
        "meanDiff": 0.5999999999999996,
        "statistic": 5.958762397937042,
        "df": 9.024555461473323,
        "pValueRaw": 0.00021073062446721745,
        "ciLow": 0.3723132004192343,
        "ciHigh": 0.827686799580765,
        "hedgesG": 3.1448305246391195,
        "pValueAdj": 0.0004214612489344349
      },
      {
        "meanDiff": 0.2999999999999998,
        "statistic": 3.6365491603879554,
        "df": 10.0,
        "pValueRaw": 0.004562791391099047,
        "ciLow": 0.11618792263911767,
        "ciHigh": 0.48381207736088194,
        "hedgesG": 1.9373622018207954,
        "pValueAdj": 0.004562791391099047
      }
    ]
  },
  {
    "name": "extreme variance ratio",
    "control": [
      50.0,
      50.1,
      49.9,
      50.05,
      49.95,
      50.02
    ],
    "treated": [
      [
        40.0,
        60.0,
        30.0,
        70.0,
        45.0
      ]
    ],
    "dunnett": [
      {
        "statistic": -0.15564146189803318,
        "pValueAdj": 0.8797697463978876
      }
    ],
    "holmWelch": [
      {
        "meanDiff": -1.0033333333333303,
        "statistic": -0.14049360530773747,
        "df": 4.000132462092936,
        "pValueRaw": 0.8950606498407925,
        "ciLow": -20.831022544995108,
        "ciHigh": 18.824355878328447,
        "hedgesG": -0.07089731950654399,
        "pValueAdj": 0.8950606498407925
      }
    ]
  },
  {
    "name": "near-equal means",
    "control": [
      10.0,
      10.5,
      9.5,
      10.2,
      9.8,
      10.1
    ],
    "treated": [
      [
        10.1,
        9.9,
        10.3,
        9.7,
        10.2,
        10.0
      ]
    ],
    "dunnett": [
      {
        "statistic": 0.1007074368138394,
        "pValueAdj": 0.9218107661949225
      }
    ],
    "holmWelch": [
      {
        "meanDiff": 0.01666666666666572,
        "statistic": 0.10070743681383938,
        "df": 8.426970577425829,
        "pValueRaw": 0.9221377426673641,
        "ciLow": -0.36162784189347863,
        "ciHigh": 0.39496117522681007,
        "hedgesG": 0.05278316845310324,
        "pValueAdj": 0.9221377426673641
      }
    ]
  }
];
