/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  /**
  Opens GraphPad Prism file
  */
  export async function importPrism(bytes: any ): Promise<any> {
    return await grok.functions.call('Prism:ImportPrism', { bytes });
  }

  export async function previewPrism(file: DG.FileInfo ): Promise<DG.View> {
    return await grok.functions.call('Prism:PreviewPrism', { file });
  }
}
