name: myenv
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - flask
  - flask_cors
  - pip
  - cuda-version=11.8
  - cudatoolkit=11.8
  - cuDNN
  - pytorch>=1.8.1=*cuda*
  - pytorch-cuda=11.8
  - torchvision=*=*_cu*
  - torchaudio=*=*_cu*