{
  "swagger": "2.0",
  "info": {
    "description": "Jira Cloud REST API documentation",
    "version": "1001.0.0-SNAPSHOT",
    "title": "Jira Reddata",
    "termsOfService": "http://atlassian.com/terms/",
    "contact": {
      "email": "ecosystem@atlassian.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "reddata.atlassian.net",
  "basePath": "/rest",
  "schemes": ["https"],
  "paths": {
    "/api/2/application-properties": {
      "get": {
        "summary": "Get application property",
        "description": "Returns all application properties or a single application property.\n\n <p>\n If you specify a value for the <code>key</code> parameter, then a single application property is returned as\n an object (not in an array). Otherwise, an array of all editable application properties is returned. See\n <a href=\"#api-api-2-application-properties-id-put\">Set application property</a> for\n descriptions of editable properties.\n\n <p>\n <b><a href=\"#permissions\">Permissions</a> [...]",
        "summary": "com.atlassian.jira.rest.v2.admin.ApplicationPropertiesResource.getApplicationProperty_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/application-properties/advanced-settings": {
      "get": {
        "summary": "Get advanced settings",
        "description": "Returns the application properties that are accessible on the <em>Advanced Settings</em> page. To navigate to the\n <em>Advanced Settings</em> page in Jira, choose the Jira icon > <b>Jira settings</b> > <b>System</b>,\n <b>General Configuration</b> and then click <b>Advanced Settings</b> (in the upper right).\n\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permissio[...]",
        "summary": "com.atlassian.jira.rest.v2.admin.ApplicationPropertiesResource.getAdvancedSettings_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/application-properties/{id}": {
      "put": {
        "summary": "Set application property",
        "description": "Changes the value of an application property. For example, you can change the value of the\n <code>jira.clone.prefix</code> from its default value of <em>CLONE -</em> to <em>Clone -</em> if you prefer\n sentence case capitalization. Editable properties are described below along with their default values.\n\n\n <h4>Advanced settings</h4>\n\n <p>The advanced settings below are also accessible in <a href=\"https://confluence.atlassian.com/x/vYXKM\">Jira</a>.</p>\n\n <table>\[...]",
        "summary": "com.atlassian.jira.rest.v2.admin.ApplicationPropertiesResource.setApplicationProperty_put",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/applicationrole": {
      "get": {
        "summary": "Get all application roles",
        "description": "Returns all application roles. In Jira, application roles are managed using the\n <a href=\"https://confluence.atlassian.com/x/3YxjL\">Application access configuration</a> page.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.admin.applicationrole.ApplicationRoleResource.getAllApplicationRoles_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/applicationrole/{key}": {
      "get": {
        "summary": "Get application role",
        "description": "Returns an application role.\n\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.admin.applicationrole.ApplicationRoleResource.getApplicationRole_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/attachment/meta": {
      "get": {
        "summary": "Get global attachment settings",
        "description": "Returns the global attachment settings, that is, whether attachments are enabled and the maximum attachment size\n allowed.\n <p>\n Note that there are also <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permissions</a> that restrict\n whether users can create and delete attachments or not.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.attachment.AttachmentResource.getAttachmentMeta_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/attachment/{id}": {
      "get": {
        "summary": "Get attachment metadata",
        "description": "Returns the metadata for an attachment. Note that the attachment itself is not returned.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> For the issue containing the attachment:\n <ul>\n   <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the\n   project that the issue is in.</li>\n   <li>If configured, permission to see the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.attachment.AttachmentResource.getAttachment_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete attachment",
        "description": "Deletes an attachment from an issue.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> For the project holding the issue containing the attachment:\n <ul>\n     <li><em>Delete own attachments</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>\n     to delete an attachment created by the calling user.</li>\n     <li><em>Delete all attachments</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>\n  [...]",
        "summary": "com.atlassian.jira.rest.v2.issue.attachment.AttachmentResource.removeAttachment_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/attachment/{id}/expand/human": {
      "get": {
        "summary": "Get all metadata for an expanded attachment",
        "description": "Returns the metadata for the contents of an attachment, if it is an archive, and metadata for the attachment itself.\n For example, if the attachment is a ZIP archive, then information about the files in the archive is returned and\n metadata for the ZIP archive. Currently, only the ZIP archive format is supported.\n <p>\n Use this method to retrieve data that is presented in the UI, as this method returns the metadata for the attachment\n itself, such as the attachment's[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.attachment.AttachmentResource.expandAttachmentForHumans_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false,
        "x-experimental": true
      }
    },
    "/api/2/attachment/{id}/expand/raw": {
      "get": {
        "summary": "Get contents metadata for an expanded attachment",
        "description": "Returns the metadata for the contents of an attachment, if it is an archive. For example, if the attachment is a ZIP\n archive, then information about the files in the archive is returned. Currently, only the ZIP archive format is supported.\n <p>\n Use this method if you are processing the data without presenting it in the UI, as this method only returns the metadata\n for the contents of the attachment. Otherwise, to retrieve data to present in the UI, use\n <a href=\"#[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.attachment.AttachmentResource.expandAttachmentForMachines_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false,
        "x-experimental": true
      }
    },
    "/api/2/auditing/record": {
      "get": {
        "summary": "Get audit records",
        "description": "Returns a list of audit records. The list can be filtered to include items:\n  <ul>\n     <li>containing a string in at least one field. For example, providing <em>up</em> will return all audit records\n     where one or more fields contains words such as <em>update</em>.</li>\n     <li>created on or after a date and time.</li>\n     <li>created or or before a date and time.</li>\n     <li>created during a time period.</li>\n  </ul>\n <p>\n <b><a href=\"#permissions\">Per[...]",
        "summary": "com.atlassian.jira.rest.v2.admin.auditing.AuditingResource.getAuditRecords_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/avatar/{type}/system": {
      "get": {
        "summary": "Get system avatars by type",
        "description": "Returns a list of system avatar details by owner type, where the owner types are issue type, project, or user.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.AvatarResource.getAllSystemAvatars_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/comment/list": {
      "post": {
        "summary": "Get comments by IDs",
        "description": "Returns the comments for a list of comment IDs.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse project</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the project\n containing a requested issue. Issues in projects where the user doesn't have <em>browser project</em> permission are\n excluded from the returned list. Also, when the visibility of a comment is restricted to a role or group the user\n must b[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueCommentListResource.getCommentsByIds_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/comment/{commentId}/properties": {
      "get": {
        "summary": "Get comment property keys",
        "description": "Returns the keys of all the properties of a comment.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> either of:\n  <ul>\n       <li><em>Edit All Comments</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>\n       to get the keys of all the properties on any comment.</li>\n       <li><em>Edit Own Comments</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>\n       to get the keys of all the prop[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.CommentPropertyResource.getCommentPropertyKeys_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/comment/{commentId}/properties/{propertyKey}": {
      "get": {
        "summary": "Get comment property",
        "description": "Returns the value of a comment property.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> either of:\n  <ul>\n       <li><em>Edit All Comments</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>\n       to get the value of a property from any comment.</li>\n       <li><em>Edit Own Comments</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>\n       to get the value of a property from a comment cr[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.CommentPropertyResource.getCommentProperty_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Set comment property",
        "description": "Creates or updates the value of a property for a comment. Use this resource to store custom data against a comment.\n <p>\n The value of the request body must be a <a href=\"http://tools.ietf.org/html/rfc4627\">valid</a>, non-empty JSON\n blob. The maximum length is 32768 characters.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> either of:\n  <ul>\n       <li><em>Edit All Comments</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permi[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.CommentPropertyResource.setCommentProperty_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete comment property",
        "description": "Deletes a comment property.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> either of:\n  <ul>\n       <li><em>Edit All Comments</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>\n       to delete a property from any comment.</li>\n       <li><em>Edit Own Comments</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>\n       to delete a property from a comment created by the user.</li>\n  </ul>\[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.CommentPropertyResource.deleteCommentProperty_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/component": {
      "post": {
        "summary": "Create component",
        "description": "Creates a component. Use components to provide containers for issues within a project.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Any of the following:\n <ul>\n     <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>.</li>\n     <li><em>Administer projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>.</li>\n </ul> ",
        "summary": "com.atlassian.jira.rest.v2.issue.ComponentResource.createComponent_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/component/{id}": {
      "get": {
        "summary": "Get component",
        "description": "Returns a component.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Browse projects</em>\n <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ComponentResource.getComponent_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Update component",
        "description": "Updates a component. Any fields included in the request are overwritten. If <code>leadUserName</code>\n is an empty string (\"\") the component lead is removed.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Any of the following:\n <ul>\n     <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>.</li>\n     <li><em>Administer projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project pe[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.ComponentResource.updateComponent_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete component",
        "description": "Deletes a component.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Any of the following:\n <ul>\n     <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>.</li>\n     <li><em>Administer projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>.</li>\n </ul> ",
        "summary": "com.atlassian.jira.rest.v2.issue.ComponentResource.deleteComponent_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/component/{id}/relatedIssueCounts": {
      "get": {
        "summary": "Get component issues count",
        "description": "Returns the counts of issues assigned to the component.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ComponentResource.getComponentRelatedIssues_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/configuration": {
      "get": {
        "summary": "Get global settings",
        "description": "Returns the <a href=\"https://confluence.atlassian.com/x/qYXKM\">global settings</a> in Jira. These settings\n determine whether optional features (for example, sub-tasks, time tracking, and others) are enabled.\n If time tracking is enabled, this method also returns the time tracking configuration.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira . ",
        "summary": "com.atlassian.jira.rest.v2.admin.ConfigurationResource.getConfiguration_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/configuration/timetracking": {
      "get": {
        "summary": "Get selected time tracking provider",
        "description": "Returns the time tracking provider that is currently selected. Note that if time tracking is disabled, then\n a successful but empty response is returned.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.admin.timetracking.TimeTrackingResource.getSelectedTimeTrackingImplementation_get",
        "schemes": [],
        "deprecated": false
      },
      "put": {
        "summary": "Select time tracking provider",
        "description": "Selects a time tracking provider.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.admin.timetracking.TimeTrackingResource.selectTimeTrackingImplementation_put",
        "schemes": [],
        "deprecated": false
      },
      "delete": {
        "summary": "Disable time tracking",
        "description": "Disables time tracking.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.admin.timetracking.TimeTrackingResource.disableTimeTracking_delete",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/configuration/timetracking/list": {
      "get": {
        "summary": "Get all time tracking providers",
        "description": "Returns all time tracking providers. By default, Jira only has one time tracking provider: <em>JIRA provided time tracking</em>.\n However, you can install other time tracking providers via apps from the Atlassian Marketplace.\n For more information on time tracking providers, see the documentation for the\n <a href=\"https://developer.atlassian.com/cloud/jira/platform/modules/time-tracking-provider/\">\n Time Tracking Provider</a> module.\n <p>\n <b><a href=\"#permission[...]",
        "summary": "com.atlassian.jira.rest.v2.admin.timetracking.TimeTrackingResource.getAvailableTimeTrackingImplementations_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/configuration/timetracking/options": {
      "get": {
        "summary": "Get time tracking settings",
        "description": "Returns the time tracking settings. This includes settings such as the time format, default time\n unit, and others. For more information, see\n <a href=\"https://confluence.atlassian.com/x/qoXKM\">Configuring time tracking</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.admin.timetracking.TimeTrackingResource.getSharedTimeTrackingConfiguration_get",
        "schemes": [],
        "deprecated": false
      },
      "put": {
        "summary": "Set time tracking settings",
        "description": "Sets the time tracking settings.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.admin.timetracking.TimeTrackingResource.setSharedTimeTrackingConfiguration_put",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/customFieldOption/{id}": {
      "get": {
        "summary": "Get custom field option",
        "description": "Returns a custom field option. For example, an option in a cascading select list.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.customfield.CustomFieldOptionResource.getCustomFieldOption_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/dashboard": {
      "get": {
        "summary": "Get all dashboards",
        "description": "Returns a list of dashboards owned by or shared with the user. The list may be filtered to include only favorite or\n owned dashboards.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.dashboard.DashboardResource.getAllDashboards_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/dashboard/search": {
      "get": {
        "summary": "Search for dashboards",
        "description": "Search for dashboards. This method is similar to\n <a href=\"#api-api-2-dashboard-get\">Get dashboards</a> except that\n you can refine the results to include dashboards that have specific attributes. For example, dashboards with a particular name.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however only the following dashboards are returned (if no search parameters are set):\n <ul>\n <li>Dashboards owned by the user.</li[...]",
        "summary": "com.atlassian.jira.rest.v2.dashboard.DashboardResource.getDashboardsPaginated_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/dashboard/{dashboardId}/items/{itemId}/properties": {
      "get": {
        "summary": "Get dashboard item property keys",
        "description": "Returns the keys of all properties for a dashboard item.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira.\n However, to get the property keys the user must be the owner of the dashboard or be shared the dashboard.\n Note, users with the <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global\n permission</a> are considered owners of the System dashboard. The System dashboard is considered to be sh[...]",
        "summary": "com.atlassian.jira.rest.v2.dashboard.DashboardItemPropertyResource.getDashboardItemPropertyKeys_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}": {
      "get": {
        "summary": "Get dashboard item property",
        "description": "Returns the key and value of a dashboard item property.\n <p>\n A dashboard item enables an app to add user-specific information to a user dashboard. Dashboard items are exposed\n to users as gadgets that users can add to their dashboards. For more information on how users do this, see\n <a href=\"https://confluence.atlassian.com/x/7AeiLQ\">Adding and customizing gadgets</a>.\n <p>\n When an app creates a dashboard item it registers a callback to receive the dashboard ite[...]",
        "summary": "com.atlassian.jira.rest.v2.dashboard.DashboardItemPropertyResource.getDashboardItemProperty_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Set dashboard item property",
        "description": "Sets the value of a dashboard item property. Use this resource in apps to store custom data against a dashboard\n item.\n <p>\n A dashboard item enables an app to add user-specific information to a user dashboard. Dashboard items are exposed\n to users as gadgets that users can add to their dashboards. For more information on how users do this, see\n <a href=\"https://confluence.atlassian.com/x/7AeiLQ\">Adding and customizing gadgets</a>.\n <p>\n When an app creates a das[...]",
        "summary": "com.atlassian.jira.rest.v2.dashboard.DashboardItemPropertyResource.setDashboardItemProperty_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete dashboard item property",
        "description": "Deletes a dashboard item property.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira.\n However, to delete a dashboard item property the user must be the owner of the dashboard.\n Note, users with the <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global\n permission</a> are considered owners of the System dashboard. ",
        "summary": "com.atlassian.jira.rest.v2.dashboard.DashboardItemPropertyResource.deleteDashboardItemProperty_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/dashboard/{id}": {
      "get": {
        "summary": "Get dashboard",
        "description": "Returns a dashboard.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira.\n However, to get a dashboard, the dashboard must be shared with the user or the user must own it.\n Note, users with the <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global\n permission</a> are considered owners of the System dashboard. The System dashboard is considered to be shared\n with all other users. ",
        "summary": "com.atlassian.jira.rest.v2.dashboard.DashboardResource.getDashboard_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/expression/eval": {
      "post": {
        "summary": "Evaluate Jira expression",
        "description": "Evaluates a Jira expression and returns its value.\n\n <p> Jira expressions is the name of a domain-specific language for Jira\n that can be used to evaluate expressions in the context of Jira entities.\n\n <h4 id=\"jira-expressions-context\">Context variables</h4>\n <p> The following context variables are available:\n <ul>\n     <li>`user`: The current user. Equal to `null` if the request is anonymous.\n         <br/>&nbsp;Fields: `accountId`, `displayName`, `properties`[...]",
        "summary": "com.atlassian.jira.rest.v2.expression.JiraExpressionsResource.evaluateJiraExpression_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work",
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/field": {
      "get": {
        "summary": "Get fields",
        "description": "Returns all issue fields in Jira, both system and custom fields.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira, however the following\n rules apply:\n <ul>\n     <li>Fields that cannot be added to the issue navigator are always returned.</li>\n     <li>Fields that cannot be placed on an issue screen are always returned.</li>\n     <li>Fields that depend on global Jira settings are only returned if the setting is enabled. That [...]",
        "summary": "com.atlassian.jira.rest.v2.issue.FieldResource.getFields_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Create custom field",
        "description": "Creates a custom field.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.FieldResource.createCustomField_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/field/{fieldKey}/option": {
      "get": {
        "summary": "Get all issue field options",
        "description": "Returns all options defined for a select list issue field. A select list issue field is a type of\n <a href=\"https://developer.atlassian.com/cloud/jira/platform/modules/issue-field/\">issue field</a>\n that allows a user to select n value from a list of options.\n <p>\n Note that this operation <b>cannot be used with the built-in custom fields</b>. It only works with issue fields\n added by Connect apps, as described above.\n <p>\n <b><a href=\"#permissions\">Permissions[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.field.IssueFieldOptionResource.getAllIssueFieldOptions_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Create issue field option",
        "description": "Creates an option for a select list issue field.\n <p>\n Note that this operation <b>cannot be used with the built-in custom fields</b>. It only works with issue fields\n added by Connect apps, as described above.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. Jira permissions are not required for\n the app providing the field. ",
        "summary": "com.atlassian.jira.rest.v2.issue.field.IssueFieldOptionResource.createIssueFieldOption_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/field/{fieldKey}/option/suggestions/edit": {
      "get": {
        "summary": "Get selectable issue field options",
        "description": "Returns options defined for a select list issue field that can be viewed and selected by the currently logged in user.\n <p>\n Note that this operation <b>cannot be used with the built-in custom fields</b>. It only works with issue fields\n added by Connect apps, as described above.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.field.IssueFieldOptionResource.getSelectableIssueFieldOptions_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/field/{fieldKey}/option/suggestions/search": {
      "get": {
        "summary": "Get visible issue field options",
        "description": "Returns options defined for a select list issue field that can be viewed by the currently logged in user.\n <p>\n Note that this operation <b>cannot be used with the built-in custom fields</b>. It only works with issue fields\n added by Connect apps, as described above.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.field.IssueFieldOptionResource.getVisibleIssueFieldOptions_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/field/{fieldKey}/option/{optionId}": {
      "get": {
        "summary": "Get issue field option",
        "description": "Returns an option from a select list issue field.\n <p>\n Note that this operation <b>cannot be used with the built-in custom fields</b>. It only works with issue fields\n added by Connect apps, as described above.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. Jira permissions are not required for\n the app providing the field. ",
        "summary": "com.atlassian.jira.rest.v2.issue.field.IssueFieldOptionResource.getIssueFieldOption_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Update issue field option",
        "description": "Updates or creates an option for a select list issue field. This operation requires that the option ID is provided\n when creating an option, therefore, the option ID needs to be specified as a path and body parameter. The option\n ID provided in the path and body must be identical.\n <p>\n Note that this operation <b>cannot be used with the built-in custom fields</b>. It only works with issue fields\n added by Connect apps, as described above.\n <p>\n <b><a href=\"#permi[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.field.IssueFieldOptionResource.updateIssueFieldOption_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete issue field option",
        "description": "Deletes an option from a select list issue field.\n <p>\n Note that this operation <b>cannot be used with the built-in custom fields</b>. It only works with issue fields\n added by Connect apps, as described above.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. Jira permissions are not required for\n the app providing the field. ",
        "summary": "com.atlassian.jira.rest.v2.issue.field.IssueFieldOptionResource.deleteIssueFieldOption_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/field/{fieldKey}/option/{optionId}/issue": {
      "delete": {
        "summary": "Replace issue field option",
        "description": "Deselects a select list issue field option in all issues that it has been selected in. A different option can be\n selected to replace the deselected option. The update can also be limited to a smaller set of issues by using a JQL query.\n <p>\n This is an <a href=\"#async\">asynchronous method</a>. The response object contains a link to the long-running\n task.\n <p>\n Note that this operation <b>cannot be used with the built-in custom fields</b>. It only works with issu[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.field.IssueFieldOptionResource.replaceIssueFieldOption_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/filter": {
      "get": {
        "summary": "Get filters",
        "description": "Returns all filters. Deprecated, use <a href=\"#api-api-2-filter-search-get\">\n Search for filters</a> that supports search and pagination.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however, only the following filters are returned:\n <ul>\n <li>Filters owned by the user.</li>\n <li>Filters shared with a group that the user is a member of.</li>\n <li>Filters shared with a private project that the user has <em>Browse pro[...]",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.getFilters_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": true
      },
      "post": {
        "summary": "Create filter",
        "description": "Creates a new filter. The new filter is not shared and not selected as a favorite.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.createFilter_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/filter/defaultShareScope": {
      "get": {
        "summary": "Get default share scope",
        "description": "Returns the default sharing settings for new filters and dashboards for a user.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.getDefaultShareScope_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Set default share scope",
        "description": "Sets the default sharing for new filters and dashboards for a user.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.setDefaultShareScope_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/filter/favourite": {
      "get": {
        "summary": "Get favorite filters",
        "description": "Returns the favorite filters of the calling user.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.getFavouriteFilters_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/filter/my": {
      "get": {
        "summary": "Get my filters",
        "description": "Returns the filters owned by the calling user. If <code>includeFavourites</code> is <code>true</code>, the user's\n favorite filters are also returned.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.getMyFilters_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/filter/search": {
      "get": {
        "summary": "Search for filters",
        "description": "Search for filters. This method is similar to\n <a href=\"#api-api-2-filter-get\">Get filters</a> except that\n you can refine the results to include filters that have specific attributes. For example, filters with a particular name.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however:\n <ul>\n   <li>if no search parameters are set only the following filters are returned:\n   <ul>\n     <li>Filters owned by the user.</li>[...]",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.getFiltersPaginated_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/filter/{id}": {
      "get": {
        "summary": "Get filter",
        "description": "Returns a filter.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however, a filter is only returned where at least one of the following applies:\n <ul>\n    <li>the user owns the filter.</li>\n    <li>the user is a member of a group the filter is shared with.</li>\n    <li>the user has <em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>\n    for a private project the filter i[...]",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.getFilter_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Update filter",
        "description": "Updates an existing filter. Use this method to update a filter's name, description, JQL, or sharing.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however the following rules govern what a user can update:\n <ul>\n <li>Private filters (that is, filters that are not shared) can only be updated by the creator of the filter.</li>\n <li>Shared filters can only be updated by the creator of the filter or a Jira administrator.</li[...]",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.updateFilter_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete filter",
        "description": "Delete a filter.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however the following rules govern what a user can delete:\n <ul>\n <li>Private filters (that is, filters that are not shared) can only be deleted by the creator of the filter.</li>\n <li>Shared filters can only be deleted by the creator of the filter or a Jira administrator.</li>\n </ul> ",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.deleteFilter_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/filter/{id}/columns": {
      "get": {
        "summary": "Get columns",
        "description": "Returns the columns configured for a filter. The column configuration is used when the filter's results\n are viewed in <em>List View</em> with the <em>Columns</em> set to <em>Filter</em>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however, a filter is only returned where at least one of the following applies:\n <ul>\n    <li>the user owns the filter.</li>\n    <li>the user is a member of a group the filter is shared wit[...]",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.getColumns_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Set columns",
        "description": "Sets the columns for a filter. Only navigable fields can be set as columns. Use\n <a href=\"#api-api-2-field-get\">Get fields</a> to get the\n list fields in Jira. A navigable field has <code>navigable</code> set to <code>true</code>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however, columns are only set for filters where at least one of the following applies:\n <ul>\n    <li>the user owns the filter.</li>\n    <li>the[...]",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.setColumns_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Reset columns",
        "description": "Reset the user's column configuration for the filter to the default.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however, columns are only reset for filters where at least one of the following applies:\n <ul>\n    <li>the user owns the filter.</li>\n    <li>the user is a member of a group the filter is shared with.</li>\n    <li>the user has <em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">pr[...]",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.resetColumns_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/filter/{id}/favourite": {
      "put": {
        "summary": "Add filter as favorite",
        "description": "Add a filter as a favorite for the calling user.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however, the user can only favorite a filter where at least one of the following applies:\n <ul>\n     <li>the user owns the filter.</li>\n     <li>the user is a member of a group the filter is shared with.</li>\n     <li>the user has <em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission[...]",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.setFavouriteForFilter_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Remove filter as favorite",
        "description": "Removes a filter as a favorite for the calling user.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however, the user can only remove a favorite from their favorite list where at least\n one of the following applies:\n <ul>\n    <li>the user owns the filter.</li>\n    <li>the user is a member of a group the filter is shared with.</li>\n    <li>the user has <em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x[...]",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.deleteFavouriteForFilter_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/filter/{id}/permission": {
      "get": {
        "summary": "Get share permissions",
        "description": "Returns the share permissions for a filter. A filter can be shared with groups, projects, all logged-in users, or\n the public. Sharing with all logged-in users or the public is known as a global share permission.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however, a filter is only returned where at least one of the following applies:\n <ul>\n    <li>the user owns the filter.</li>\n    <li>the user is a member of a group[...]",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.getSharePermissions_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Add share permission",
        "description": "Add a share permissions to a filter. If you add a global share permission (one for all logged-in users or the public)\n it will overwrite all share permissions for the filter.\n <p>\n Be aware that this method uses different objects for updating share permissions compared to\n <a href=\"#api-api-2-filter-id-put\">Update filter</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Share dashboards and filters</em> <a href=\"https://confluence.atlassi[...]",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.addSharePermission_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/filter/{id}/permission/{permissionId}": {
      "get": {
        "summary": "Get share permission",
        "description": "Returns a share permission for a filter. A filter can be shared with groups, projects, all logged-in users, or\n the public. Sharing with all logged-in users or the public is known as a global share permission.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however, a filter is only returned where at least one of the following applies:\n <ul>\n    <li>the user owns the filter.</li>\n    <li>the user is a member of a group th[...]",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.getSharePermission_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete share permission",
        "description": "Deletes a share permission from a filter.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira and the user must own the filter. ",
        "summary": "com.atlassian.jira.rest.v2.search.FilterResource.deleteSharePermission_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/group": {
      "get": {
        "summary": "Get group",
        "description": "This resource is deprecated, use <a href=\"#api-api-2-group-member-get\"><code>group/member</code></a>.\n <p>\n Returns all users in a group.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.GroupResource.getGroup_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": true
      },
      "post": {
        "summary": "Create group",
        "description": "Creates a group.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Site administration (that is, member of the <em>site-admin</em>\n <a href=\"https://confluence.atlassian.com/x/24xjL\">group</a>). ",
        "summary": "com.atlassian.jira.rest.v2.issue.GroupResource.createGroup_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Remove group",
        "description": "Deletes a group.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Site administration (that is, member of the <em>site-admin</em>\n strategic <a href=\"https://confluence.atlassian.com/x/24xjL\">group</a>). ",
        "summary": "com.atlassian.jira.rest.v2.issue.GroupResource.removeGroup_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/group/member": {
      "get": {
        "summary": "Get users from group",
        "description": "Returns all users in a group. Users are ordered by username.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.GroupResource.getUsersFromGroup_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/group/user": {
      "post": {
        "summary": "Add user to group",
        "description": "Adds a user to a group.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Site administration (that is, member of the <em>site-admin</em>\n <a href=\"https://confluence.atlassian.com/x/24xjL\">group</a>). ",
        "summary": "com.atlassian.jira.rest.v2.issue.GroupResource.addUserToGroup_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Remove user from group",
        "description": "Removes a user from a group.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Site administration (that is, member of the <em>site-admin</em>\n <a href=\"https://confluence.atlassian.com/x/24xjL\">group</a>). ",
        "summary": "com.atlassian.jira.rest.v2.issue.GroupResource.removeUserFromGroup_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/groups/picker": {
      "get": {
        "summary": "Find groups",
        "description": "Returns a list of groups whose names contain a query string. A list of group names can\n be provided to exclude groups from the results.\n <p>\n The primary use case for this resource is to populate a group picker suggestions list. To this end, the returned\n object includes the <code>html</code> field where the matched query term is highlighted in the group name with\n the HTML strong tag. Also, the groups list is wrapped in a response object that contains a header for u[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.GroupPickerResource.findGroups_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/groupuserpicker": {
      "get": {
        "summary": "Find users and groups",
        "description": "Returns a list of users and groups matching a string. The string is used:\n <ul>\n   <li>for users, to find a case insensitive match with username, name, and e-mail address.</li>\n   <li>for groups, to find a case-sensitive match with group name.</li>\n </ul>\n For example, if the string <em>tin</em> is used, records with the username ptindall, name Tina,\n email address sarah@tinplatetraining.com, and the group accounting would be returned.\n <p>\n Optionally, the search[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.GroupAndUserPickerResource.findUsersAndGroups_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue": {
      "post": {
        "summary": "Create issue",
        "description": "Creates an issue or, where the option to create sub-tasks is enabled in Jira, a sub-task. A transition may be\n applied, to move the issue or sub-task to a workflow step other than the default start step, and issue properties\n set.\n <p>\n The content of the issue or sub-task is defined using <code>update</code> and <code>fields</code>. The fields\n that can be set in the issue or sub-task are determined using the <a href=\"#api-api-2-issue-createmeta-get\">\n Get create[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.createIssue_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/bulk": {
      "post": {
        "summary": "Bulk issue create",
        "description": "Creates issues and, where the option to create sub-tasks is enabled in Jira, sub-tasks. Transitions may be\n applied, to move the issues or sub-tasks to a workflow step other than the default start step, and issue properties\n set.\n <p>\n The content of each issue or sub-task is defined using <code>update</code> and <code>fields</code>. The fields\n that can be set in the issue or sub-task are determined using the <a href=\"#api-api-2-issue-createmeta-get\">\n Get create[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.createIssues_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/createmeta": {
      "get": {
        "summary": "Get create issue metadata",
        "description": "Returns details of projects, issue types within projects, and, when requested, the create screen\n fields for each issue type for the user. Use the information to populate the requests in <a href=\"#api-api-2-issue-post\">\n Create issue</a> and <a href=\"#api-api-2-issue-bulk-post\">Create issues</a>.\n <p>\n The request can be restricted to specific projects or issue types using the query parameters. The response will\n contain information for the valid projects, issue [...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.getCreateIssueMeta_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/picker": {
      "get": {
        "summary": "Get issue picker suggestions",
        "description": "Returns lists of issues matching a query string. Use this resource to provide auto-completion suggestions\n when the user is looking for an issue using a word or string.\n <p>\n This operation returns two lists:\n <ul>\n <li><code>History Search</code> which includes issues from the user's history of created, edited, or viewed\n issues that contain the string in the <code>query</code> parameter.</li>\n <li><code>Current Search</code> which includes issues that match the J[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.getIssuePickerResource_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/properties/{propertyKey}": {
      "put": {
        "summary": "Bulk set issue property",
        "description": "Sets a property value on multiple issues. The issues to be updated can be specified by a filter.\n <p>\n The filter identifies issues eligible for update using these criteria:\n <ul>\n   <li><code>entityIds</code> Only issues from this list are eligible.</li>\n   <li><code>currentValue</code> Only issues with the property set to this value are eligible.</li>\n   <li><code>hasProperty</code>:\n   <ul>\n       <li>If <em>true</em>, only issues with the property are eligible[...]",
        "summary": "com.atlassian.jira.rest.v2.property.IssuePropertyBulkUpdateResource.bulkSetIssueProperty_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false,
        "x-experimental": true
      },
      "delete": {
        "summary": "Bulk delete issue property",
        "description": "Deletes a property value from multiple issues. The issues to be updated can be specified by filter criteria.\n <p>\n The criteria the filter used to identify eligible issues are:\n <ul>\n   <li><code>entityIds</code> Only issues from this list are eligible.</li>\n   <li><code>currentValue</code> Only issues with the property set to this value are eligible.</li>\n </ul>\n If both criteria is specified, they are joined with the logical <em>AND</em>: only issues that satisfy[...]",
        "summary": "com.atlassian.jira.rest.v2.property.IssuePropertyBulkUpdateResource.bulkDeleteIssueProperty_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false,
        "x-experimental": true
      }
    },
    "/api/2/issue/{issueIdOrKey}": {
      "get": {
        "summary": "Get issue",
        "description": "Returns the details for an issue.\n <p>\n The issue is identified by its ID or key, however, if the identifier doesn't match an issue, a case-insensitive\n search and check for moved issues is performed. If a matching issue is found its details are returned, a 302 or\n other redirect is <b>not</b> returned. The issue key returned in the response is the key of the issue\n found.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Browse proje[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.getIssue_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Edit issue",
        "description": "Edits an issue. A transition may be applied and issue properties updated as part of the edit.\n <p>\n The edits to the issue's fields are defined using <code>update</code> and <code>fields</code>. The fields\n that can be edited are determined using <a href=\"#api-api-2-issue-issueIdOrKey-editmeta-get\">\n Get edit issue metadata</a>.\n <p>\n Connect app users with admin permissions (from user permissions and app scopes) can override the screen security\n configuration us[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.editIssue_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete issue",
        "description": "Deletes an issue.\n <p>\n An issue cannot be deleted if it has one or more sub-tasks. To delete an issue with sub-tasks, set <code>\n deleteSubtasks</code>. This causes the issue's sub-tasks to be deleted with the issue.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the\n project that the issue is in.</li>\n <li>If configured, permissi[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.deleteIssue_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/assignee": {
      "put": {
        "summary": "Assign issue",
        "description": "Assigns an issue to a user. Use this operation when the calling user does not have the <em>Edit Issues</em> permission\n but has the <em>Assign issue</em> permission for the project that the issue is in.\n <p>\n Note that:\n <ul>\n <li>Only the <code>name</code> property needs to be set in the request object.</li>\n <li>If <code>name</code> in the request object is set to <code>\"-1\"</code>, then the issue is assigned to the\n default assignee for the project.</li>\n <li[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.assignIssue_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/attachments": {
      "post": {
        "summary": "Add attachment",
        "description": "Adds one or more attachments to an issue. Attachments are posted as multipart/form-data (<a href=\"https://www.ietf.org/rfc/rfc1867.txt\">RFC 1867</a>).\n <p>\n Note that:\n <ul>\n     <li>The request must have a <code>X-Atlassian-Token: no-check</code> header, otherwise it will be blocked.\n     See <a href=\"#special-request-headers\">Special headers</a> for more information.</li>\n     <li>The name of the multipart/form-data parameter that contains the attachments must[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueAttachmentsResource.addAttachment_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/changelog": {
      "get": {
        "summary": "Get change logs",
        "description": "Returns all changelogs for an issue sorted by date, starting from the oldest.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the\n   project that the issue is in.</li>\n   <li>If configured, permission to see the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n   issue-level security</a>.<li>\n </ul> ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueChangelogResource.getChangeLogs_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/comment": {
      "get": {
        "summary": "Get comments",
        "description": "Returns all comments, that are visible to the user, for an issue.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the\n   project that the issue containing the comment is in.</li>\n   <li>If configured, permission to see the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n   issue-level security</a>.<li>\n </ul[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueCommentResource.getComments_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Add comment",
        "description": "Adds a comment to an issue.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> and <em>Add comments</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">\n   project permission</a> for the project that the issue containing the comment is in.</li>\n   <li>If configured, permission to see the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n   issue-level security</a>.<li>\n </ul> ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueCommentResource.addComment_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/comment/{id}": {
      "get": {
        "summary": "Get comment",
        "description": "Returns a comment.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the\n   project that the issue containing the comment is in.</li>\n   <li>If configured, permission to see the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n   issue-level security</a>.<li>\n   <li>Where the visibility of the comment is restri[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueCommentResource.getComment_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Update comment",
        "description": "Updates a comment.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> and <em>Edit all comments</em> or <em>Edit own comments</em>\n   <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the project that the issue\n   containing the comment is in.</li>\n   <li>If configured, permission to see the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n   issue-level securi[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueCommentResource.updateComment_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete comment",
        "description": "Deletes a comment.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> and <em>Delete all comments</em> or <em>Delete own comments</em>\n   <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the project that the issue\n   containing the comment is in.</li>\n   <li>If configured, permission to see the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n   issue-level se[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueCommentResource.deleteComment_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/editmeta": {
      "get": {
        "summary": "Get edit issue metadata",
        "description": "Returns the edit screen fields for an issue that are visible to and editable by the user. Use the information to\n populate the requests in <a href=\"#api-api-2-issue-issueIdOrKey-put\">Edit issue</a>.\n <p/>\n Connect app users with admin permissions (from user permissions and app scopes) can return additional details using:\n <ul>\n <li><code>overrideScreenSecurity</code> Returns hidden fields.</li>\n <li><code>overrideEditableFlag</code> Returns uneditable fields. For [...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.getEditIssueMeta_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/notify": {
      "post": {
        "summary": "Send notification for issue",
        "description": "Creates an email notification for an issue and adds it to the mail queue.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Browse Projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the project that the issue is in.</li>\n <li>If configured, permission to view the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">issue-level security</a>.</li>\n </ul> ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.notify_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/properties": {
      "get": {
        "summary": "Get issue property keys",
        "description": "Returns the URLs and keys of an issue's properties.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n  <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the project\n  that the issue is in.</li>\n  <li>If configured, permission to see the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n      issue-level security<a>.<li>\n  </ul> ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssuePropertyResource.getIssuePropertyKeys_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/properties/{propertyKey}": {
      "get": {
        "summary": "Get issue property",
        "description": "Returns the key and value of an issue's property.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n   <ul>\n   <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the project\n   that the issue is in.</li>\n   <li>If configured, permission to see the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n   issue-level security<a>.<li>\n </ul> ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssuePropertyResource.getIssueProperty_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Set issue property",
        "description": "Sets the value of an issue's property. Use this resource to store custom data against an issue.\n <p>\n The value of the request body must be a <a href=\"http://tools.ietf.org/html/rfc4627\">valid</a>, non-empty JSON\n blob. The maximum length is 32768 characters.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n   <ul>\n   <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the project\n  that th[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssuePropertyResource.setIssueProperty_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete issue property",
        "description": "Deletes an issue's property.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n   <ul>\n   <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the project\n   that the issue is in.</li>\n   <li>If configured, permission to view the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n   issue-level security <a>.<li>\n   <li><em>Edit issues</em> <a href=\"https://confluence.atlas[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssuePropertyResource.deleteIssueProperty_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/remotelink": {
      "get": {
        "summary": "Get remote issue links",
        "description": "Returns the remote issue links for an issue. When a remote issue link global ID is provided the record with that\n global ID is returned, otherwise all remote issue links are returned.\n <p>\n This operation requires <a href=\"https://confluence.atlassian.com/x/yoXKM\">issue linking to be active</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permissi[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.getRemoteIssueLinks_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Create or update remote issue link",
        "description": "Creates or updates a remote issue link for an issue.\n <p>\n If a <code>globalId</code> is provided and a the remote issue link with that global ID exists it is updated. Any\n fields without values in the request are set to null. Otherwise, the remote issue link is created.\n <p>\n For more details on the content of the request body, see <a href=\"https://developer.atlassian.com/server/jira/platform/using-fields-in-remote-issue-links/\">\n Using fields in Remote Issue Lin[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.createOrUpdateRemoteIssueLink_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete remote issue link by global id",
        "description": "Deletes the remote issue link from the issue using the link's global ID.\n <p>\n This operation requires <a href=\"https://confluence.atlassian.com/x/yoXKM\">issue linking to be active</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the\n project that the issue is in.</li>\n <li>If configured, permission to see the issue granted by [...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.deleteRemoteIssueLinkByGlobalId_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/remotelink/{linkId}": {
      "get": {
        "summary": "Get remote issue link by id",
        "description": "Returns a remote issue link for an issue.\n <p>\n This operation requires <a href=\"https://confluence.atlassian.com/x/yoXKM\">issue linking to be active</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the\n project that the issue is in.</li>\n <li>If configured, permission to see the issue granted by <a href=\"https://confluence.at[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.getRemoteIssueLinkById_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Update remote issue link",
        "description": "Updates a remote issue link for an issue.\n <p>\n For more details on the content of the request body, see <a href=\"https://developer.atlassian.com/server/jira/platform/using-fields-in-remote-issue-links/\">\n Using fields in Remote Issue Links</a>\n <p>\n Note: Fields without values in the request are set to null.\n <p>\n This operation requires <a href=\"https://confluence.atlassian.com/x/yoXKM\">issue linking to be active</a>.\n <p>\n <b><a href=\"#permissions\">Permi[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.updateRemoteIssueLink_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete remote issue link by id",
        "description": "Deletes a remote issue link from an issue.\n <p>\n This operation requires <a href=\"https://confluence.atlassian.com/x/yoXKM\">issue linking to be active</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the\n project that the issue is in.</li>\n <li>If configured, permission to see the issue granted by <a href=\"https://confluence.a[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.deleteRemoteIssueLinkById_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/transitions": {
      "get": {
        "summary": "Get transitions",
        "description": "Returns either all transitions or a transition that can be performed by the user on an issue, based on the issue's\n status.\n <p>\n Note, if a request is made for a transition that does not exist or cannot be performed on the issue, given\n its status, the response will return any empty transitions list.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project per[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.getTransitions_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Transition issue",
        "description": "Performs an issue transition and, if the transition has a screen, updates the fields from the transition screen.\n <p>\n To update the fields on the transition screen, specify the fields in the <code>fields</code> or <code>update</code>\n parameters in the request body.\n Get details about the fields by calling <code>fields</code> by <a href=\"#api-api-2-issue-issueIdOrKey-transitions-get\">\n Get transition</a> and using the <code>transitions.fields</code> expand.\n <p>\[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.doTransition_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/votes": {
      "get": {
        "summary": "Get votes",
        "description": "Returns details about the votes on an issue.\n <p>\n This operation requires the <b>Allow users to vote on issues</b> option to be <em>ON</em>. This option is set in\n General configuration for Jira. See <a href=\"https://confluence.atlassian.com/x/uYXKM\">Configuring Jira application\n options</a> for details.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">proje[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.getVotes_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Add vote",
        "description": "Adds the user's vote to an issue. This is the equivalent of the user clicking <em>Vote</em> on an issue\n in Jira.\n <p>\n This operation requires the <b>Allow users to vote on issues</b> option to be <em>ON</em>. This option is set in\n General configuration for Jira. See <a href=\"https://confluence.atlassian.com/x/uYXKM\">Configuring Jira application\n options</a> for details.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Browse pro[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.addVote_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete vote",
        "description": "Deletes a user's vote from an issue. This is the equivalent of the user clicking <em>Unvote</em> on an issue\n in Jira.\n <p>\n This operation requires the <b>Allow users to vote on issues</b> option to be <em>ON</em>. This option is set in\n General configuration for Jira. See <a href=\"https://confluence.atlassian.com/x/uYXKM\">Configuring Jira application\n options</a> for details.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Brows[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.removeVote_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/watchers": {
      "get": {
        "summary": "Get issue watchers",
        "description": "Returns the watchers for an issue.\n <p>\n This operation requires the <b>Allow users to watch issues</b> option to be <em>ON</em>. This option is set in\n General configuration for Jira. See <a href=\"https://confluence.atlassian.com/x/uYXKM\">Configuring Jira application\n options</a> for details.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permissio[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.getIssueWatchers_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Add watcher",
        "description": "Adds a user as a watcher of an issue. If no user is specified the calling user is added.\n <p>\n This operation requires the <b>Allow users to watch issues</b> option to be <em>ON</em>. This option is set in\n General configuration for Jira. See <a href=\"https://confluence.atlassian.com/x/uYXKM\">Configuring Jira application\n options</a> for details.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Browse projects</em> <a href=\"https:/[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.addWatcher_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete watcher",
        "description": "Deletes a user as a watcher of an issue.\n <p>\n This operation requires the <b>Allow users to watch issues</b> option to be <em>ON</em>. This option is set in\n General configuration for Jira. See <a href=\"https://confluence.atlassian.com/x/uYXKM\">Configuring Jira application\n options</a> for details.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project per[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueResource.removeWatcher_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/worklog": {
      "get": {
        "summary": "Get issue worklogs",
        "description": "Returns all worklogs for an issue.\n <p>\n Time tracking must be enabled in Jira, otherwise this operation returns an error. For more information, see\n <a href=\"https://confluence.atlassian.com/x/qoXKM\">Configuring time tracking</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the\n   project that the issue is in.</li>\n   <li>I[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueWorklogsResource.getIssueWorklog_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Add worklog",
        "description": "Adds a worklog to an issue.\n <p>\n Time tracking must be enabled in Jira, otherwise this operation returns an error. For more information, see\n <a href=\"https://confluence.atlassian.com/x/qoXKM\">Configuring time tracking</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> and <em>Work on issues</em><a href=\"https://confluence.atlassian.com/x/yodKLg\">\n   project permission</a> for the project that the issue [...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueWorklogsResource.addWorklog_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/worklog/{id}": {
      "get": {
        "summary": "Get worklog",
        "description": "Returns a worklog.\n <p>\n Time tracking must be enabled in Jira, otherwise this operation returns an error. For more information, see\n <a href=\"https://confluence.atlassian.com/x/qoXKM\">Configuring time tracking</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\"> project permission</a> for the\n   project that the issue is in.</li>\n   <li>If configured, p[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueWorklogsResource.getWorklog_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Update worklog",
        "description": "Updates a worklog.\n <p>\n Time tracking must be enabled in Jira, otherwise this operation returns an error. For more information, see\n <a href=\"https://confluence.atlassian.com/x/qoXKM\">Configuring time tracking</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\"> project permission</a> for the\n   project that the issue is in.</li>\n   <li>If configured, p[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueWorklogsResource.updateWorklog_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete worklog",
        "description": "Deletes a worklog from an issue.\n <p>\n Time tracking must be enabled in Jira, otherwise this operation returns an error. For more information, see\n <a href=\"https://confluence.atlassian.com/x/qoXKM\">Configuring time tracking</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\"> project permission</a> for the\n   project that the issue is in.</li>\n   <li>If[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueWorklogsResource.deleteWorklog_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/worklog/{worklogId}/properties": {
      "get": {
        "summary": "Get worklog property keys",
        "description": "Returns the keys of all properties for a worklog.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the\n   project that the issue is in.</li>\n   <li>If configured, permission to see the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n   issue-level security</a>.<li>\n   <li></li>\n </ul>\n If visibility is set [...]",
        "summary": "com.atlassian.jira.rest.v2.issue.WorklogPropertyResource.getWorklogPropertyKeys_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issue/{issueIdOrKey}/worklog/{worklogId}/properties/{propertyKey}": {
      "get": {
        "summary": "Get worklog property",
        "description": "Returns the value of a worklog property.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the\n   project that the issue is in.</li>\n   <li>If configured, permission to see the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n   issue-level security</a>.<li>\n   <li></li>\n </ul>\n If visibility is set on the wo[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.WorklogPropertyResource.getWorklogProperty_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Set worklog property",
        "description": "Sets the value of a worklog property. Use this operation to store custom data against the worklog.\n <p>\n The value of the request body must be a <a href=\"http://tools.ietf.org/html/rfc4627\">valid</a>, non-empty JSON blob.\n The maximum length is 32768 characters.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> and <em>Edit all worklogs</em> or <em>Edit own worklogs</em>\n   <a href=\"https://confluence.atlassia[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.WorklogPropertyResource.setWorklogProperty_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete worklog property",
        "description": "Deletes a worklog property.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n   <li><em>Browse projects</em> and <em>Edit all worklogs</em> or <em>Edit own worklogs</em>\n   <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for the project that the issue is in.</li>\n   <li>If configured, permission to see the issue granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n   issue-level security</a>.<li>\n   <l[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.WorklogPropertyResource.deleteWorklogProperty_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issueLink": {
      "post": {
        "summary": "Create issue link",
        "description": "Creates a link between two issues. Use this operation to indicate a relationship between two issues and optionally\n add a comment to the from (outward) issue. To use this resource the site must have\n <a href=\"https://confluence.atlassian.com/x/yoXKM\">Issue Linking</a> enabled.\n <p>\n This resource returns nothing on the creation of an issue link. To obtain the ID of the issue link, use\n <code>https://your-domain.atlassian.net/rest/api/2/issue/[linked issue key]?fiel[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.LinkIssueResource.linkIssues_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issueLink/{linkId}": {
      "get": {
        "summary": "Get issue link",
        "description": "Returns an issue link.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n     <li><em>Browse project</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for all the projects\n containing the linked issues.</li>\n     <li>If configured, permission to see both of the issues granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n     issue-level security</a>.<li>\n </ul> ",
        "summary": "com.atlassian.jira.rest.v2.issue.LinkIssueResource.getIssueLink_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete issue link",
        "description": "Deletes an issue link.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n    <li>Browse project</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> for all the\n    projects containing the issues in the link.</li>\n    <li>If configured, permission to see both of the issues granted by <a href=\"https://confluence.atlassian.com/x/J4lKLg\">\n    issue-level security</a>.<li>\n    <li><em>Link issues</em> <a href=\"https:[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.LinkIssueResource.deleteIssueLink_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issueLinkType": {
      "get": {
        "summary": "Get issue link types",
        "description": "Returns a list of all issue link types.\n <p>\n To use this operation, the site must have <a href=\"https://confluence.atlassian.com/x/yoXKM\">issue linking</a> enabled.\n <p>\n <b></a><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. Users with permission\n to access Jira can call this method, but an empty list is returned. ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueLinkTypeResource.getIssueLinkTypes_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Create issue link type",
        "description": "Creates an issue link type. Use this operation to create descriptions of the reasons why issues are linked. The\n issue link type consists of a name and descriptions for a link's inward and outward relationships.\n <p>\n To use this operation, the site must have <a href=\"https://confluence.atlassian.com/x/yoXKM\">issue linking</a> enabled.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.c[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueLinkTypeResource.createIssueLinkType_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issueLinkType/{issueLinkTypeId}": {
      "get": {
        "summary": "Get issue link type",
        "description": "Returns an issue link type.\n <p>\n To use this operation, the site must have <a href=\"https://confluence.atlassian.com/x/yoXKM\">issue linking</a> enabled.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueLinkTypeResource.getIssueLinkType_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Update issue link type",
        "description": "Updates an issue link type.\n <p>\n To use this operation, the site must have <a href=\"https://confluence.atlassian.com/x/yoXKM\">issue linking</a> enabled.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueLinkTypeResource.updateIssueLinkType_put",
        "schemes": [],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete issue link type",
        "description": "Deletes an issue link type.\n <p>\n To use this operation, the site must have <a href=\"https://confluence.atlassian.com/x/yoXKM\">issue linking</a> enabled.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueLinkTypeResource.deleteIssueLinkType_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issuesecurityschemes": {
      "get": {
        "summary": "Get issue security schemes",
        "description": "Returns all <a href=\"https://confluence.atlassian.com/x/J4lKLg\">issue security schemes</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueSecuritySchemeResource.getIssueSecuritySchemes_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issuesecurityschemes/{id}": {
      "get": {
        "summary": "Get issue security scheme",
        "description": "Returns an issue security scheme along with its security levels.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n     <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>.</li>\n     <li><em>Administer Projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>\n     for a project that uses the requested issue security scheme.</li>\n </ul> ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueSecuritySchemeResource.getIssueSecurityScheme_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issuetype": {
      "get": {
        "summary": "Get all issue types for user",
        "description": "Returns all issue types.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira,\n however, issue types are only returned as follows:\n <ul>\n   <li>if the user has the <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>,\n   all issue types are returned.</li>\n   <li>if the user has the <em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueTypeResource.getIssueAllTypes_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Create issue type",
        "description": "Creates an issue type and adds it to the default issue type scheme.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueTypeResource.createIssueType_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issuetype/{id}": {
      "get": {
        "summary": "Get issue type",
        "description": "Returns an issue type.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>\n to get the details of any issue type.</li>\n <li><em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> to get the\n details of any issue type associated with the projects the user has permission to browse.</li>\n </ul> ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueTypeResource.getIssueType_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Update issue type",
        "description": "Updates the issue type.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueTypeResource.updateIssueType_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete issue type",
        "description": "Deletes the issue type. If the issue type is in use, all uses are updated with the alternative issue type\n (<code>alternativeIssueTypeId</code>). A list of alternative issue types can be obtained from the\n <a href=\"#api-api-2-issuetype-id-alternatives-get\">\n Get alternative issue types</a> resource.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. [...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueTypeResource.deleteIssueType_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issuetype/{id}/alternatives": {
      "get": {
        "summary": "Get alternative issue types",
        "description": "Returns a list of issue types that can be used to replace the issue type. The alternative issue types are those\n assigned to the same workflow scheme, field configuration scheme, and screen scheme.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueTypeResource.getAlternativeIssueTypes_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issuetype/{id}/avatar2": {
      "post": {
        "summary": "Load issue type avatar",
        "description": "Loads an avatar for the issue type.\n <p>\n Specify the avatar's local file location in the body of the request. Also, include the following headers:\n <ul>\n <li><code>X-Atlassian-Token: no-check</code> To prevent XSRF protection blocking the request,\n for more information see <a href=\"#special-request-headers\">Special Headers</a>.</li>\n <li><code>Content-Type: image/<em>image type</em></code> Valid image types are JPEG, GIF, or PNG.</li>\n </ul>\n <p>\n For example:[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueTypeResource.createIssueTypeAvatar_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issuetype/{issueTypeId}/properties": {
      "get": {
        "summary": "Get issue type property keys",
        "description": "Returns all the\n <a href=\"https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties\">issue type property</a>\n keys of the issue type.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n     <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>\n     to get the property keys of any issue type.</li>\n     <li><em>Brows[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueTypePropertyResource.getIssueTypePropertyKeys_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/issuetype/{issueTypeId}/properties/{propertyKey}": {
      "get": {
        "summary": "Get issue type property",
        "description": "Returns the key and value of the\n <a href=\"https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties\">issue type property</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n     <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>\n     to get the details of any issue type.</li>\n     <li><em>Browse projects</em[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueTypePropertyResource.getIssueTypeProperty_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Set issue type property",
        "description": "Creates or updates the value of the\n <a href=\"https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties\">issue type property</a>.\n Use this resource to store and update data against an issue type.\n <p>\n The value of the request body must be a <a href=\"http://tools.ietf.org/html/rfc4627\">valid</a>, non-empty JSON\n blob. The maximum length is 32768 characters.\n <p>\n <b><a href=\"#perm[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueTypePropertyResource.setIssueTypeProperty_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete issue type property",
        "description": "Deletes the\n <a href=\"https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties\">issue type property</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <i>Administer Jira</i>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueTypePropertyResource.deleteIssueTypeProperty_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/jql/autocompletedata": {
      "get": {
        "summary": "Get field reference data",
        "description": "Returns reference data for JQL searches. This is a downloadable version of the documentation provided in\n <a href=\"https://confluence.atlassian.com/x/gwORLQ\">Advanced searching - fields reference</a> and\n <a href=\"https://confluence.atlassian.com/x/hgORLQ\">Advanced searching - functions reference</a>, along with a\n list of JQL-reserved words. Use this information to assist with the programmatic creation of JQL queries or the\n validation of queries built in a custo[...]",
        "summary": "com.atlassian.jira.rest.v2.search.SearchAutoCompleteResource.getAutoComplete_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/jql/autocompletedata/suggestions": {
      "get": {
        "summary": "Get field auto complete suggestions",
        "description": "Returns the JQL search auto complete suggestions for a field.\n <p>\n Suggestions can be obtained by providing:\n <ul>\n     <li><code>fieldName</code> to get a list of all values for the field.</li>\n     <li><code>fieldName</code> and <code>fieldValue</code> to get a list of values containing the text in\n     <code>fieldValue</code>.</li>\n     <li><code>fieldName</code> and <code>predicateName</code> to get a list of all predicate values for the field.</li>\n     <li>[...]",
        "summary": "com.atlassian.jira.rest.v2.search.SearchAutoCompleteResource.getFieldAutoCompleteForQueryString_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/jql/pdcleaner": {
      "post": {
        "summary": "Convert user identifiers to account IDs in JQL queries",
        "description": "Converts one or more JQL queries with user identifiers (username or user key) to equivalent JQL queries with account IDs.\n <p>\n You may wish to use this operation if your system stores JQL queries and you want to make them GDPR-compliant. For\n more information about GDPR-related changes, see the\n <a href=\"https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/\">migration guide</a>.\n <p>\n <b><a href=\"#permissions\">[...]",
        "summary": "com.atlassian.jira.rest.v2.search.JQLPersonalDataMigrationResource.migrateQueries_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/mypermissions": {
      "get": {
        "summary": "Get my permissions",
        "description": "Returns a list of permissions indicating which permissions the user has. Details of the user's permissions can be\n obtained in a global, project, or issue context.\n <p>\n The user is reported as having a project permission:\n <ul>\n <li>in the global context, if the user has the project permission in any project.</li>\n <li>for a project, where the project permission is determined using issue data, if the user meets the permission's\n criteria for any issue in the proje[...]",
        "summary": "com.atlassian.jira.rest.v2.permission.PermissionsResource.getMyPermissions_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/mypreferences": {
      "get": {
        "summary": "Get preference",
        "description": "Returns the value of a preference of the user.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.preference.CurrentUserPreferencesResource.getPreference_get",
        "schemes": [],
        "deprecated": false
      },
      "put": {
        "summary": "Set preference",
        "description": "Creates a preference for the user or updates its value. An arbitrary preference can be created with the value containing\n up to 255 characters. In addition, the following keys define system preferences that can be set or created:\n  <ul>\n       <li><em>user.notifications.mimetype</em> The mime type used in notifications sent to the user. Defaults to\n       <code>html</code>.</li>\n       <li><em>user.notify.own.changes</em> Indicates whether the user gets notified of t[...]",
        "summary": "com.atlassian.jira.rest.v2.preference.CurrentUserPreferencesResource.setPreference_put",
        "schemes": [],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete preference",
        "description": "Deletes a preference of the user, which restores the default value of system defined settings.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.preference.CurrentUserPreferencesResource.removePreference_delete",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/mypreferences/locale": {
      "get": {
        "summary": "Get locale",
        "description": "Returns the locale for the current user.\n <p>\n If the user has no language preference set (which is the default setting) or this resource is accessed anonymous,\n the browser locale detected by Jira is returned. Jira detects the browser locale using the <em>Accept-Language</em>\n header in the request. However, if this doesn't match a locale available Jira, the site default locale is returned.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission [...]",
        "summary": "com.atlassian.jira.rest.v2.preference.CurrentUserPreferencesResource.getLocale_get",
        "schemes": [],
        "deprecated": false
      },
      "put": {
        "summary": "Set locale",
        "description": "Sets the locale of the current user. The requested locale must be one supported by the instance of Jira.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.preference.CurrentUserPreferencesResource.setLocale_put",
        "schemes": [],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete locale",
        "description": "Deletes the locale of the current user, which restores the default setting.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.preference.CurrentUserPreferencesResource.deleteLocale_delete",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/myself": {
      "get": {
        "summary": "Get current user",
        "description": "Returns details for the authenticated user.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.CurrentUserResource.getCurrentUser_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/notificationscheme": {
      "get": {
        "summary": "Get notification schemes paginated",
        "description": "Returns a <a href=\"#pagination\">paginated</a>\n list of <a href=\"https://confluence.atlassian.com/x/8YdKLg\">notification schemes</a> in order by display name.\n\n <h3 id=\"about-notification-schemes\">About notification schemes</h3>\n\n <p>\n A notification scheme is a list of events and recipients who will receive notifications for those events. The\n list is contained within the <code>notificationSchemeEvents</code> object and contains pairs of <code>events</code>\n[...]",
        "summary": "com.atlassian.jira.rest.v2.notification.NotificationSchemeResource.getNotificationSchemes_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/notificationscheme/{id}": {
      "get": {
        "summary": "Get notification scheme",
        "description": "Returns a <a href=\"https://confluence.atlassian.com/x/8YdKLg\">notification scheme</a>, including the list of\n events and the recipients who will receive notifications for those events.\n\n <p><b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira, however the requesting user must have permission to administer at least one project associated with the\n requested notification scheme. ",
        "summary": "com.atlassian.jira.rest.v2.notification.NotificationSchemeResource.getNotificationScheme_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/permissions": {
      "get": {
        "summary": "Get all permissions",
        "description": "Returns all permissions, including:\n <ul>\n <li>global permissions.</li>\n <li>project permissions.</li>\n <li>global permissions added by plugins.</li>\n </ul>\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.permission.PermissionsResource.getAllPermissions_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/permissions/check": {
      "post": {
        "summary": "Get bulk permissions",
        "description": "Checks whether the current user has the provided permissions for the given issues.\n <p>\n If an unknown issue or project id is passed it will be ignored. The number of issues or projects\n that can be checked is capped at 1000. ",
        "summary": "com.atlassian.jira.rest.v2.permission.PermissionsResource.getBulkPermissions_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/permissions/project": {
      "post": {
        "summary": "Get permitted projects",
        "description": "Returns all the projects where the user is granted a list of project permissions.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.permission.PermissionsResource.getPermittedProjects_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "deprecated": false,
        "x-experimental": true
      }
    },
    "/api/2/permissionscheme": {
      "get": {
        "summary": "Get all permission schemes",
        "description": "Returns all permission schemes.\n\n <h3 id=\"about-permission-schemes\">About permission schemes and grants</h3>\n\n A permission scheme is a collection of permission grants. A permission grant consists of a <code>holder</code>\n and a <code>permission</code>.\n\n <h4 id=\"holder-object\">Holder</h4>\n\n The <code>holder</code> object contains information about the user or group being granted the permission. For\n example, the <em>Administer projects</em> permission is gr[...]",
        "summary": "com.atlassian.jira.rest.v2.admin.permissionscheme.PermissionSchemeResource.getAllPermissionSchemes_get",
        "schemes": [],
        "deprecated": false
      },
      "post": {
        "summary": "Create permission scheme",
        "description": "Creates a new permission scheme. You can create a permission scheme with or without defining a set of\n permission grants.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.admin.permissionscheme.PermissionSchemeResource.createPermissionScheme_post",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/permissionscheme/{schemeId}": {
      "get": {
        "summary": "Get permission scheme",
        "description": "Returns a permission scheme.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.admin.permissionscheme.PermissionSchemeResource.getPermissionScheme_get",
        "schemes": [],
        "deprecated": false
      },
      "put": {
        "summary": "Update permission scheme",
        "description": "Updates a permission scheme. Below are some important things to note when using this resource:\n <p>\n <ul>\n     <li>If a permissions list is present in the request, then it will be set in the permission scheme, overwriting\n     <em>all existing</em> grants.</li>\n     <li>If you want to update only the name and description, then do not send a permissions list in the request.</li>\n     <li>Sending an empty list will remove all permission grants from the permission sche[...]",
        "summary": "com.atlassian.jira.rest.v2.admin.permissionscheme.PermissionSchemeResource.updatePermissionScheme_put",
        "schemes": [],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete permission scheme",
        "description": "Deletes a permission scheme.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.admin.permissionscheme.PermissionSchemeResource.deletePermissionScheme_delete",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/permissionscheme/{schemeId}/permission": {
      "get": {
        "summary": "Get permission scheme grants",
        "description": "Returns all permission grants for a permission scheme.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.admin.permissionscheme.PermissionSchemeResource.getPermissionSchemeGrants_get",
        "schemes": [],
        "deprecated": false
      },
      "post": {
        "summary": "Create permission grant",
        "description": "Creates a permission grant in a permission scheme.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.admin.permissionscheme.PermissionSchemeResource.createPermissionGrant_post",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/permissionscheme/{schemeId}/permission/{permissionId}": {
      "get": {
        "summary": "Get permission scheme grant",
        "description": "Returns a permission grant.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.admin.permissionscheme.PermissionSchemeResource.getPermissionSchemeGrant_get",
        "schemes": [],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete permission scheme entity",
        "description": "Deletes a permission grant from a permission scheme. See\n <a href=\"#about-permission-schemes\">About permission schemes and grants</a>\n for more details.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.admin.permissionscheme.PermissionSchemeResource.deletePermissionSchemeEntity_delete",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/priority": {
      "get": {
        "summary": "Get priorities",
        "description": "Returns the list of all issue priorities.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.PriorityResource.getPriorities_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/priority/{id}": {
      "get": {
        "summary": "Get priority",
        "description": "Returns an issue priority.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.PriorityResource.getPriority_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project": {
      "get": {
        "summary": "Get all projects",
        "description": "Returns all projects visible to the currently logged in user. Deprecated, use <a href=\"#api-api-2-project-search-get\">\n Get projects paginated</a> that supports search and pagination.\n <p>\n For projects to be visible, the authenticated user\n must be granted either <em>Browse projects</em> or <em>Administer projects</em> permissions. If no user is logged\n in, it returns all projects that are visible for anonymous users.\n <p>\n <b><a href=\"#permissions\">Permission[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.getAllProjects_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": true
      },
      "post": {
        "summary": "Create project",
        "description": "Creates a project based on a project type template, as shown in the following table:\n <p>\n <table>\n   <thead>\n    <tr>\n      <th>Project Type Key</th>\n      <th>Project Template Key</th>\n    </tr>\n   </thead>\n   <tbody>\n      <tr>\n        <td><code>business</code></td>\n        <td><code>com.atlassian.jira-core-project-templates:jira-core-simplified-content-management</code>,\n            <code>com.atlassian.jira-core-project-templates:jira-core-simplified-docu[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.createProject_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/search": {
      "get": {
        "summary": "Get projects paginated",
        "description": "Returns projects visible to the currently logged in user. For projects to be visible, the authenticated user\n must be granted either <em>Browse projects</em> or <em>Administer projects</em> permissions. If no user is logged\n in, then all projects visible to anonymous users are returned.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.searchProjects_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/type": {
      "get": {
        "summary": "Get all project types",
        "description": "Returns all <a href=\"https://confluence.atlassian.com/x/Var1Nw\">project types</a>, whether or not the instance\n has a valid license for each type.\n\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.project.type.ProjectTypeResource.getAllProjectTypes_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/type/{projectTypeKey}": {
      "get": {
        "summary": "Get project type by key",
        "description": "Returns a <a href=\"https://confluence.atlassian.com/x/Var1Nw\">project type</a>.\n\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.project.type.ProjectTypeResource.getProjectTypeByKey_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/type/{projectTypeKey}/accessible": {
      "get": {
        "summary": "Get accessible project type by key",
        "description": "Returns a <a href=\"https://confluence.atlassian.com/x/Var1Nw\">project type</a> if it is accessible\n to the logged in user.\n\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.project.type.ProjectTypeResource.getAccessibleProjectTypeByKey_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}": {
      "get": {
        "summary": "Get project",
        "description": "Returns the <a href=\"https://confluence.atlassian.com/x/ahLpNw\">project details</a> for the specified project.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse Projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.getProject_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Update project",
        "description": "Updates the <a href=\"https://confluence.atlassian.com/x/ahLpNw\">project details</a> of a project.\n <p>\n All parameters are optional in the body of the request.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.updateProject_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete project",
        "description": "Deletes a project.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.deleteProject_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/avatar": {
      "put": {
        "summary": "Set project avatar",
        "description": "Sets the avatar displayed for a project.\n <p>\n Use <a href=\"#api-api-2-project-projectIdOrKey-avatar2-post\">Load project avatar</a> to store avatars against\n the project, before using this operation to set the displayed avatar.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.updateProjectAvatar_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/avatar/{id}": {
      "delete": {
        "summary": "Delete project avatar",
        "description": "Deletes a custom avatar from a project. Note that system avatars cannot be deleted.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.deleteProjectAvatar_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/avatar2": {
      "post": {
        "summary": "Load project avatar",
        "description": "Loads an avatar for a project.\n <p>\n Specify the avatar's local file location in the body of the request. Also, include the following headers:\n <ul>\n     <li><code>X-Atlassian-Token: no-check</code> To prevent XSRF protection blocking the request,\n     for more information see <a href=\"#special-request-headers\">Special Headers</a>.</li>\n     <li><code>Content-Type: image/<em>image type</em></code> Valid image types are JPEG, GIF, or PNG.</li>\n </ul>\n <p>\n For e[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.createProjectAvatar_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/avatars": {
      "get": {
        "summary": "Get all project avatars",
        "description": "Returns all project avatars, grouped by system and custom avatars.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.getAllProjectAvatars_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/component": {
      "get": {
        "summary": "Get project components paginated",
        "description": "Returns a <a href=\"#pagination\">paginated</a>\n representation of all components existing in a single project. See the\n <a href=\"#api-api-2-project-projectIdOrKey-components-get\">Get project components</a>\n resource if you want to get a full list of versions without pagination.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse Projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.getProjectComponentsPaginated_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/components": {
      "get": {
        "summary": "Get project components",
        "description": "Returns all components in a project. See the\n <a href=\"#api-api-2-project-projectIdOrKey-component-get\">Get project components paginated</a>\n resource if you want to get a full list of components with pagination.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse Projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.getProjectComponents_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/properties": {
      "get": {
        "summary": "Get project property keys",
        "description": "Returns all <a href=\"https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties\">project property</a>\n keys for the project.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse Projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectPropertyResource.getProjectPropertyKeys_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/properties/{propertyKey}": {
      "get": {
        "summary": "Get project property",
        "description": "Returns the value of the <a href=\"https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties\">project property</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse Projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectPropertyResource.getProjectProperty_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Set project property",
        "description": "Sets the value of the\n <a href=\"https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties\">project property</a>.\n You can use project properties to store custom data against the project.\n <p>\n The value of the request body must be a <a href=\"http://tools.ietf.org/html/rfc4627\">valid</a>, non-empty JSON\n blob. The maximum length is 32768 characters.\n <p>\n <b><a href=\"#permissions\">[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectPropertyResource.setProjectProperty_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete project property",
        "description": "Removes the <a href=\"https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties\">property</a>\n from the project.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectPropertyResource.deleteProjectProperty_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/role": {
      "get": {
        "summary": "Get project roles for project",
        "description": "Returns a list of <a href=\"https://confluence.atlassian.com/x/3odKLg\">project roles</a> for the project.\n\n <p>\n Note that all project roles are shared with all projects in Jira Cloud. See the\n <a href=\"#api-api-2-role-get\">Get all project roles</a>\n resource for more information.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>\n or <em>Administ[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.project.ProjectRoleResource.getProjectRoles_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/role/{id}": {
      "get": {
        "summary": "Get project role for project",
        "description": "Returns the project role's details and actors associated with the project. The list of actors is sorted by\n display name.\n\n <p>\n If you would like to check to see whether a user belongs to a role based on their group memberships, use the\n <a href=\"#api-api-2-user-get\">Get user</a> resource\n with the <code>groups</code> expand parameter selected. Then check whether the user keys and groups match with\n the actors returned for the project.\n\n <p>\n <b><a href=\"#pe[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.project.ProjectRoleResource.getProjectRole_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Add actors to project role",
        "description": "Adds additional actors to a project role for the project.\n\n <p>\n If you want to replace all actors for the project, then use\n <a href=\"#api-api-2-project-projectIdOrKey-role-id-put\">Set actors for project role</a>.\n\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>\n or <em>Administer Projects</em> <a href=\"https://confluence.atlassian.com/x/yodKL[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.project.ProjectRoleResource.addActorUsers_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Set actors for project role",
        "description": "Associates actors with the project role for the project, replacing all existing actors.\n <p>\n If you want to add actors to the project without overwriting the existing list, then use\n <a href=\"#api-api-2-project-projectIdOrKey-role-id-post\">Add actors to project role</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>\n or <em>Administer Projects<[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.project.ProjectRoleResource.setActors_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete actors from project role",
        "description": "Deletes actors from a project role for the project.\n\n <p>\n If you want to remove default actors from the project role, see the\n <a href=\"#api-api-2-role-id-actors-delete\">Delete default actors from project role</a>\n resource.\n\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>\n or <em>Administer Projects</em> <a href=\"https://confluence.atlassian[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.project.ProjectRoleResource.deleteActor_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/roledetails": {
      "get": {
        "summary": "Get project role details",
        "description": "Returns all <a href=\"https://confluence.atlassian.com/x/3odKLg\">project roles</a> and the details for each role.\n Note that the list of project roles is common to all projects. ",
        "summary": "com.atlassian.jira.rest.v2.issue.project.ProjectRoleDetailsResource.getProjectRoleDetails_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/statuses": {
      "get": {
        "summary": "Get all statuses for project",
        "description": "Returns the valid statuses for a project. The statuses are grouped by issue type, as each project has a set of\n valid issue types and each issue type has a set of valid statuses.\n\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse Projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.getAllStatuses_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/type/{newProjectTypeKey}": {
      "put": {
        "summary": "Update project type",
        "description": "Updates a <a href=\"https://confluence.atlassian.com/x/GwiiLQ\">project type</a>. The project type can be updated\n for classic projects only, project type cannot be updated for next-gen projects.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.updateProjectType_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/version": {
      "get": {
        "summary": "Get project versions paginated",
        "description": "Returns a <a href=\"#pagination\">paginated</a>\n representation of all versions in a project. See the\n <a href=\"#api-api-2-project-projectIdOrKey-versions-get\">Get project versions</a>\n resource if you want to get a full list of versions without pagination.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse Projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.getProjectVersionsPaginated_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectIdOrKey}/versions": {
      "get": {
        "summary": "Get project versions",
        "description": "Returns all versions existing in a project. The response is not paginated. Use\n <a href=\"#api-api-2-project-projectIdOrKey-version-get\">Get project versions paginated</a>\n if you want to get the versions in a project with pagination.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse Projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectResource.getProjectVersions_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectKeyOrId}/issuesecuritylevelscheme": {
      "get": {
        "summary": "Get project issue security scheme",
        "description": "Returns the <a href=\"https://confluence.atlassian.com/x/J4lKLg\">issue security scheme</a> associated with the\n project.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a> or the <em>Administer Projects</em>\n <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectIssueSecurityLevelSchemeResource.getIssueSecurityScheme_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectKeyOrId}/notificationscheme": {
      "get": {
        "summary": "Get project notification scheme",
        "description": "Gets a <a href=\"https://confluence.atlassian.com/x/8YdKLg\">notification scheme</a> associated with the project.\n See the <a href=\"#api-api-2-notificationscheme-id-get\">Get notification scheme</a>\n resource for more information about notification schemes.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>\n or <em>Administer Projects</em> <a href=\"ht[...]",
        "summary": "com.atlassian.jira.rest.v2.notification.ProjectNotificationSchemeResource.getNotificationScheme_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectKeyOrId}/permissionscheme": {
      "get": {
        "summary": "Get assigned permission scheme",
        "description": "Gets the <a href=\"https://confluence.atlassian.com/x/yodKLg\">permission scheme</a> associated with the project.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a> or\n <em>Administer projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> ",
        "summary": "com.atlassian.jira.rest.v2.permission.ProjectPermissionSchemeResource.getAssignedPermissionScheme_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Assign permission scheme",
        "description": "Associates a permission scheme with a particular project. See\n <a href=\"https://confluence.atlassian.com/x/yodKLg\">Managing project permissions</a>\n for more information about permission schemes.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a> ",
        "summary": "com.atlassian.jira.rest.v2.permission.ProjectPermissionSchemeResource.assignPermissionScheme_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/project/{projectKeyOrId}/securitylevel": {
      "get": {
        "summary": "Get project issue security levels",
        "description": "Returns all <a href=\"https://confluence.atlassian.com/x/J4lKLg\">issue security</a> levels for the project that\n the currently authenticated user has access to. If the user does not have permission to see an issue security\n level, then that level is not returned. If the user lacks the <em>Set Issue Security</em> permission, then an\n empty list is returned.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Set Issue Security</em> <a href=\"https:/[...]",
        "summary": "com.atlassian.jira.rest.v2.securitylevel.ProjectSecurityLevelResource.getSecurityLevelsForProject_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/projectCategory": {
      "get": {
        "summary": "Get all project categories",
        "description": "Returns all project categories.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectCategoryResource.getAllProjectCategories_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Create project category",
        "description": "Creates a project category.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectCategoryResource.createProjectCategory_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/projectCategory/{id}": {
      "get": {
        "summary": "Get project category by id",
        "description": "Returns a project category.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectCategoryResource.getProjectCategoryById_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Update project category",
        "description": "Updates a project category.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectCategoryResource.updateProjectCategory_put",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete project category",
        "description": "Deletes a project category.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectCategoryResource.removeProjectCategory_delete",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/projectvalidate/key": {
      "get": {
        "summary": "Validate project key",
        "description": "Validates a project key by confirming the key is a valid string and not in use.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectValidateResource.validateProjectKey_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/projectvalidate/validProjectKey": {
      "get": {
        "summary": "Get valid project key",
        "description": "Validates a project key and, if the key is invalid or in use, generates a valid random string for the project key.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectValidateResource.getValidProjectKey_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/projectvalidate/validProjectName": {
      "get": {
        "summary": "Get valid project name",
        "description": "Checks that a project name isn't in use. If the name isn't in use, the passed string is returned. If the name is\n in use, this operation attempts to generate a valid project name based on the one supplied, usually by adding a\n sequence number. If a valid project name cannot be generated, a 404 response is returned.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ProjectValidateResource.getValidProjectName_get",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/resolution": {
      "get": {
        "summary": "Get resolutions",
        "description": "Returns a list of all issue resolution values.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ResolutionResource.getResolutions_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/resolution/{id}": {
      "get": {
        "summary": "Get resolution",
        "description": "Returns an issue resolution value.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ResolutionResource.getResolution_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/role": {
      "get": {
        "summary": "Get all project roles",
        "description": "Gets a list of all project roles, complete with project role details and default actors.\n <p>\n <h3 id=\"about-project-roles\">About project roles</h3>\n <p>\n <a href=\"https://confluence.atlassian.com/x/3odKLg\">Project roles</a> are a flexible way to to associate users and\n groups with projects. In Jira Cloud, the list of project roles is shared globally with all projects, but each\n project can have a different set of actors associated with it (unlike groups, which [...]",
        "summary": "com.atlassian.jira.rest.v2.issue.project.RoleResource.getAllProjectRoles_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Create project role",
        "description": "Creates a new project role with no <a href=\"#api-api-2-resolution-get\">default actors</a>.\n You can use the <a href=\"#api-api-2-role-id-actors-post\">Add default actors to project role</a>\n the project method to add default actors to the project role after creating it.\n <p>\n <em>Note that although a new project role is available to all projects upon creation, any default actors that are associated\n with the project role are not added to projects that existed prior[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.project.RoleResource.createProjectRole_post",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/role/{id}": {
      "get": {
        "summary": "Get project role by ID",
        "description": "Gets the project role details and the default actors associated with the role. The list of default actors is\n sorted by display name.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.project.RoleResource.getProjectRoleById_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Partial update project role",
        "description": "Update either the project role's name or its description.\n <p>\n You cannot update both the name and description at the same time using this method. If you send a request\n with both a name and a description, then only the name will be updated, regardless of the order of appearance in\n the body of the request.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permissi[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.project.RoleResource.partialUpdateProjectRole_post",
        "schemes": [],
        "deprecated": false
      },
      "put": {
        "summary": "Fully update project role",
        "description": "Update the project role's name and description. You must include both a name and a description in the request.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.project.RoleResource.fullyUpdateProjectRole_put",
        "schemes": [],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete project role",
        "description": "Deletes a project role. You must specify a replacement project role if you wish to delete a project role that is\n in use.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.project.RoleResource.deleteProjectRole_delete",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/role/{id}/actors": {
      "get": {
        "summary": "Get default actors for project role",
        "description": "Returns the <a href=\"#api-api-2-resolution-get\">default actors</a>\n for the project role.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.project.RoleResource.getProjectRoleActorsForRole_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Add default actors to project role",
        "description": "<p>\n Adds <a href=\"#api-api-2-resolution-get\">default actors</a>\n to the given role. You may add either groups or users, but you cannot add groups and users in the same request.\n </p>\n\n <div class=\"aui-message note\">\n <div class=\"icon\"></div>\n <p>Changing a project role's default actors does not affect project role members for projects already created.</p>\n </div>\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em>\n <a[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.project.RoleResource.addProjectRoleActorsToRole_post",
        "schemes": [],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete default actors from project role",
        "description": "Removes <a href=\"#api-api-2-resolution-get\">default actors</a>\n from the project role. You may remove either a group or user, but you cannot remove a group and a user in the same\n request.\n\n <div class=\"aui-message note\">\n <div class=\"icon\"></div>\n <p>Changing a project role's default actors does not affect project role members for projects already created.</p>\n </div>\n\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> <em>Administer Jira</em[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.project.RoleResource.deleteProjectRoleActorsFromRole_delete",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/screens": {
      "get": {
        "summary": "Get all screens",
        "description": "Returns all screens.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ScreensResource.getAllScreens_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/screens/addToDefault/{fieldId}": {
      "post": {
        "summary": "Add field to default screen",
        "description": "Adds a field to the default tab of the default screen.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ScreensResource.addFieldToDefaultScreen_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/screens/{screenId}/availableFields": {
      "get": {
        "summary": "Get available screen fields",
        "description": "Returns the fields that can be added to a tab on a screen.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ScreensResource.getAvailableScreenFields_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/screens/{screenId}/tabs": {
      "get": {
        "summary": "Get all screen tabs",
        "description": "Returns the list of tabs for a screen.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n      <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>.</li>\n      <li><em>Administer projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> when\n      the project key is specified, providing that the screen is associated with the project through a Screen Scheme\n     [...]",
        "summary": "com.atlassian.jira.rest.v2.issue.ScreensResource.getAllScreenTabs_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Create screen tab",
        "description": "Creates a tab for a screen.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ScreensResource.addScreenTab_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/screens/{screenId}/tabs/{tabId}": {
      "put": {
        "summary": "Update screen tab",
        "description": "Updates the name of a screen tab.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ScreensResource.renameScreenTab_put",
        "schemes": [],
        "deprecated": false
      },
      "delete": {
        "summary": "Delete screen tab",
        "description": "Deletes a screen tab.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ScreensResource.deleteScreenTab_delete",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/screens/{screenId}/tabs/{tabId}/fields": {
      "get": {
        "summary": "Get all screen tab fields",
        "description": "Returns all fields for a screen tab.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n      <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>.</li>\n      <li><em>Administer projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a> when\n      the project key is specified, providing that the screen is associated with the project through a Screen Scheme\n      a[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.ScreensResource.getAllScreenTabFields_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Add screen tab field",
        "description": "Adds a field to a screen tab.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ScreensResource.addScreenTabField_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/screens/{screenId}/tabs/{tabId}/fields/{id}": {
      "delete": {
        "summary": "Remove screen tab field",
        "description": "Removes a field from a screen tab.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ScreensResource.removeScreenTabField_delete",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/screens/{screenId}/tabs/{tabId}/fields/{id}/move": {
      "post": {
        "summary": "Move screen tab field",
        "description": "Moves a screen tab field.\n <p>\n If <code>after</code> and <code>position</code> are provided in the request, <code>position</code> is ignored.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ScreensResource.moveScreenTabField_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/screens/{screenId}/tabs/{tabId}/move/{pos}": {
      "post": {
        "summary": "Move screen tab",
        "description": "Moves a screen tab.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.ScreensResource.moveScreenTab_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-project"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/search": {
      "get": {
        "summary": "Search for issues using JQL (GET)",
        "description": "Searches for issues using <a href=\"https://confluence.atlassian.com/x/egORLQ\">JQL</a>.\n <p>\n If the JQL query expression is too large to be encoded as a query parameter, use the\n <a href=\"#api-api-2-search-post\">POST</a> version of this resource.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.search.SearchResource.searchForIssuesUsingJql_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Search for issues using JQL (POST)",
        "description": "Searches for issues using <a href=\"https://confluence.atlassian.com/x/egORLQ\">JQL</a>.\n <p>\n There is a <a href=\"#api-api-2-search-get\">GET</a>\n version of this resource that can be used for smaller JQL query expressions.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.search.SearchResource.searchForIssuesUsingJql_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/securitylevel/{id}": {
      "get": {
        "summary": "Get issue security level",
        "description": "Returns details of an issue security level.\n <p>\n Use <a href=\"#api-api-2-issuesecurityschemes-id-get\">Get issue security scheme</a> to obtain the IDs of issue\n security levels associated with the issue security scheme.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.IssueSecurityLevelResource.getIssueSecurityLevel_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "manage:jira-configuration"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/serverInfo": {
      "get": {
        "summary": "Get Jira instance info",
        "description": "Returns information about the Jira instance.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.ServerInfoResource.getServerInfo_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/settings/columns": {
      "get": {
        "summary": "Get issue navigator default columns",
        "description": "Returns the default issue navigator columns.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.admin.SettingsResource.getIssueNavigatorDefaultColumns_get",
        "schemes": [],
        "deprecated": false
      },
      "put": {
        "summary": "Set issue navigator default columns",
        "description": "Sets the default issue navigator columns.\n <p>\n The <code>columns</code> parameter accepts a single navigable field value and is expressed as HTML form data. To\n specify multiple columns, pass multiple <code>columns</code> parameters. For example, in curl:\n <p>\n <code>curl --request PUT \\\\ <p>\n   --data columns=&lt;field value 1&gt; \\\\ <p>\n   --data columns=&lt;field value 2&gt; \\\\ <p>\n   --url 'https://your-domain.atlassian.net/rest/api/2/settings/columns'<[...]",
        "summary": "com.atlassian.jira.rest.v2.admin.SettingsResource.setIssueNavigatorDefaultColumns_put",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/status": {
      "get": {
        "summary": "Get all statuses",
        "description": "Returns a list of all statuses associated with workflows.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. Users with permission\n to access Jira can call this method, but an empty list is returned. ",
        "summary": "com.atlassian.jira.rest.v2.issue.StatusResource.getStatuses_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/status/{idOrName}": {
      "get": {
        "summary": "Get status",
        "description": "Returns a status. The status must be associated with a workflow to be returned.\n <p>\n If a name is used on more than one status, only the status found first is returned. Therefore, identifying the\n status by its ID may be preferable.\n <p>\n <a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse projects</em> <a href=\"https://confluence.atlassian.com/x/yodKLg\">project permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.StatusResource.getStatus_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/statuscategory": {
      "get": {
        "summary": "Get all status categories",
        "description": "Returns a list of all status categories.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.StatusCategoryResource.getStatusCategories_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/statuscategory/{idOrKey}": {
      "get": {
        "summary": "Get status category",
        "description": "Returns a status category. Status categories provided a mechanism for categorizing\n <a href=\"#api-api-2-status-idOrName-get\">statuses</a>.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.StatusCategoryResource.getStatusCategory_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-work"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/task/{taskId}": {
      "get": {
        "summary": "Get task",
        "description": "Returns the status of a <a href=\"#async\">long-running asynchronous task</a>.\n <p>\n When a task has finished, this operation returns the JSON blob applicable to the task. See the documentation\n of the operation that created the task for details. Task details are not permanently retained. As of September 2019,\n details are retained for 14 days although this period may change without notice.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> either of:\n[...]",
        "summary": "com.atlassian.jira.rest.v2.task.TaskResource.getTask_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": []
          }
        ],
        "deprecated": false,
        "x-experimental": true
      }
    },
    "/api/2/task/{taskId}/cancel": {
      "post": {
        "summary": "Cancel task",
        "description": "Cancels a task.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> either of:\n  <ul>\n       <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>.</li>\n       <li>Creator of the task.</li>\n  </ul> ",
        "summary": "com.atlassian.jira.rest.v2.task.TaskResource.cancelTask_post",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "write:jira-work"
            ]
          }
        ],
        "deprecated": false,
        "x-experimental": true
      }
    },
    "/api/2/universal_avatar/type/{type}/owner/{entityId}": {
      "get": {
        "summary": "Get avatars",
        "description": "Returns the system and custom avatars for a project or issue type.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.UniversalAvatarResource.getAvatars_get",
        "schemes": [],
        "deprecated": false
      },
      "post": {
        "summary": "Load avatar",
        "description": "Loads a custom avatar for a project or issue type.\n <p>\n Specify the avatar's local file location in the body of the request. Also, include the following headers:\n <ul>\n     <li><code>X-Atlassian-Token: no-check</code> To prevent XSRF protection blocking the request,\n     for more information see <a href=\"#special-request-headers\">Special Headers</a>.</li>\n     <li><code>Content-Type: image/<em>image type</em></code> Valid image types are JPEG, GIF, or PNG.</li>\n[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.UniversalAvatarResource.storeAvatar_post",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/universal_avatar/type/{type}/owner/{owningObjectId}/avatar/{id}": {
      "delete": {
        "summary": "Delete avatar",
        "description": "Deletes an avatar from a project or issue type.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.UniversalAvatarResource.deleteAvatar_delete",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/user": {
      "get": {
        "summary": "Get user",
        "description": "Returns a user.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.UserResource.getUser_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "summary": "Create user",
        "description": "Creates a user. This resource is retained for legacy compatibility. As soon as a more suitable alternative is\n available this resource will be deprecated.\n <p>\n The option is provided to set or generate a password for the user. When using the option to generate a password,\n by omitting <code>password</code> from the request, include <code>\"notification\": \"true\"</code> to ensure the\n user is sent an email advising them that their account has been created. This ema[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.UserResource.createUser_post",
        "schemes": [],
        "deprecated": false,
        "x-experimental": true
      },
      "delete": {
        "summary": "Delete user",
        "description": "Deletes a user.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Site administration (that is, membership of the <em>site-admin</em>\n <a href=\"https://confluence.atlassian.com/x/24xjL\">group</a>). ",
        "summary": "com.atlassian.jira.rest.v2.issue.UserResource.removeUser_delete",
        "schemes": [],
        "deprecated": false,
        "x-experimental": true
      }
    },
    "/api/2/user/assignable/multiProjectSearch": {
      "get": {
        "summary": "Find users assignable to projects",
        "description": "Returns a list of users who can be assigned issues in one or more projects. The list may be restricted to users\n whose attributes match a string.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.issue.UserResource.findBulkAssignableUsers_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/user/assignable/search": {
      "get": {
        "summary": "Find users assignable to issues",
        "description": "Returns a list of users that can be assigned to an issue. Use this method to find the list of users who can be assigned to:\n <ul>\n <li>a new issue, by providing the <code>projectKeyOrId</code>.</li>\n <li>an updated issue, by providing the <code>issueKey</code>.</li>\n <li>to an issue during a transition (workflow action), by providing the <code>issueKey</code> and the transition id in\n <code>actionDescriptorId</code>. You can obtain the IDs of an issue's valid transit[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.UserResource.findAssignableUsers_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/user/bulk": {
      "get": {
        "summary": "Bulk get users",
        "description": "Returns details of the users specified in one or more user key, username, or user account ID parameters.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.user.UserBulkResource.bulkGetUsers_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false,
        "x-experimental": true
      }
    },
    "/api/2/user/bulk/migration": {
      "get": {
        "summary": "Bulk get users migration",
        "description": "Returns accountIds for the users specified in one or more user key or username parameters.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b> Permission to access Jira. ",
        "summary": "com.atlassian.jira.rest.v2.user.UserBulkResource.bulkGetUsersMigration_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false,
        "x-experimental": true
      }
    },
    "/api/2/user/columns": {
      "get": {
        "summary": "Get user default columns",
        "description": "Returns the default <a href=\"https://confluence.atlassian.com/x/XYdKLg\">issue table columns</a> for the user.\n If a username is not passed in the request, the calling user's details are returned.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLgl\">global permission</a>, to get\n the column details for any user. </li>\n <li>Permission to access Jira, to get the cal[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.UserResource.getUserDefaultColumns_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Set user default columns",
        "description": "Sets the default <a href=\"https://confluence.atlassian.com/x/XYdKLg\">\n issue table columns</a> for the user. If a username or account ID is not passed, the calling user's default columns are set. If no\n column details are sent, then all default columns are removed.\n <p>\n The parameters for this resource are expressed as HTML form data. For example, in curl:\n <code>curl -X PUT -d username=&#60;username&#62; -d columns=summary -d columns=description &#60;url&#62;</co[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.UserResource.setUserColumns_put",
        "schemes": [],
        "deprecated": false
      },
      "delete": {
        "summary": "Reset user default columns",
        "description": "Resets the default <a href=\"https://confluence.atlassian.com/x/XYdKLg\">\n issue table columns</a> for the user to the system default. If a username or account ID is not passed, the calling user's\n default columns are reset.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>, to set\n the columns on any user. </li>\n <li>Permission to access J[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.UserResource.resetUserColumns_delete",
        "schemes": [],
        "deprecated": false
      }
    },
    "/api/2/user/groups": {
      "get": {
        "summary": "Get user groups",
        "description": "Returns the groups to which a user belongs.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse users and groups</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. ",
        "summary": "com.atlassian.jira.rest.v2.issue.UserResource.getUserGroups_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/user/permission/search": {
      "get": {
        "summary": "Find users with permissions",
        "description": "Returns a list of users who fulfill these criteria:\n <ul>\n     <li>their user attributes match a search string.</li>\n     <li>they have a set of permissions for a project or issue.</li>\n </ul>\n If no search string is provided, a list of all users with the permissions is returned.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>, to get\n [...]",
        "summary": "com.atlassian.jira.rest.v2.issue.UserResource.findUsersWithAllPermissions_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/user/picker": {
      "get": {
        "summary": "Find users for picker",
        "description": "Returns a list of users whose attributes match the query term. The returned object\n includes the <code>html</code> field where the matched query term is highlighted with the HTML strong tag. A list\n of account IDs can be provided to exclude users from the results.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <em>Browse users and groups</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>. Users\n with permission to acce[...]",
        "summary": "com.atlassian.jira.rest.v2.issue.UserResource.findUsersForPicker_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/user/properties": {
      "get": {
        "summary": "Get user property keys",
        "description": "Returns the keys of all properties for a user.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n     <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>, to\n     access the property keys on any user.</li>\n     <li>Access to Jira, to access the calling user's property keys.</li>\n </ul>\n\n Note: These user properties are unrelated to the <a href=\"https://confluence.atlassian.com/x/8YxjL\">Jir[...]",
        "summary": "com.atlassian.jira.rest.v2.userproperty.UserPropertyResource.getUserPropertyKeys_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/api/2/user/properties/{propertyKey}": {
      "get": {
        "summary": "Get user property",
        "description": "Returns the value of a user's property. If no property key is provided\n <a href=\"#api-api-2-user-properties-get\">Get user property keys</a> is called.\n <p>\n <b><a href=\"#permissions\">Permissions</a> required:</b>\n <ul>\n     <li><em>Administer Jira</em> <a href=\"https://confluence.atlassian.com/x/x4dKLg\">global permission</a>, to get\n     a property from any user. </li>\n     <li>Access to Jira, to get a property from the calling user's record.</li>\n </ul>\n\n[...]",
        "summary": "com.atlassian.jira.rest.v2.userproperty.UserPropertyResource.getUserProperty_get",
        "schemes": [],
        "security": [
          {
            "OAuth2": [
              "read:jira-user"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "summary": "Set user property",
[...]
