/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('Admetica:Info', {});
  }

  /**
  Panel with ADMET predictions for a molecule.
  */
  export async function admeticaWidget(smiles: any ): Promise<any> {
    return await grok.functions.call('Admetica:AdmeticaWidget', { smiles });
  }

  /**
  Lists available ADMET properties.
  */
  export async function getModels(property: string ): Promise<any> {
    return await grok.functions.call('Admetica:GetModels', { property });
  }

  /**
  Runs ADMET predictions for Hit Triage.
  */
  export async function admeticaHT(table: DG.DataFrame , molecules: DG.Column , absorption: any | null, distribution: any | null, metabolism: any | null, excretion: any | null): Promise<void> {
    return await grok.functions.call('Admetica:AdmeticaHT', { table, molecules, absorption, distribution, metabolism, excretion });
  }

  export async function admeticaEditor(call: any ): Promise<void> {
    return await grok.functions.call('Admetica:AdmeticaEditor', { call });
  }

  /**
  Predicts ADMET properties and appends result columns.
  */
  export async function admeticaMenu(table: DG.DataFrame , molecules: DG.Column , template: string , models: any , addPiechart: boolean , addForm: boolean ): Promise<void> {
    return await grok.functions.call('Admetica:AdmeticaMenu', { table, molecules, template, models, addPiechart, addForm });
  }

  /**
  Predicts ADMET properties for a molecule column.
  */
  export async function getAdmeProperties(table: DG.DataFrame , molecules: DG.Column , props?: any ): Promise<DG.DataFrame> {
    return await grok.functions.call('Admetica:GetAdmeProperties', { table, molecules, props });
  }

  /**
  Predicts ADMET properties for a given molecule.
  */
  export async function getAdmePropertiesSingle(molecule: string ): Promise<DG.DataFrame> {
    return await grok.functions.call('Admetica:GetAdmePropertiesSingle', { molecule });
  }

  export async function runAdmeticaApplication(): Promise<DG.View> {
    return await grok.functions.call('Admetica:RunAdmeticaApplication', {});
  }

  /**
  Evaluating ADMET properties
  */
  export async function admeticaDemo(): Promise<void> {
    return await grok.functions.call('Admetica:AdmeticaDemo', {});
  }
}
