/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function info(): Promise<void> {
    return await grok.functions.call('ThreeBodyProblem:Info', {});
  }

  /**
  Interactive simulation of the CR3BP in the co-rotating frame with orbits, Lagrange points, Jacobi constant, and zero-velocity curves
  */
  export async function threeBodyProblemAppEntry(): Promise<void> {
    return await grok.functions.call('ThreeBodyProblem:ThreeBodyProblemAppEntry', {});
  }
}
