#!/bin/bash

# remove results of a previous build

for file in $(find . -name '*.ts')
do
  template=$(dirname $file)/$(basename $file .ts)
  dts=$template.d.ts
  map=$dts.map
  js=$template.js
  if [[ -f $js && -f $map && -f $js ]]; then
    rm --verbose -- $dts $map $js
  fi
done
