export const HELM_ITEM_SEPARATOR = '|';
export const HELM_SECTION_SEPARATOR = '$';
export const HYDROGEN_SYMBOL = 'H';
export const R_GROUP_ELEMENT_SYMBOL = 'R#';

export const enum V2K_CONST {
  MAX_ATOM_COUNT = 999,
  RGP_LINE_START = 'M  RGP',
  ATOM_ALIAS_LINE_START = 'A  ',
}

export const enum V3K_CONST {
  HEADER = `
     RDKit          2D

  0  0  0  0  0  0  0  0  0  0999 V3000`,
  BEGIN_CTAB = 'M  V30 BEGIN CTAB',
  COUNTS_LINE_START = 'M  V30 COUNTS ',
  COUNTS_LINE_END = ' 0 0 0',
  BEGIN_ATOM_BLOCK = 'M  V30 BEGIN ATOM',
  END_ATOM_BLOCK = 'M  V30 END ATOM',
  BEGIN_BOND_BLOCK = 'M  V30 BEGIN BOND',
  END_BOND_BLOCK = 'M  V30 END BOND',
  BEGIN_COLLECTION_BLOCK = 'M  V30 BEGIN COLLECTION',
  END_COLLECTION_BLOCK = 'M  V30 END COLLECTION',
  END_CTAB = 'M  V30 END CTAB',
  END = 'M  END\n',
}

