-- Domain schema mpo: 1.0.0 -> 1.1.0
-- ems-migration: from=bcc814671211eecac10bf060e5ac411952fca85d651e2dde623992cb8469ee49 to=1207ca37bfd49df69e5c9c3c5953c25db9f791a9f49897c0837682c219333c4e
-- Generated by the schema snapshot tool from snapshot bcc814671211 to 1207ca37bfd4.
-- Registry-only changes (no SQL; converged by the next registration):
--   * table-knob profile: grants (none) -> {"All users":["view","edit","delete"]}
--   * column-meta profile.properties: description "The scored properties and their desirability curves, as JSON." -> "The scored properties and their desirability curves, keyed by property name."

-- change-type profile.properties: type string -> json [manual]
-- Every stored value is the JSON object MpoProfileStore.toRow wrote, so the cast is lossless.
ALTER TABLE mpo.profile ALTER COLUMN properties TYPE jsonb USING properties::jsonb;
