/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function testViewerComponent(): Promise<void> {
    return await grok.functions.call('LibTests:TestViewerComponent', {});
  }

  export async function testFromComponent(): Promise<void> {
    return await grok.functions.call('LibTests:TestFromComponent', {});
  }

  export async function testElements(): Promise<void> {
    return await grok.functions.call('LibTests:TestElements', {});
  }

  export async function testAdd2(a: number , b: number ): Promise<number> {
    return await grok.functions.call('LibTests:TestAdd2', { a, b });
  }

  export async function testSub2(a: number , b: number ): Promise<number> {
    return await grok.functions.call('LibTests:TestSub2', { a, b });
  }

  export async function testMul2(a: number , b: number ): Promise<number> {
    return await grok.functions.call('LibTests:TestMul2', { a, b });
  }

  export async function testDiv2(a: number , b: number ): Promise<number> {
    return await grok.functions.call('LibTests:TestDiv2', { a, b });
  }

  export async function testDF1(df: DG.DataFrame ): Promise<DG.DataFrame> {
    return await grok.functions.call('LibTests:TestDF1', { df });
  }

  export async function testPresets(): Promise<DG.DataFrame> {
    return await grok.functions.call('LibTests:TestPresets', {});
  }

  export async function testFileInput(inputFile: DG.FileInfo ): Promise<string> {
    return await grok.functions.call('LibTests:TestFileInput', { inputFile });
  }

  export async function testAdd2Error(a: number , b: number ): Promise<number> {
    return await grok.functions.call('LibTests:TestAdd2Error', { a, b });
  }

  export async function testMultiarg5(a: number , b: number , c: number , d: number , e: number ): Promise<number> {
    return await grok.functions.call('LibTests:TestMultiarg5', { a, b, c, d, e });
  }

  export async function testIONamesA(seed: number ): Promise<{x: number, y: number}> {
    return await grok.functions.call('LibTests:TestIONamesA', { seed });
  }

  export async function testIONamesB(x: number , y: number ): Promise<number> {
    return await grok.functions.call('LibTests:TestIONamesB', { x, y });
  }

  export async function testIONamesBReversed(y: number , x: number ): Promise<number> {
    return await grok.functions.call('LibTests:TestIONamesBReversed', { y, x });
  }

  export async function testIONamesAExtra(seed: number ): Promise<{x: number, y: number, z: number}> {
    return await grok.functions.call('LibTests:TestIONamesAExtra', { seed });
  }

  export async function mockWrapper1(params: any ): Promise<any> {
    return await grok.functions.call('LibTests:MockWrapper1', { params });
  }

  export async function mockWrapper2(params: any ): Promise<any> {
    return await grok.functions.call('LibTests:MockWrapper2', { params });
  }

  export async function mockWrapper3(params: any ): Promise<any> {
    return await grok.functions.call('LibTests:MockWrapper3', { params });
  }

  export async function mockWrapper4(params: any ): Promise<any> {
    return await grok.functions.call('LibTests:MockWrapper4', { params });
  }

  export async function mockWrapper5(params: any ): Promise<any> {
    return await grok.functions.call('LibTests:MockWrapper5', { params });
  }

  export async function mockWrapperAction(params: any ): Promise<any> {
    return await grok.functions.call('LibTests:MockWrapperAction', { params });
  }

  export async function mockWrapperDF(params: any ): Promise<any> {
    return await grok.functions.call('LibTests:MockWrapperDF', { params });
  }

  export async function testToleranceInputs(plain: number , abs: number , rel: number , df: DG.DataFrame ): Promise<number> {
    return await grok.functions.call('LibTests:TestToleranceInputs', { plain, abs, rel, df });
  }

  /**
   * @param {string} mode
   *   choices: ["fast", "exact"]
   * @param {DG.Column} mol
   *   semType: Molecule
   */
  export async function testAnnotatedInputs(a: number | null, b: number | undefined, c: number , v: number , code: string , mode: string , df: DG.DataFrame , col: DG.Column , mol: DG.Column ): Promise<number> {
    return await grok.functions.call('LibTests:TestAnnotatedInputs', { a, b, c, v, code, mode, df, col, mol });
  }

  /**
   * @param {string} city
   *   choices: LibTests:MockCities
   */
  export async function testReservedNames(region: string , city: string , call: string , all: string , table: number , target: number , literals: number , x: number ): Promise<string> {
    return await grok.functions.call('LibTests:TestReservedNames', { region, city, call, all, table, target, literals, x });
  }

  export async function mockValidator(x: number ): Promise<string> {
    return await grok.functions.call('LibTests:MockValidator', { x });
  }

  export async function testNamedValidators(x: number , y: number ): Promise<number> {
    return await grok.functions.call('LibTests:TestNamedValidators', { x, y });
  }

  export async function mockCities(region: string ): Promise<any> {
    return await grok.functions.call('LibTests:MockCities', { region });
  }

  export async function mockCountingCities(region: string ): Promise<any> {
    return await grok.functions.call('LibTests:MockCountingCities', { region });
  }

  /**
   * @param {string} city
   *   choices: LibTests:MockCountingCities
   */
  export async function testCountingChoices(region: string , city: string , n: number ): Promise<string> {
    return await grok.functions.call('LibTests:TestCountingChoices', { region, city, n });
  }

  export async function mockCars(): Promise<DG.DataFrame> {
    return await grok.functions.call('LibTests:MockCars', {});
  }

  /**
   * @param {string} metric
   *   choices: ["euclidean", "minkowski"]
   * @param {string} speed
   *   choices: ["slow", "fast"]
   * @param {string} city
   *   choices: LibTests:MockCities
   * @param {string} model
   *   choices: LibTests:MockCars()
   */
  export async function testValueAnnotations(calc: number , bare: string , metric: string , speed: string , region: string , city: string , model: string , mpg: number , cyl: number ): Promise<string> {
    return await grok.functions.call('LibTests:TestValueAnnotations', { calc, bare, metric, speed, region, city, model, mpg, cyl });
  }

  export async function mockCarsTyped(): Promise<DG.DataFrame> {
    return await grok.functions.call('LibTests:MockCarsTyped', {});
  }

  export async function mockEngines(): Promise<DG.DataFrame> {
    return await grok.functions.call('LibTests:MockEngines', {});
  }

  /**
   * @param {string} model
   *   choices: LibTests:MockCarsTyped()
   * @param {string} engine
   *   choices: LibTests:MockEngines()
   */
  export async function testLookupAnnotations(model: string , engine: string , cyl: number , mpg: number , name: string , flag: boolean , when: any , made: any ): Promise<string> {
    return await grok.functions.call('LibTests:TestLookupAnnotations', { model, engine, cyl, mpg, name, flag, when, made });
  }

  export async function mockValidatorBool(x: number ): Promise<boolean> {
    return await grok.functions.call('LibTests:MockValidatorBool', { x });
  }

  export async function mockValidatorThrow(x: number ): Promise<string> {
    return await grok.functions.call('LibTests:MockValidatorThrow', { x });
  }

  export async function testExpressionInputs(k: number , hv: number , foo: number , bar: number , code: string ): Promise<number> {
    return await grok.functions.call('LibTests:TestExpressionInputs', { k, hv, foo, bar, code });
  }

  export async function testEnabledInputs(k: number , en: number , both: number ): Promise<number> {
    return await grok.functions.call('LibTests:TestEnabledInputs', { k, en, both });
  }

  export async function loadProfile(): Promise<DG.DataFrame> {
    return await grok.functions.call('LibTests:LoadProfile', {});
  }

  /**
   * @param {string} subject
   *   choices: []
   * @param {string} route
   *   choices: ["iv", "oral"]
   * @param {string} doseUnit
   *   choices: ["mg", "mg/kg"]
   * @param {string} method
   *   choices: ["LSODA", "RK45"]
   */
  export async function pkModel(profile: DG.DataFrame , time: DG.Column , subject: string | null, route: string , dose: number , doseUnit: string , weight: number | null, ka: number | null, compound: string | null, clearance: number , volume: number , duration: number , method: string , tolerance: number | null): Promise<number> {
    return await grok.functions.call('LibTests:PkModel', { profile, time, subject, route, dose, doseUnit, weight, ka, compound, clearance, volume, duration, method, tolerance });
  }

  export async function allometricClearance(weight: number | null): Promise<number> {
    return await grok.functions.call('LibTests:AllometricClearance', { weight });
  }

  export async function checkTolerance(tolerance: number ): Promise<string> {
    return await grok.functions.call('LibTests:CheckTolerance', { tolerance });
  }
}
