// Worker for the function 'doubledInts'.

// Import from JS-file generated by Emscripten
import {exportLib} from '../wasm/LibForWebWorker';

// Import utilities
import {cppWrapper} from './callWasmUtils';

onmessage = async function (evt) {
  exportLib().then(module => 
    {     
        // exctract arguments to be put to wasm-function
        let args = evt.data

        // call c++/wasm-function via wrapper
        let result = cppWrapper(module, args, 'doubledInts', 'number');

        // post results
        postMessage({'callResult': result, 'args': args});
    } )
}