// Worker for the function 'pca'.

// Import from JS-file generated by Emscripten
import {exportAnalyzer} from '../wasm/AnalyzerForWebWorker';

// Import utilities
import {cppWrapper} from './callWasmUtils';

onmessage = async function (evt) {
  exportAnalyzer().then(module => 
    { 
        // exctract arguments to be put to wasm-function    
        let args = evt.data

        // call c++/wasm-function via wrapper
        let result = cppWrapper(module, args, 'principalComponentAnalysis', 'number');

        // post results
        postMessage({'callResult': result, 'args': args});
    } )
}