/**
This file is auto-generated by the grok api command.
If you notice any changes, please push them to the repository.
Do not edit this file manually.
*/
import * as grok from 'datagrok-api/grok';
import * as DG from 'datagrok-api/dg';


export namespace funcs {
  export async function previewEps(file: DG.FileInfo ): Promise<DG.View> {
    return await grok.functions.call('EPSViewer:PreviewEps', { file });
  }
}
