name: Test Notif
on:
  workflow_dispatch: { }
  push:
    branches:
      - vhlushchenko/GROK-15351-github-notification
jobs:
  notif:
    name: Check version
    runs-on: ubuntu-22.04
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      - name: ls
        run: ls -la
      - name: Prepare Slack Message
        if: ${{ steps.publish.outcome == 'success' && !contains(matrix.package, 'Meta') }}
        id: slack-prepare
        shell: bash
        env:
          SLACK_ID: ${{ secrets.SLACK_ID }}
        run: |
          channel_id=$(echo "$SLACK_ID" | jq -r .\"${{ github.actor }}\")
          echo "::add-mask::$channel_id"
          echo SLACK_CHANNEL=$channel_id >> $GITHUB_ENV
      
      - uses: xaroth/action-slack-notification@v1
        with:
          channel-id: ${{ env.SLACK_CHANNEL }}
          slack-token: ${{ secrets.SLACKBOT_TOKEN }}
      - name: Some action
        uses: trabe/github-actions-slack-job-status@v1
        id: post-to-slack
        if: always()
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: ${{ toJson(github.event) }}
          head_ref: ${{ github.head_ref }}
          base_ref: ${{ github.base_ref }}
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACKBOT_TOKEN }}
          channel: "D06NWJH4EHE"
        #   - uses: mdecoleman/slack-job-status-notifier@v1
        # if: always()
        # with:
        #   slack_token:  ${{ secrets.SLACKBOT_TOKEN }}
        #   slack_channel: ${{ env.SLACK_CHANNEL }}
        #   status: ${{ job.status }}
        #   job_name: "123"

