name: Test Notif
on:
  workflow_dispatch: { }
  push:
    branches:
      - vhlushchenko/GROK-15351-github-notification
jobs:
  notif:
    name: Check version
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ls
        run: ls -la
      - name: Prepare Slack Message
        if: ${{ steps.publish.outcome == 'success' && !contains(matrix.package, 'Meta') }}
        id: slack-prepare
        shell: bash
        env:
          SLACK_ID: ${{ secrets.SLACK_ID }}
        run: |
          channel_id=$(echo "$SLACK_ID" | jq -r .\"${{ github.actor }}\")
          echo "::add-mask::$channel_id"
          echo SLACK_CHANNEL=$channel_id >> $GITHUB_ENV
      - name: Send Slack notification for job status
        id: notifyjobstatus-id
        uses: KK-Repos/NotifyJobStatus@v1
        with:
          GH_PROJECT_ORGNAME: 'your-organization'
          GH_PROJECT_REPONAME: 'your-repository'
          RUN_ID: ${{ github.run_id }}
          JOB_NAME_1: 'job_name_1'
          JOB_NAME_2: 'job_name_2'  # Optional
          CHANNEL_ID: ${{ env.SLACK_CHANNEL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}

